AscensionGameDev/Intersect-Engine

Intersect.Server/Database/PlayerData/Api/RefreshToken.cs
Intersect.Server/Database/PlayerData/User.cs
Intersect.Server/Entities/Player.Database.cs

This addresses #54 
The general gist is compiled queries do not actually load data, they return an `IQueryable<T>` which has a reference to the context in order to load the data. This happens with transformations like `ToList()`.
With this change, `ToList()` is now called within the confines of the locking region, rather than outside of it. Since all of our reads are bounded by locking regions, this ensures that the list reads do not collide with any other database accesses.

Properly load list data within locking region

---

Intersect (Core)/Intersect (Core).csproj
Intersect (Core)/Network/Events/ConnectionEventArgs.cs
Intersect (Core)/Network/INetworkLayerInterface.cs
Intersect (Core)/Network/NetworkStatus.cs
Intersect.Client.Framework/Network/GameSocket.cs
Intersect.Client/Interface/Menu/MainMenu.cs
Intersect.Client/Localization/Strings.cs
Intersect.Client/MonoGame/IntersectGame.cs
Intersect.Client/MonoGame/Network/MonoSocket.cs
Intersect.Client/Networking/Network.cs
Intersect.Client/Networking/NetworkStatus.cs
Intersect.Editor/Networking/Network.cs
Intersect.Network/ClientNetwork.cs
Intersect.Network/LidgrenInterface.cs
Intersect.Server/Networking/Lidgren/ServerNetwork.cs

Implements more detailed server status details for the main menu in the client for #63.
Introduces server full string and network status enum, but it is *not* currently used.
"Server full" will be implemented separately in the future to fulfill #77.

Implement #63: Server status details

---

Intersect.Network/LidgrenInterface.cs

Resolves #94 
**Issue**:
When the server is offline for a sufficient duration it is given a disconnect reason of `Failed to establish connection - no response from remote host`, which didn't have a mapping.
That moved it to a status of `Unknown` which was being treated as a denial of connection.
After connection denial, the client makes no further attempts to connect to the server.
**Resolution**:
Add additional mapping to offline.
Treat unknown as disconnect instead of denial.

Fix 94: Add non-response reason and treat unknown as disconnect

---

Intersect.Client/Intersect.Client.csproj
Intersect.Client/MonoGame/Audio/MonoMusicInstance.cs
Intersect.Client/MonoGame/Audio/MonoMusicSource.cs
Intersect.Client/MonoGame/Graphics/MonoRenderer.cs
Intersect.Client/Networking/NetworkStatus.cs
Intersect.Client/app.config
Intersect.Client/packages.config
Intersect.Tests.Client/app.config
NuGet.Config

Upgrades the version of MonoGame we use to a recent develop build with our OpenGL audio fixes included.
Nothing really important to note here other than it also requires an updated radial gradient shader.
People will need to download and replace their Client/resources/shaders/radialgradient.xnb with the one inside [this zip archive](https://github.com/AscensionGameDev/Intersect-Engine/files/4464398/radialgradient.zip).
This also reverts our DynamicSoundEffectInstance changes and goes back to using Songs/MediaPlayer for ogg playback since it handles streaming really well.
This will resolve #116 and resolve #102.
@panda please feel free to add your review but please don't merge yet. Thanks!

Upgrading monogame to dev

---

Intersect (Core)/Config/LootOptions.cs
Intersect (Core)/Config/MapOptions.cs
Intersect (Core)/Config/Options.cs
Intersect (Core)/Intersect (Core).csproj
Intersect.Client/Entities/Entity.cs
Intersect.Client/Entities/Player.cs
Intersect.Client/Items/MapItem.cs
Intersect.Client/Maps/MapInstance.cs
Intersect.Server/Entities/Entity.cs
Intersect.Server/Entities/Npc.cs
Intersect.Server/Entities/Player.cs
Intersect.Server/Entities/Resource.cs
Intersect.Server/Localization/Strings.cs
Intersect.Server/Maps/MapInstance.cs
Intersect.Server/Maps/MapItemInstance.cs
Intersect.Server/Networking/PacketHandler.cs

Resolves #182 
Resolves #184 
Adds the ability to tag MapItems with an owner, and only allow the owner (and their party) to pick the items up for a configurable amount of time.
NPC drops will attempt to use the player that did the most damage to it as the owner, unless killed by something other than a player.
Player drops will attempt to use player that did the killing blow as the owner for the items. Unless killed by something else.
Items dropped from the inventory voluntarily are also subject to ownership.
[Preview](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/6e3028d392bae32b70620ae58e7901fc.gif)
Some small fixes are mixed in to this as well as I run into them.

Assigning loot ownership + small fixes

---

Intersect.Client/Interface/Game/PartyWindow.cs

Resolves #199
This fix checks to see if the player's max vital for health or mana is over 0 before doing any math to see how to resize the bar, much like it works on the EntityBox. If max vital is not over 0, just set the bar to display as full like it does on the EntityBox.

Fix party max vitals being set to 0 resulting in a divide by 0 issue.

---

Intersect.Editor/Forms/Editors/frmItem.cs

Resolves #206 
Enforce Stackability on Currency type items in the editor, and disable the option to remove this.

Enforce stackability and disable the checkbox on item editor for currencies

---

Intersect.Editor/Forms/Editors/frmItem.cs

Belonged in issue #206 as well, but was missed. Oopsie.

Disables the Stackable checkbox on both Equipment and Bag item types as well

---

Intersect.Server/Entities/Player.cs

Resolves #220 
For the master branch, only return the maximum size back to 4.
Development gets the fancy stuff. ;)

Return the max party size to 4

---

Intersect (Core)/Config/Options.cs
Intersect (Core)/Config/PartyOptions.cs
Intersect.Client/Interface/Game/PartyWindow.cs
Intersect.Server/Entities/Player.cs
Intersect.Server/Networking/PacketHandler.cs

Resolves #226 
- Fixes a max party size discrepancy where it was accidentally set to 10, but was still 4 in other areas.
- Added a Party option to allow the maximum party size to be set through the server config file.
- Removed some Top Level party config options, they should really be referenced through the Party section.

Make the maximum party size user configurable

---

Intersect.Client/Interface/Game/GameInterface.cs
Intersect.Client/Interface/Game/Menu.cs

Resolves #214 
Good when opening Trade, Bank, Shop, Crafting ... the inventory is not open in my opinion it should be opened so that the player knows what is giving, receiving and others

Open InventoryWindow when Bank,Shop,Trade or CraftingTable Open

---

Intersect.Server/Entities/Player.cs

Resolves #262 
Consumable sing in action message could have two minus sign or could be negative while the real value is positive. A more detailled explanation below:
[Go to the bug report](https://github.com/AscensionGameDev/Intersect-Engine/issues/262)

Fix wrong consumable sign in action message

---

Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_PlayAnimation.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_SpawnNpc.cs
Intersect.Editor/Forms/Helpers/GridHelper.cs
Intersect.Editor/Intersect.Editor.csproj

Resolves #232 
Introduces `Intersect.Editor.Forms.Helpers.GridHelper`:
- Draws grids of a specified column/row count
- Grid tiles can be specified, with labels rendering over top of simple background color tiles
- Selection tile (`red`) is rendered at `<spawn X>,<spawn Y>`
- `E` tile is rendered second at `2,2`
- Cell sizes scale according to destination bitmap size to account for environmental skew and scaling
- This is to accommodate an older bug that has been seen but unable to diagnose where the panel would be skewed (and not evenly) on some systems but is totally normal on others
Updates the following selection panels to use `GridHelper` for rendering:
- `EventCommand_PlayAnimation` (the part that addresses #287)
- `EventCommand_SpawnNpc`

fix 232: common autoscaling grid rendering

---

Intersect.Server/Database/PlayerData/Ban.cs
Intersect.Server/Database/PlayerData/Mute.cs

Resolves #268 
Realized mutes will have the same issue, and fixed those as well
After a ban/mute is selected by user or IP, it is checked to see if it
is expired. If it has been expired, null is returned and it is removed.

fix 268: check if ban expired

---

Intersect (Core)/Config/NpcOptions.cs
Intersect (Core)/Config/Options.cs
Intersect (Core)/Intersect (Core).csproj
Intersect.Server/Entities/Npc.cs

Adds features requested in #302 
Request discussed in shoutbox pertained a reset radius, not a new behaviour type though..
Adds the ability to configure several new global options for NPC behaviour through the server configuration:
* AllowResetRadius - Configures whether or not Npcs are allowed to reset after moving out of a specified radius when starting to fight another entity.
* ResetRadius - Configures the radius in which an NPC is allowed to move after starting to fight another entity.
* AllowNewResetLocationBeforeFinish - Configures whether or not the NPC is allowed to gain a new reset center point while it is still busy moving to its original reset point. NOTE: Can be used to allow the NPCs to be dragged far far away, as it constantly resets the center of its radius!!!
* …

Configurable reset radius and behaviour for NPCs after going into combat.

---

Intersect (Core)/Config/Options.cs
Intersect (Core)/Config/SpriteOptions.cs
Intersect (Core)/Intersect (Core).csproj
Intersect.Client/Entities/Entity.cs
Intersect.Client/Entities/Events/Event.cs
Intersect.Client/Interface/Game/AdminWindow.cs
Intersect.Client/Interface/Game/Character/CharacterWindow.cs
Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
Intersect.Client/Interface/Menu/CreateCharacterWindow.cs
Intersect.Client/Interface/Menu/SelectCharacterWindow.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ChangeSprite.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/Event_GraphicSelector.cs
Intersect.Editor/Forms/Editors/Events/frmEvent.cs
Intersect.Editor/Forms/Editors/frmClass.cs
Intersect.Editor/Forms/Editors/frmNpc.cs
Intersect.Editor/Forms/Editors/frmSpell.cs

Pulls out options for # of sprite frames, time before idling, and more into the server config instead of being hard coded into the client/editor.
Changes a lot of "/4" and "/8" into meaningful and readable values.
Resolves #316

Sprite Options (Frames/Timing/Etc)

---

Intersect (Core)/Configuration/ClientConfiguration.cs
Intersect.Client/Core/Graphics.cs
Intersect.Client/Entities/Player.cs
Intersect.Client/MonoGame/IntersectGame.cs

Adds very basic support for a custom mouse cursor.
Can be set from the client configuration, since we want the cursor to work even if we don't have a connection to the server.
Hides the normal OS mouse.
Had to generalize a piece of code for re-using, because I didn't want to end up duplicating the code calculating the mouse's actual world position.

Custom Mouse Cursor

---

Intersect.Client.Framework/GenericClasses/Clipboard.cs
Intersect.Client.Framework/Gwen/Control/MultilineTextBox.cs
Intersect.Client.Framework/Gwen/Control/TextBox.cs
Intersect.Client.Framework/Intersect.Client.Framework.csproj
Intersect.Client/Interface/Game/Chat/Chatbox.cs
Intersect.Client/Localization/Strings.cs

Resolves #178 
I know JC asked to put the clipboard logic in the client itself, but the handlers are all in the Client Framework and adding the accellerators outside the components to each textbox instance we create does not sound fun.
Unless someone has a better option?
Also warns users they are missing the appropriate Linux libraries upon logging in through the chat box. Wonder if it might be cleaner to throw them a warning when they open the client?

Allow clipboard access cross platform

---

Intersect.Client/Interface/Game/InputBox.cs
Intersect.Client/Interface/Menu/LoginWindow.cs
Intersect.Client/Interface/Menu/RegisterWindow.cs

resolves #357 
Haven't figured out a way to do the same for Event dialogs with a single choice, either Gwen doesn't let me submit buttons with return or it's not retaining focus.
Still, this sets the focus on a few forms properly so we can submit with enter and tab through things.

Setting focus to appropriate window elements, allow for return submits

---

Intersect.Editor/Forms/Editors/frmClass.cs

The map list wasn't selecting the first map when another map had been chosen and the selected class has a spawn map id of Guid.Empty.
Resolves #352

Fix map dropdown not updating when changing classes

---

Intersect.Editor/Core/Database.cs
Intersect.Editor/Core/Graphics.cs
Intersect.Editor/Forms/Editors/Events/frmEvent.Designer.cs
Intersect.Editor/Forms/Editors/Events/frmEvent.cs
Intersect.Editor/Forms/frmMain.Designer.cs
Intersect.Editor/Forms/frmMain.cs
Intersect.Editor/Forms/frmMain.resx
Intersect.Editor/Localization/Strings.cs

resolves #236
resolves #344 
This PR accomplishes two little things that might help out our more avid Event users:
- The event command list will attempt to remember where the user last added/removed a command and tries to select the item again to scroll back to it. (Especially helpful in LOOOOOOOOONG event command lists)
- The map editor has received an option to render Event previews in the map editor screen, rather than only the square E symbol on the event tab. The Event graphics are always rendered, unless the option under View is not ticked.

Scrollback on event editor, event map previews

---

Intersect (Core)/GameObjects/Maps/MapAttribute.cs
Intersect.Client/Entities/Player.cs
Intersect.Editor/Forms/DockingElements/frmMapLayers.Designer.cs
Intersect.Editor/Forms/DockingElements/frmMapLayers.cs
Intersect.Editor/Localization/Strings.cs
Intersect.Server/Entities/Entity.cs
Intersect.Server/Entities/Projectile.cs
Intersect.Server/Maps/MapInstance.cs

Reverts AscensionGameDev/Intersect-Engine#369
We need to revert this modification because it will break games until we do a db migration and save our map attributes using ceras with version tolerance enabled.

Revert "Add option for map animations to be considered blocks"

---

Intersect.Client/MonoGame/File Management/MonoContentManager.cs

resolves #386 
Recent quick and dirty fix in #371 broke tileset loading for asset packs.
- The directory was always assumed to exist, even when it does not (which is not the case for other assets)
- When using asset packs, the realFileName was null, crashing Path.Combine()

Fix prerelease Asset Pack tileset loading

---

Intersect (Core)/Config/ChatOptions.cs
Intersect (Core)/Config/Options.cs
Intersect (Core)/Intersect (Core).csproj
Intersect (Core)/Network/Packets/Server/AnnouncementPacket.cs
Intersect.Client/Interface/Game/AnnouncementWindow.cs
Intersect.Client/Interface/Game/GameInterface.cs
Intersect.Client/Intersect.Client.csproj
Intersect.Client/Networking/PacketHandler.cs
Intersect.Server/Core/Commands/AnnouncementCommand.cs
Intersect.Server/Networking/PacketHandler.cs
Intersect.Server/Networking/PacketSender.cs

Ran into notifications disappearing into chat spam on a game, so decided to write up a quick little solution.. The option to display an announcement pop-up in game!
Can be disabled in the server config. 
Timing for it is configurable there as well.
Works with the in-game announcement command as well as the server console one.
Additional resources: [Download](https://www.ascensiongamedev.com/resources/filehost/6824b9e000bf9d84a59db8a3089733b8.zip)

Allow announcements to show a pop-up on the client-side.

---

Intersect (Core)/Intersect (Core).csproj
Intersect (Core)/Network/Delegates.cs
Intersect (Core)/Network/HandlePacket.cs
Intersect (Core)/Network/IPacketHandler.cs
Intersect (Core)/Network/IPacketSender.cs
Intersect (Core)/Network/PacketHandlerAttribute.cs
Intersect (Core)/Network/PacketHandlerRegistry.DisposableHandler.cs
Intersect (Core)/Network/PacketHandlerRegistry.cs
Intersect (Core)/Reflection/MemberInfoExtensions.cs
Intersect.Client/Networking/Network.cs
Intersect.Client/Networking/PacketHandler.cs
Intersect.Editor/Networking/Network.cs
Intersect.Editor/Networking/PacketHandler.cs
Intersect.Server/Core/ServerContext.cs
Intersect.Server/Entities/Player.cs
Intersect.Server/Networking/Client.cs
Intersect.Server/Networking/PacketHandler.cs
Intersect.Server/Networking/PacketSender.cs
Intersect.Tests/Intersect.Tests.csproj
Intersect.Tests/Network/PacketHandlerAttributeTests.cs

Resolves #446 
Adapted [Jon Skeet's blog post](https://blogs.msmvps.com/jonskeet/2008/08/09/making-reflection-fly-and-exploring-delegates/) to fit our use case.
Added (non-public) endpoints in the registry to enable blindly registering _static only_ delegates across an entire assembly and registering interface-based packet handlers for future implementations.
- The static only delegates option may be outright removed, it's not a very good paradigm and if we remove delegates entirely we can remove most if not all of the horrible wrapper system.
This updates the client, server and editor.
Client and editor got an extra parameter in packet handlers, server lost one.
All dynamic nested packet handling is now non-dynamic (it never needed to be dynamic...), the only dynamic is for admin actions …

Thank you Jon Skeet

---

Intersect (Core)/Core/ApplicationContext`2.cs
Intersect (Core)/Intersect (Core).csproj
Intersect (Core)/Network/MessagePacker.cs
Intersect (Core)/Network/PackedIntersectPacket.cs
Intersect.Client/Core/ClientContext.cs
Intersect.Editor/Networking/Network.cs
Intersect.Server/Core/ServerContext.cs

By wrapping packets into a class that saves them as an integer.
Intead of prefixing every packet with a full type name such as the one here:
"Intersect.Network.Packets.Client.AdminActionPacket, Intersect Core, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null"
Fixes #492

Reduce packet sizes 

---

Intersect.Server/Database/Item.cs

Clone dropchance when cloning items to fix all items always dropping

---

Intersect.Client/Maps/MapInstance.cs

Use a preset color to draw map item names if custom color for the set rarity doesn't exist.

---

Intersect (Core)/Config/CombatOptions.cs
Intersect.Client/Entities/Player.cs
Intersect.Client/Networking/PacketHandler.cs
Intersect.Server/Entities/Entity.cs

Enhancement was unintentionally pulled in while merging changes made to Leafling, allowing it as an option (disabled by default) seems to be the best move forward.
Resolves #517

Resolves 517 by making spell cast canceling via movement optional

---

Intersect.Server/Core/LogicService.LogicThread.cs

No need for the loop to iterate 1.8 million times a second for something that only divys out work to other threads.

Fix cpu burning by sleeping instead of yielding on the main server loop

---

Intersect (Core)/Config/NpcOptions.cs
Intersect (Core)/Config/PlayerOptions.cs
Intersect (Core)/Enums/TagsPosition.cs
Intersect.Client.Framework/File Management/GameContentManager.cs
Intersect.Client/Core/Graphics.cs
Intersect.Client/Entities/Entity.cs
Intersect.Client/Entities/Player.cs
Intersect.Client/MonoGame/File Management/MonoContentManager.cs

Resolves #394 
This PR implements _Default and Custom Tags_ for **Npcs** **+** _Custom Tags_ for **Players**  !
> `Re-opened this PR because the initial code/idea changed a lot and it may be easier to review it on a single commit.`
> PS : _To whoever decides to review this (lodicolo was first reviewing) - i would like to ask if the development has a discord group or something similar that allows us to speak in real time in order to avoid unnnecesary PRs and commits. Thanks <3_
Devs are opted out of this feature by default (bool = **false** for **ShowTags** in server/resources/config.json), they may toggle it on if they want to test their own tags with Npcs and Players.
Few Examples of this Feature Implementation:
> ![CtsmNpc Players](https://user-images.githubusercontent.com/17498701/10865 …

Player & Npc Tags Implementation

---

Intersect.Server/Entities/Npc.cs

This line shouldn't exist. It spams clients with npc aggression updates even when the aggression isn't changing

Reduce NPC Aggression Packet Spam

---

Intersect (Core)/Network/Packets/Server/ProjectileDeadPacket.cs
Intersect.Client/Networking/PacketHandler.cs
Intersect.Server/Entities/Entity.cs
Intersect.Server/Entities/Projectile.cs
Intersect.Server/Entities/ProjectileSpawn.cs
Intersect.Server/Maps/MapInstance.cs
Intersect.Server/Networking/PacketSender.cs

Batch projectile and projectile spawn deaths into a singular packet when updating maps

Fix projectile packets being sent too much

---

Intersect.Server/Database/Item.cs
Intersect.Server/Database/PlayerData/Players/Variable.cs
Intersect.Server/Database/PlayerData/User.cs
Intersect.Server/Database/Spell.cs
Intersect.Server/Entities/Entity.cs
Intersect.Server/Entities/Player.Database.cs
Intersect.Server/Entities/Player.cs
Intersect.Server/Intersect.Server.csproj
Intersect.Server/Localization/Strings.cs
Intersect.Server/Networking/PacketHandler.cs
Intersect.Server/Notifications/Notification.cs
Intersect.Server/Web/RestApi/Payloads/ClassChange.cs
Intersect.Server/Web/RestApi/Payloads/LevelChange.cs
Intersect.Server/Web/RestApi/Payloads/NameChange.cs
Intersect.Server/Web/RestApi/Routes/V1/GameObjectController.cs
Intersect.Server/Web/RestApi/Routes/V1/InfoController.cs
Intersect.Server/Web/RestApi/Routes/V1/PlayerController.cs
Intersect.Server/Web/RestApi/Routes/V1/UserController.cs

Users List
- Added search parameter that searches against name and email address
- Added sort parameter which will sort via email or name
Players List
- Added search parameter that searches against name and email address
- Added sort parameter which will sort via name or rank (level + experience)
User Name Changes
Player Name Changes
Deleting Users
Deleting Players
Bug Fixes

Extended API Endpoints

---

Intersect (Core)/Config/NpcOptions.cs
Intersect.Server/Entities/Entity.cs
Intersect.Server/Entities/Npc.cs

Should resolve #643 
ContinuouslyResetVitalsAndStatuses (true/false) will determine whether the npc restores hp/resets statuses while they work their way back to their reset point.
AllowEngagingWhileResetting (true/false) will determine if a npc that is resetting can be engaged again if their new attacker is within the reset radius.

Added more npc reset options

---

Intersect (Core)/GameObjects/Maps/MapAttribute.cs
Intersect.Client/Entities/Player.cs
Intersect.Editor/Forms/DockingElements/frmMapLayers.Designer.cs
Intersect.Editor/Forms/DockingElements/frmMapLayers.cs
Intersect.Editor/Localization/Strings.cs
Intersect.Server/Entities/Entity.cs
Intersect.Server/Entities/Projectile.cs
Intersect.Server/Maps/MapInstance.cs

Reintroducing this PR for map animation blocks.
This was all merged before in #369 for issue #368 but that PR broke the engine due to no sort of fault tolerance with how we were serializing map tiles/attributes.
Now that #379 as been merged this is safe to reintroduce.

Option for map animation attributes to also be blocked tiles

---

Intersect (Core)/Config/Options.cs
Intersect (Core)/Config/PacketOptions.cs
Intersect (Core)/Config/PacketSecurityOptions.cs
Intersect (Core)/Config/SecurityOptions.cs
Intersect (Core)/Intersect (Core).csproj
Intersect (Core)/Network/Packets/Server/ActionMsgPackets.cs
Intersect (Core)/Network/Packets/Server/EntityMovementPackets.cs
Intersect (Core)/Network/Packets/Server/PlayAnimationPackets.cs
Intersect.Client/Networking/PacketHandler.cs
Intersect.Server/Intersect.Server.csproj
Intersect.Server/Maps/MapActionMessages.cs
Intersect.Server/Maps/MapAnimations.cs
Intersect.Server/Maps/MapEntityMovements.cs
Intersect.Server/Maps/MapInstance.cs
Intersect.Server/Networking/PacketSender.cs

Send entity movement, action message, and animation packets with each map update instead of in realtime (configurable).
This will reduce network and server load with minimal/no visual difference on the client end.

Batch movement, action message, and animation packets

---

Intersect.Client.Framework/File Management/GameContentManager.cs
Intersect.Client.Framework/Gwen/Control/Base.cs
Intersect.Client.Framework/Gwen/Control/Menu.cs
Intersect.Client/Interface/Game/Chat/Chatbox.cs

- [Bug Fix] When chatbox input text is set (for sending pms and such) the text input carot moves to the end of the line
- [Extension?] Gwen Menus can now be assigned names via a constructor parameter which will allow us to load uis for them via json files
- [Performance Fix] UI json files are cached in memory upon loading, so we reduce disk reads if we need to load them again (like we do for bank slots)

Small UI Tweaks

---

Intersect (Core)/GameObjects/LightBase.cs
Intersect.Client/Core/Graphics.cs
Intersect.Client/Entities/Entity.cs
Intersect.Client/Interface/Game/DebugMenu.cs
Intersect.Client/MonoGame/Graphics/MonoShader.cs

Few client sided performance tweaks to pump out a few more fps
- Fix excessive disk usage loading assets when sprites haven't changed
- Only set the interface count debug label when opening the window, because the linq query takes a lot of processing time
- Tweaks to shaders & lighting so we can batch lights with matching settings and improve rendering performance.

Client performance tweaks

---

Intersect.Client/Maps/MapInstance.cs

TODO: Make issue
Basically when you have an item on Tile 15, 15, and you over hover tile 15,15 on an adjacent map the item name will draw as if we are hovering over it. This small edit fixes that.

Fix item names drawing when hovering over the proper coordinates on ANY map

---

Intersect (Core)/GameObjects/Events/Condition.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.Designer.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.resx
Intersect.Editor/Intersect.Editor.csproj
Intersect.Editor/Localization/Strings.cs
Intersect.Server/Entities/Entity.cs
Intersect.Server/Entities/Events/Conditions.cs

Resolves #603
This time for Prerelease
- Removes an aribitrary limitation where Arena maps would hardcoded exclude PvP Kill and Death events from triggering, this decision should be left up the developer in question and handled through an event Condition.
- Added an Event Condition to check for Map Zone Type.

Remove Arena PvP event trigger limitations, add Condition to check for Zone Types

---

Intersect (Core)/GameObjects/ItemBase.cs
Intersect (Core)/GameObjects/NpcBase.cs
Intersect.Server/Entities/Entity.cs
Intersect.Server/Migrations/20201017065035_AddColorToEntities.cs
Intersect.Server/Migrations/Game/20201016122614_AddItemAndNpcColors.cs

This resolves migration issues adding color columns in Mysql environments -- #459

Make the engine not dependent upon default text values in the db

---

Intersect (Core)/GameObjects/ItemBase.cs
Intersect.Editor/Forms/Editors/frmItem.Designer.cs
Intersect.Editor/Forms/Editors/frmItem.cs
Intersect.Editor/Localization/Strings.cs
Intersect.Server/Database/GameData/GameContext.cs
Intersect.Server/Database/GameData/Migrations/BoundItemExtensionMigration.cs
Intersect.Server/Entities/BankInterface.cs
Intersect.Server/Entities/Entity.cs
Intersect.Server/Entities/Events/CommandProcessing.cs
Intersect.Server/Entities/Npc.cs
Intersect.Server/Entities/Player.cs
Intersect.Server/Entities/Projectile.cs
Intersect.Server/Entities/Resource.cs
Intersect.Server/Intersect.Server.csproj
Intersect.Server/Localization/Strings.cs
Intersect.Server/Maps/MapInstance.cs
Intersect.Server/Migrations/Game/20210512071349_BoundItemExtension.Designer.cs
Intersect.Server/Migrations/Game/20210512071349_BoundItemExtension.cs
Intersect.Server/Networking/PacketHandler.cs

Resolves #684 
Resolves #670
Added the following options to replace the singular Bound property on individual tems:
- CanDrop
- CanTrade
- CanSell
- CanBank
- CanBag
- Drop Chance on Death (%)
If an Item was bound prior to this update then a custom migration will make sure that **ALL** these options are disabled.
The global option for item Drop Chance on player death from the server configuration is no longer used globally, but rather as a default configuration value for new items (and existing non-bound items upon running the migration)
Also fixed a minor issue with a typo regarding item drop rates from players.

Make item binding options more granular

---

Intersect (Core)/GameObjects/ItemBase.cs
Intersect.Editor/Forms/Editors/frmItem.Designer.cs
Intersect.Editor/Forms/Editors/frmItem.cs
Intersect.Editor/Localization/Strings.cs
Intersect.Server/Entities/BankInterface.cs
Intersect.Server/Entities/Player.cs
Intersect.Server/Intersect.Server.csproj
Intersect.Server/Migrations/Game/20210513080440_AddItemStackCaps.Designer.cs
Intersect.Server/Migrations/Game/20210513080440_AddItemStackCaps.cs

Resolves #727 
Add configurable options to the item editor that allows the admin to set a limit as to how many items are allowed on a stack of an item in both the bank and inventory.
Had to rewrite a fair chunk of the bank logic for this, replaced it with the basis of the inventory logic since that seems to work fine.
Existing items will get a stack cap of the Int32 limit.
New items start with a default stack cap of 1.000.000

Add item stack caps

---

Intersect.Server/Database/DbInterface.cs

Fixes #734 by not crashing the server if multiple variables have the same textIds.

---

Intersect.Server/Entities/Entity.cs
Intersect.Server/Entities/Npc.cs

Fix fleeing npcs from running past their reset radius and instantly restoring health.

---

Intersect (Core)/Config/PartyOptions.cs
Intersect.Server/Entities/Player.cs

Its Resolves: #749
Percentage configured on the gain server.
Ex: 10 = 10%
Monster gives 1000 XP.
1 player, alone, without a party, will win 1000 by killing him.
2 players in a party, will kill this monster.
The Exp that will be divided will be +20%
Then, the monster will now divide 1200 XP, totaling a division of 600 XP for each member.
In short, for each additional member in a group you will gain + 10% xp on top of the xp to be divided for EVERYONE.
The particular EXP I cannot change because there is already a configuration in the items that can add XP individual bonus for each one.

Bonify XP Party for Each Member

---

Intersect.Server/Entities/Player.cs

Variable name didn't match with the updated name resulting in a reference error when compiling

Fixes compile error within #773

---

Intersect.Client/Interface/Game/Crafting/CraftingWindow.cs
Intersect.Client/Interface/Game/Crafting/RecipeItem.cs

Resolves #807 
Also uses the craft name in the crafting list instead of the item name.
In cases where the craft might make multiple quantities or something we give more control over the listing names to the developers.

Fix 807 by render crafting item and ingredient color hues

---

Intersect.Server/Entities/Player.cs
Intersect.Server/Networking/PacketHandler.cs

So #795 wasn't as simple as I had thought. When items failed to pick up, the overflow logic would take the map items and combine them into a new map item. And then the logic after the pickup code would fail to remove the original map item. Items would duplicate on the map and then you could clear up inventory space and get the unlimited items. This fixes all of that.
Should fully resolve #794

Fix 794 Cont: Fix item duplication angle when trying to pickup map items with a full inventory

---

Intersect.sln
targets/AscensionGameDev.Intersect.CommonVariables.targets

Intersect.Server.Framework.dll was being copied into the build directory when it should not have been
Add targets directory to the solution so it's easier to edit them in the IDE

fix: exclude isf binary from targets

---

Intersect (Core)/Config/CombatOptions.cs
Intersect (Core)/Config/Options.cs
Intersect.Server/Entities/Entity.cs

It is a very basic PR but it is linked to this issue https://github.com/AscensionGameDev/Intersect-Engine/issues/506, I have used the suggestions that they had written but without eliminating the default behavior.

Add option in server to enable regeneration vitals in combat

---

Intersect.Editor/Forms/Editors/frmCrafts.cs

Resolves #864 
UpdateEditor() was not updated with the change that introduced the craft common event.

FIX 864: Crafts Editor "Common Event" combobox now displays correct value when flipping between crafts in the editor

---

Intersect.Client/General/Globals.cs

Resolves #917 
So, turns out I never checked whether the things I'm trying to pull data from to push to plugins exist.
When the gamestate changes this causes some.. issues.

Check whether Entities and MapGrid actually exist before pulling data to send to plugins

---

Intersect.Client/Interface/Game/Bank/BankWindow.cs
Intersect.Client/Interface/Game/GameInterface.cs

Resolves #937
Stop (partially) destroying and fully recreating the bank window each use, was leaving orphaned Gwen objects around causing a memory leak.
We kept nulling this out but not disposing the actual window, so it was never removed (along with all of its children) from the Interface collections.. Oopsie. Though to be fair, why on earth are we endlessly recreating it anyway? Can just re-use it right. :)
I believe a similar issue may be happening elsewhere too, not sure?
Thanks Aesthethic for notifying me about this one. :)

Fix bank Interface memory leak

---

Intersect.Client/Interface/Game/Chat/Chatbox.cs
Intersect.Server/Networking/PacketHandler.cs

I believe that the chat log's warnings towards spammers are being checked in the wrong moment / place, this is the current behaviour with blank/empty messages, which in my opinion doesn't makes much sense if no message is being send at all:
(Simply press the "Return"/"Enter" Key repeatedly to toggle on and off the chatbox input)
https://user-images.githubusercontent.com/17498701/133119051-095f0b57-d3e4-4a0c-94b1-cfd544cfcb76.mp4
This PR fixes that client side behaviour, in adition with a server side check in the packet handler, to basically do the same (nothing) if the message content is empty/blank or null (just in case that someone decides to mess with the client in order to send spammy empty messages):
https://user-images.githubusercontent.com/17498701/133118893-74ad6e2b-0c75-48dd-9f10- …

[Fix]Chatbox (Blank|Empty)Msgs Behaviour with SpamCheck

---

Intersect.Editor/Forms/Editors/frmSpell.Designer.cs
Intersect.Editor/Forms/Editors/frmSpell.cs

Resolves #921 
Turns out the windows on the spell editor form were misaligned a bit.
Someone probably had good intentions somewhere but things were a bit.. messy.
Returned all the spell data types back to the same location, but because Event spells have both event and combat data groups up the combat data group will move down a bit to make space for it when selected.

Fix Spell editor windows being misaligned

---

Intersect.Editor/Forms/DockingElements/frmMapEditor.cs
Intersect.Editor/Forms/frmMain.cs

Resolves #843 
This was likely disabled unintentionally when the map layers became dynamically configured through the server configuration.

Restore Fill and Erase functionality for Attributes in the map editor

---

Intersect.Server/Entities/Entity.cs

Resolves #957 
Fix when trying to swap targets HP and MP and when target MPs defense transform MP damaging in MP healing.
Basically that baseDamage is setted by HP damage only. So when trying to swap targets HP into MP, the damagingAttack is **true** since **HP damage > 0** and **MP is < 0**, then MP is just setted to 0.
In another case, if the damage calculation brings an damaging MP attack below 0, the **damagingAttack is false** because there is no HP damage, so the **secondaryDamage is not setted to 0** turning an **MP damage in a MP healing**.

Fix at secondaryDamage

---

Intersect.Server/Entities/Entity.cs

Resolves #946
First of all, it's my first time creating this, any change I accept helps
In [1701](https://github.com/AscensionGameDev/Intersect-Engine/blob/d39d457c04c81323827d33ca0d74e3cdf2a7db1a/Intersect.Server/Entities/Entity.cs#L1701) a variable is created to store the original value of the baseDamage variable. Until [1731](https://github.com/AscensionGameDev/Intersect-Engine/blob/d39d457c04c81323827d33ca0d74e3cdf2a7db1a/Intersect.Server/Entities/Entity.cs#L1731) the value does not change what makes [1727](https://github.com/AscensionGameDev/Intersect-Engine/blob/d39d457c04c81323827d33ca0d74e3cdf2a7db1a/Intersect.Server/Entities/Entity.cs#L1727) meaningless (in my opinion, I may not understand the whole context). In addition, the verification made …

Fix #946 - Formula to be considered before verification of base damage

---

Intersect (Core)/Config/PartyOptions.cs
Intersect.Server/Networking/PacketHandler.cs

Resolves #962 
Removes the invite range setting from parties, it's honestly counterintuitive and makes grouping up tedious.
This genuinely doesn't fit in a modern game, and I even find it baffling for older games.
(Also counterintuitive with the changes in #959 and #964 since that allows invites by name, not proximity)

Remove InviteRange from Parties

---

Intersect.Server/Entities/Player.cs

The "Abandoned" and "Complete" colours (quests) aren't properly linked, this PR should resolve #1004

Fix for unused colours within the quest messages.

---

Intersect.Server/Core/LogicService.LogicThread.cs

MapUpdateQueue was updating the map within the ActiveMaps check, while **inside the enabled check for metrics only**.
By moving this check for active maps along with MapUpdateQueue, **out of this previously mentioned check** for enabled metrics, we can now still enjoy metrics doing it's job properly (to work or not) whenever it's enabled or disabled, _without interrupting the gameplay map updates_. 
Should resolve #855

Fixes map updates when metrics is false. (#855)

---

Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.cs

Resolves #874 
Forgot to add a specifier as to which variable type we had to retrieve the Id for.

Use correct variable Id for HasFreeInventorySlots condition

---

Intersect.Client/Interface/Shared/SettingsWindow.cs

The issue was triggered by a mistake i previously made with the Settings Revamp commit (#950): 
If we navigated to the Settings Window, applied changes or navigated back to the main menu and then we decided to log-in in order to see the character select screen, the Main Menu Window would show up behind the character select window.
(Test purposes) Made the character select windows transparent to see what the heck was behind:
The previously explained behavior should be corrected with the commit from this pull request.
(Test purposes) with transparent character select window

Fix: Hides the Main Menu Window while in the character select screen.

---

Intersect.Client.Framework/Gwen/Control/Base.cs
Intersect.Client.Framework/Gwen/Control/Canvas.cs

Resolves #1031 
This is me attempting to implement a fix for my theory as to why UI sounds get cutoff prematurely (see linked issue for details). I _haven't_ seen anything like memory leaks or weird issues/crashes come from this change, and while debugging I did see that sound instances I was creating through the UI were being disposed of in some fashion.

[GWEN] FIX #1031: Control Base now keeps track of sound instance it plays

---

Intersect.Client/Entities/Entity.cs

* Should resolve #1095 
* Applied Lathander's idea to prevent the 'wobbly' (trembling looking) effect of the targetbox texture when entities move.
* Removed redundant casts within the 'DrawTarget' method.
* Moved the declaration 'srcRectangle' closer to it's usage.
* Converted to float values the fraction operations for targetTex's Width and Height in order to prevent possible loss of fraction.
PS: Thanks to [Lathander](https://www.ascensiongamedev.com/profile/5651-lathander/) for pointing this out!

Chore: fixes 'wobbly' targetbox texture when entities move

---

Intersect (Core)/Configuration/ClientConfiguration.cs
Intersect (Core)/Enums/DisplayModes.cs
Intersect (Core)/Intersect (Core).csproj
Intersect.Client/Core/Graphics.cs

**Preview of Animated Background (DisplayMode: Stretch)**
https://user-images.githubusercontent.com/17498701/149450094-8ee3c759-cba1-4d5a-aee6-b7149f977f93.mp4
This Pull Request should resolve #815
**11-01-2022 ~ 12-01-2022**
* Adds the ability to to stretch the main menu's static background to the game client's window size though a new boolean property at Client's Config.json.
* Adds the ability to set an animated background in the main menu. Frames and their speed (Milliseconds) are configurable though new properties at Client's Config.json.
* Created the method "DrawFullScreenAnimatedTextureStretched", which draws a full screen animation as background, stretching it's size to the game client's window size.
* Created the method "DrawFullScreenAnimatedTexture", which draws a full screen …

[MainMenu] Adds Animated Background & DisplayMode Settings.

---

Intersect (Core)/Compression/AssetPacker.cs
Intersect.Editor/Forms/frmMain.cs
Intersect.Editor/Forms/frmOptions.Designer.cs
Intersect.Editor/Forms/frmOptions.cs
Intersect.Editor/Localization/Strings.cs

Probably seems like the most pointless thing ever, but batching these by file count rather than size was always a bit of a silly oversight of mine.
Unlucky scenarios could cache like 50MB inside a single file, which takes.. a while to load.
This should let the user set an upper limit for pack file sizes.
Of course, trying to package files above the limit won't make the files magically smaller, it'll just put these in its own packs.

Modify Asset Packing to pack by file size per batch rather than file count

---

Intersect.Client.Framework/Gwen/Control/ComboBox.cs

* Removes default hardcoded values of ComboBox sound effects.
* Resolves #1097 
Explanation: ComboBox sound effects shouldn't be overwritten by default hardcoded values, they should consider the user's input from the Json files, it doesn't matter if the value is null or the established sound effect doesn't exists since this isn't an issue for Gwen.

Fix: removes hardcoded ComboBox sound effects

---

Intersect.Client.Framework/Database/GameDatabase.cs
Intersect.Client/Core/Graphics.cs
Intersect.Client/Entities/Player.cs
Intersect.Client/Interface/Shared/SettingsWindow.cs
Intersect.Client/Localization/Strings.cs

* This pull request pretends to continue with the implementation 
of few game settings that were previously mentioned in #936 
* This pull request should resolve #740 
* For testing, you will need to be up to date with the dev branch and the latest resources
added to the development asset repo: #950 
* Adds 6 new Game Settings that allows users to toggle the visibility of entities overhead information (such as Names, Labels, Guild Name, etc.)
* Whenever any of the 6 new settings is toggled off, the overhead information may still be viewed by hovering the cursor over the hidden cases.
* The new overhead information settings include the following: Friends, Guild, Myself, NPCs, Party, Players.
* Prevented double drawing of the overhead information, whenever Friends are Guildies at the same …

[Adds Game Settings] Overhead Information.

---

Intersect.Client.Framework/Gwen/Control/Menu.cs

Resolves #960 
This ensures menu items open within the canvas and stops them from growing in size for all eternity when you keep opening them.

Position Menu items inside the canvas on Open()

---

Intersect (Core)/Enums/SpellCastFailureReason.cs
Intersect (Core)/Intersect (Core).csproj
Intersect.Server/Entities/Entity.cs
Intersect.Server/Entities/Npc.cs
Intersect.Server/Entities/Player.cs
Intersect.Server/Localization/Strings.cs

Resolves #972  #940 
No idea why the spell system in general is in as sore a state as it is right now, but I figured I'd start cleaning SOMEWHERE.
Entities, Npcs and Players each had their own ways of checking the same things.
This really shouldn't be the case, generic checks should be done on the Entity class and Npc and Player specific checks on their respective classes.
I've tried to reduce it down to something resembling some form of coherence, got rid of the out of place checks on Npc and Player classes and replaced them with inherited methods, an override and some semblance of logic.
Also made sure all entities have to pass the same basic checks before allowing them to cast spells, Entities other than  players were allowed to bypass certain checks entirely.
Also fixes the following …

Chore: clean up CanCastSpell on Entity and Player.

---

Intersect.Editor/Forms/Editors/frmNpc.cs
Intersect.Server/Entities/Npc.cs

Resolves #844 
The input accepts values the pathfinder class does not, so going to have to limit that to what the pathfinder can accept.

Don't allow a reset radius to be set over the maximum value the pathfinder accepts.

---

Intersect.Server/Admin/Actions/ActionProcessing.cs
Intersect.Server/Core/Commands/UnbanCommand.cs
Intersect.Server/Core/Commands/UnmuteCommand.cs
Intersect.Server/Database/Logging/Entities/UserActivityHistory.cs
Intersect.Server/Database/PlayerData/Security/UserRights.cs
Intersect.Server/Localization/Strings.cs
Intersect.Server/Networking/PacketHandler.cs
Intersect.Server/Web/RestApi/Routes/V1/PlayerController.cs
Intersect.Server/Web/RestApi/Routes/V1/UserController.cs

* Applied panda's [partial re-implementation](https://github.com/AscensionGameDev/Intersect-Engine/commit/04673626e0d0324733ead22d2607dd09a08970fa) (with somes changes).
* Removed unreachable code from the UserActivityHistory (??' left operand is never null, so we don't need Guid.Empty).
* From now on, bans are always announced globally.
* From now on, mutes are always announced globally.
* Adds ability to Ban/Unban & Mute/Unmute **even** if the target is Offline.
* Adds ability to Unban/Unmute in game by using the target's **player name**. 
(Unban/Unmute doesn't requires you to know the username of the player anymore.)
* Added feedback messages for whenever we try to Unban/Unmute a player that's not Banned/Muted.
* Improved feedback messages by adding colours to their font.
( …

Admin Actions: Improves Feedback and Authority checks

---

README.md

The link to docs.ascensiongamedev.com does not seem to work. But https://docs.freemmorpgmaker.com works.
Maybe also needed on main branch?

chore: fix documentation link

---

Directory.build.props
Intersect.props

This is an attempt to avoid the annoying duplicate assembly attribute issues

fix: go back to using the default output paths

---

Intersect.Tests/IO/Files/FileSystemHelperTests.cs

Fixes FileSystemHelper test cases by adding a '\' or '/ 'to the from-directory.
Resolves  #1140

Fix FileSystemHelper Tests

---

Intersect.Server/Core/LogicService.LogicThread.cs
Intersect.Server/Entities/Entity.cs
Intersect.Server/Entities/Npc.cs
Intersect.Server/Maps/MapInstance.cs

Resolves #988 
This should stop Npcs from hugging corners, entrances, walls etc. when a player joins a map somebody managed to lure all Npcs into one corner for.
When a reset radius is allowed and configured, the Npc will simply reset to the location it was pulled from, assuming it has one.
When no reset radius is configured or allowed.. things get a little trickier and we check if the Npc is in combat or not, if it is we forcibly kill it dropping no items and respawn it in its designated spawn location or randomly.

Forcibly reset Npcs on a map once we stop processing it

---

Intersect (Core)/CustomColors.cs
Intersect.Client/Entities/ChatBubble.cs

* Should resolve #1007 
* Transparent by default, in order to keep the original graphic concept of intersect's chat bubbles.
* Users are now able to set any specific colour to render as the text's outline inside chat bubbles by following the ARGB format.
**Example**
( rebuild core, client and server when testing )

Adds configurable custom colour for chat bubble text's outline.

---

Intersect.Client/Localization/Strings.cs

Resolves #1167 
No the cleanest solution ever, but at least the behaviour will be consistent with this change.

Remove inconsistent checks and conversions for lowercase keys in Client Strings

---

Intersect.Server/Core/LogicService.LogicThread.cs

* The commit 33de35cd4cf45e2aca60624580bd42852f2d15c1 re-added the old "ActiveMaps" check, which is no longer used in the dev branch and prevents the solution to compile due to unresolvable declared symbols.
* Since the addition of instances, we've been checking this up with ActiveMapInstances at LogicService.LogicThread.cs (L:371)

fix: removes unnecessary check in LogicService.LogicThread.cs

---

Intersect.Client/Interface/Shared/SettingsWindow.cs
Intersect.Client/Localization/Strings.cs

* [As previously discussed](https://github.com/AscensionGameDev/Intersect-Engine/pull/968#issuecomment-948507217): 
Moves the Auto-close Windows checkbox into a new 'Interface' sub-category within the Game Settings.
* [Assets PR related to this](https://github.com/AscensionGameDev/Intersect-Assets/pull/15)

chore: Moves 'Auto-close Windows' to Game Settings

---

Intersect.Client.Framework/Content/ContentWatcher.cs

RemoveAll occasionally hits a OOBE caused by a race condition, hopefully removing one-by-one avoids that

fix: avoid RemoveAll

---

Intersect.Server/Database/PlayerData/Players/Guild.cs

Fixes #1226 - we _migrated_ guilds to have newly-generated guild instance IDs, but I didn't make any changes to the guild create method. Whoops.

FIX-1226: Fixes issue with guild instance warps

---

Intersect (Core)/GameObjects/Events/Condition.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.Designer.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.cs
Intersect.Editor/Localization/Strings.cs
Intersect.Server/Entities/Events/Conditions.cs

Resolves #1240 
Extends the existing "No NPCs on Map" conditional by now allowing the user to check for if there are no NPCs of a _specific_ type, further expanding usability and event options.
This also fixes a small editor UI bug where the new `CheckEquippedSlot` condition didn't hide properly.
UI looks like this:
*With a specified NPC enabled*
*With a specified NPC disabled*
*Command printer text*
*Command printer text when no NPC specified*
https://user-images.githubusercontent.com/8580915/166123544-5603b2d4-5266-4720-93d7-f82082392b31.mp4
*In this video, you can see the "Nope" text when a "Some Scrub" appears on the map, followed by a "Nope!" When they leave the map (top-right).*

feat: New options for condition: NoNpcsOnMap

---

Intersect (Core)/CustomColors.cs
Intersect.Client.Framework/Gwen/Control/ListBox.cs
Intersect.Client/Interface/Game/Crafting/CraftingWindow.cs
Intersect.Client/Interface/Game/QuestsWindow.cs
Intersect.Server/Entities/Player.cs

Fix #1246 
To give more customization to the text colors of the crafting and quest windows that are hardcoded.

Fix Crafting and QuestWindow Colors

---

Intersect (Core)/GameObjects/Maps/MapAttribute.cs
Intersect.Editor/Forms/DockingElements/frmMapLayers.Designer.cs
Intersect.Editor/Forms/DockingElements/frmMapLayers.cs
Intersect.Editor/Localization/Strings.cs
Intersect.Server/Entities/Player.cs

Adds the ability to play a sound effect when warping a player via map attribute.
The attribute editor will look like this when "Warp" is selected:

resolve: (Day) Add sound effect selection to warp attribute

---

Intersect.Editor/Forms/DockingElements/frmMapLayers.cs

* When editing NPCs with declared spawns, the editor's map preview will not update the spawn locations if one of those spawns is deleted, this commit should fix that behaviour by updating the editor's map preview whenever we delete an specific NPC from the map's spawn list.
* Should fix #1054
Preview:
https://user-images.githubusercontent.com/17498701/171522743-f0fe906a-e3b8-4fef-a212-ea6cef62a1c6.mp4

[EDITOR] Updates Tile Preview On NPC Removal

---

Intersect.Editor/Content/ContentManager.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ShowPicture.cs

[ShowPicture EventCommand] Fix for Empty Directory
* Avoids reaching a run-time exception within the ShowPicture event Command window when the image directory is empty by filling up the combo box list with an empty string instead of null.
* Made sure to properly check for null mMyCommand variable before making use of it.
* cmbPicture.SelectedIndex & cmbSize.SelectedIndex have been properly checked and converted to '?:' operators.
* Should Resolve #1261
[ Panda's Review I ]
* Saved the result of GetTextureNames(type) to a local variable to prevent calling it twice.
[ Panda's Review II ]
* Changed the SelectedIndex of cmbPicture and cmbSize for Math.Max that returns the 
parameter val1 or val2 (whichever is larger). 
* This will maintain consistency and will not corrupt the state of the …

[EDITOR] Fix for Empty Directory with ShowPicture events

---

Intersect.Client/Entities/Player.cs

* Sets the proper maximum amount for the bank's input slider box when giving/taking stackable items.
* Should Fix #1286
Fix preview:
https://user-images.githubusercontent.com/17498701/174117354-29644856-2207-4566-9fa3-e95f1733e1e0.mp4

Fix: Sets the proper maximum amount for the bank's input slider box

---

Intersect.Client/Interface/Game/Spells/SpellItem.cs
Intersect.Server/Networking/PacketHandler.cs

* This workaround prevents taking advantage of the cast timing exploit when swapping spells within the spell window by disallowing the ability to swap them while casting. -> Should fix #1069
* A client-side and server-side check has been added (even if the client is modified with malicious intents, the server will still prevent the exploit from happening).
A note to Developers, Collaboratos and Maintainers: This should be considered a workaround for now, despite the fact that it *does prevents the exploit from happening thus, resolves the issue for now*, the root of the problem lies in the way the spells are currently implemented, so eventually it will be necessary to open another issue report and PR that aims to re-engineer the implementation from the ground up.
Preview: …

Disallows spell swap while casting

---

Intersect.Editor/Content/ContentManager.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ChangeFace.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ChangeSprite.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_Options.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ShowPicture.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_Text.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/Event_GraphicSelector.cs

* Undid unnecesary changes i commited to GetSmartSortedTextureNames (#1274), which triggered the issues reported in #1299
* Simplified some comboboxes selected indexes with Math.Max
* Allows to remove entities Face though EventCommand (added 'none'). Also prevents crash if the faces folder is empty.
* Allows to remove entities Sprite though EventCommand (added 'none'). Also prevents crash if the entities folder is empty.
* Prevents crash from ShowPicture EventCommand by adding 'none' to the combobox only if the images folder is empty.
* Prevents crash from event's sprite graphic selector by adding 'none' to the combobox only if the entities folder is empty.
* Prevents crash from event's tileset graphic selector by adding 'none' to the combobox only if the tilesets folder is empty.

Chore & Fix: some editor's comboboxes & 1299

---

Intersect (Core)/Config/NpcOptions.cs
Intersect.Server/Entities/Npc.cs

fix: (Day) Prevent NPCs from despawning when their reset positions are blocked.

---

Intersect.Editor/Forms/DockingElements/frmMapEditor.cs
Intersect.Editor/Forms/frmMain.cs

Should resolve #913 by adding the following shortcuts to the map grid editor within the intersect engine editor:
- Pen Tool => P
- Marquee Selection Tool => M
- Rectangle Tool => R
- Vertical Flip Selection Tool => PageUp
- Horizontal Flip Selection Tool => PageDown
- Fill Tool => F
- Erase Tool => E
- Eyedropper Tool => I
- Delete Selection => Delete
**Video-Demo:**
[![Demo Video of this PR](https://user-images.githubusercontent.com/17498701/178855851-2a7d4aec-910b-48e7-a927-28e2fbb07b65.png)](https://www.ascensiongamedev.com/resources/filehost/2d665bcc18ee7557e6de9a9bd3a64a97.mp4 "Demo Video of this PR - Click to Watch!")

QoL Enhancement: MapGrid Editor Tool-Shortcuts

---

Intersect.Client/Entities/Entity.cs
Intersect.Client/Entities/Events/Event.cs

Resolves #1372
If the event does not have animations, the label is positioned in the middle of the event's tile like before
To resolve the bug, if the event _does_ have animations, the label is positioned as though the event is a 1 tile tall tileset event, and the animation is centered accordingly:

chore: none 1x1 tile if animations present

---

Intersect.Client.Framework/Database/GameDatabase.cs
Intersect.Client/Core/Controls/ControlMap.cs
Intersect.Client/Core/Controls/ControlValue.cs
Intersect.Client/Core/Controls/Controls.cs
Intersect.Client/Interface/Game/Chat/Chatbox.cs
Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs
Intersect.Client/Interface/Shared/SettingsWindow.cs
Intersect.Client/Localization/Strings.cs
Intersect.Client/MonoGame/Database/MonoDatabase.cs

Resolves #1266 
- bindings are now dynamically sized (in case we ever want to increase past 2 in the future)
- this also allows for all of the code to be reused between keys
- bindings are checked independently to allow for mouse binds to not interfere with key binds (which caused #1266 )

fix: rework bindings to be dynamic and independent

---

Intersect.Client/Entities/Player.cs
Intersect.Client/Maps/MapInstance.cs

Minor chore changes to prevent drawing the following while having the cursor over GUI elements:
- Entities Target-box.
- Entities Overhead Information (when hidden).
- Dropped Item Labels.
**Before this chore PR:**
https://user-images.githubusercontent.com/17498701/179374839-b02880e4-05ec-49e1-a49b-db2297a3623b.mp4
**After this chore PR:**
https://user-images.githubusercontent.com/17498701/179374847-4e47e038-7040-4317-812a-03b672d85aac.mp4

Chore: Entities Target-box, Overhead Info, and Item Labels

---

Intersect.Client/Interface/Game/Trades/TradingWindow.cs

* should resolve #1395 
* displays item quantities within the trade windows by using the client's Strings#FormatQuantityAbbreviated method
* inverted item != null and reformatted the changed lines of code

fix 1395: Strings#FormatQuantityAbbreviated on trade window

---

Intersect.Client.Framework/Gwen/Control/Layout/TableRow.cs

Should resolve #1207 by adding the boolean parameter 'enableMouseInput' as false by default into the SetCellText method in order to disable the MouseInput within cell's text, which now allows to properly hover/click their parent buttons/elements.
https://user-images.githubusercontent.com/17498701/186951416-a377a016-40e2-4c4d-b58d-a8beb58d4c2c.mp4

fix 1207: properly sets MouseInput on CellText

---

Intersect.Client/Entities/Events/Event.cs

Basically the EventGraphic object does not change the event sprite according to the Filename property.
Worked for both Sprite/Tileset.
This pull request fix the issue  #1308

Fix updating the event graphic resolving issue #1308

---

Intersect.Client/Interface/Game/Character/CharacterWindow.cs
Intersect.Client/Localization/Strings.cs

https://user-images.githubusercontent.com/63019821/185793460-f1b9e361-466e-4b71-83aa-1d940932cc5d.mp4
You will need these resources:
[extra-status.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/9389187/extra-status.zip)

Extra Buffs in Character Window

---

Intersect.Client/Localization/Strings.cs
Intersect.Editor/Localization/Strings.cs

- add extra log info
- log don't throw on unsupported type

fix: some editor string dictionaries were incorrectly typed

---

Intersect.Client.Framework/Database/GameDatabase.cs
Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
Intersect.Client/Interface/Shared/SettingsWindow.cs
Intersect.Client/Localization/Strings.cs

- chore: some things were reorganized around the modified code.
- new feat: ability to show UI Bar values as percentage.
- If enabled, will display the toggled bar's as percentage and it's tooltip will show the actual value instead.
- If disabled, will display the toggled bar's actual value and it's tooltip will show the percentage instead.
- should resolve #1431 
**Assets PR :** https://github.com/AscensionGameDev/Intersect-Assets/pull/22
https://user-images.githubusercontent.com/17498701/189506575-57de6696-52cf-4656-be1c-4428e3d7e366.mp4

feat: ability to show UI Bar values as percentage

---

Intersect.Client/Core/Controls/Controls.cs

Fix is to not blindly delete preferences if they might not exist, there's already logic to check if they exist, move the deletion within those checks.

fix: remove log spam on control migration

---

Intersect.Server/General/Time.cs

If a user logs in extremely quickly (before the server has begun ticking) the time range value is still -1 which is out of range and **this causes an unexplained black screen with no client errors on login** -- changing it to 0 instead which is in-bounds and shouldn't cause issues (since SendTimeToAll() wouldn't be called if it was changing to zero or there are no players online).

fix: prevent time crash if user logs in too quickly after server start

---

Intersect (Core)/Configuration/ClientConfiguration.cs
Intersect (Core)/Enums/DisplayDirection.cs
Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs

Resolves #1164
Adds two client options to choose the direction from which vitals and experience bars are filled and emptied.
This opens up a wide range of possibilities by allowing for a better customization of vitals/exp bars.
https://user-images.githubusercontent.com/63019821/185804094-155b3e0b-4198-4853-b602-3a9fbc3e97d6.mp4

feat: client options for vitals and exp bar's direction

---

Intersect.Client.Framework/Database/GameDatabase.cs
Intersect.Client/Interface/Shared/SettingsWindow.cs
Intersect.Client/Localization/Strings.cs

* tweaks game settings, allowing for a modular and easier to organize sub-categories within a listbox.
* exposes `stickytarget` and restores it's default value back to false, which allows to un-target by clicking anywhere and/or the target. [this feat was reported to be working prior b7.](https://www.ascensiongamedev.com/topic/6533-cant-un-select-a-target-self-or-other-player/)
[assets pull request](https://github.com/AscensionGameDev/Intersect-Assets/pull/23)
**Preview:**
https://user-images.githubusercontent.com/17498701/190838566-374c4872-6d1c-4a63-bf3a-55abdbb8044b.mp4

chore: tweaks game settings and exposes `stickytarget`

---

Intersect.Server/Maps/MapInstance.cs

The shield information is not updated constantly when the user uses the shield spell effect. It is necessary to keep recasting the spell constantly to know how much shield is left.
I don't know if this solution is the best (there must be other ways), but with this the problem is solved, I'm sending pr for better analysis by professionals

Update shield info

---

Intersect (Core)/Config/Options.cs
Intersect (Core)/Config/PlayerOptions.cs
Intersect.Client.Framework/Database/GameDatabase.cs
Intersect.Client/Entities/Entity.cs
Intersect.Client/Entities/Player.cs
Intersect.Client/Interface/Shared/SettingsWindow.cs
Intersect.Client/Localization/Strings.cs

* Implements a new targeting game setting that allows players to auto-turn to the selected target when enabled.
* Player will auto-turn to their currently selected target (by clicking on them or switching targets) only when not moving and if the direction needs to be changed from the current one.
* The feature can be toggled by the server config as well. When disabled, it will make it so the feature no longer works for the client and the checkbox within the game settings is disabled and unchecked.
* Minor chore at DrawTargets() : reduced nesting by merging and inverting if(s) and used conditional en.Value != null within the foreach loops required for this feature.
* Special thanks to Daywalkr (Middle Ages: Online), took (and changed a bit) the implementation from his repository.
* Should …

feat: auto-turn to selected target

---

Intersect.Client/Core/Controls/ControlEnum.cs
Intersect.Client/Core/Controls/Controls.cs
Intersect.Client/Entities/Player.cs
Intersect.Client/Localization/Strings.cs

* If players holds the 'TurnAround' Control Key and **tap to any direction**, they will turn on their own axis.
* Added configurable control key (default: Keys.Control)
* This feature doesn't messes with the normal processing nor timing of walking.
* Should resolve #987
* Should resolve #1529
* For testing, [Assets PR Here.](https://github.com/AscensionGameDev/Intersect-Assets/pull/26)
https://user-images.githubusercontent.com/17498701/194784430-93e24eab-d4c0-45c0-9be6-b078e534d93e.mp4

feat: configurable key to hold and turn around

---

Intersect (Core)/Config/InstancingOptions.cs

* The server's InstancingOptions properties couldn't be set through their .json files, this commit fixes this behavior by allowing the user to input values other than the default ones. (resolves #1656 )
* chore: removes unused property "RegenManaOnInstanceDeath" since is not really implemented (yet?).

fix: ability to set InstancingOptions properties

---

Intersect.Client/Interface/Game/Bag/BagWindow.cs
Intersect.Client/Interface/Game/Bank/BankWindow.cs
Intersect.Client/Interface/Game/GuildWindow.cs
Intersect.Client/Interface/Game/Inventory/InventoryWindow.cs
Intersect.Client/Interface/Game/Shop/ShopWindow.cs
Intersect.Client/Interface/Game/Spells/SpellsWindow.cs
Intersect.Client/Interface/Game/Trades/TradingWindow.cs

* Fixes an unwanted behavior (bug) where context menus would remain opened upon closing the window from where they were initially prompted (by closing them along with their parent window).
* Should resolve #1651

fix: close context menu when closing window

---

Intersect.Client/Interface/Game/Bag/BagWindow.cs
Intersect.Client/Interface/Game/Bank/BankWindow.cs
Intersect.Client/Interface/Game/GuildWindow.cs
Intersect.Client/Interface/Game/Inventory/InventoryWindow.cs
Intersect.Client/Interface/Game/Shop/ShopWindow.cs
Intersect.Client/Interface/Game/Spells/SpellsWindow.cs
Intersect.Client/Interface/Game/Trades/TradingWindow.cs

* Also checks for other use cases after null context menus before continuing.
* Should resolve #1664

fix: NullReferenceException when closing context menus

---

Intersect (Core)/Config/PlayerOptions.cs
Intersect.Server/Networking/PacketHandler.cs

* A configurable alternative to resolve #1666 
* Adds the ability to configure whether or not the game client skips the character select window upon login or going back to characters when the max number of characters allowed per account is one.
* QoL change: By logic, newly created accounts have 0 characters on them, so the code logic behind this has been changed to skip the character select window upon creating a new account by directly going thru the character creation window instead.
* QoL change: Already created accounts with 0 characters will directly go thru the character creation window now.

enhancement: configurable character select skip

---

Intersect.Client/Entities/Entity.cs

should resolve #1649
Spell has a duration of 36 seconds and transforms into Male_003, previously and as reported, the base cast sprite would incorrectly show up when casting while transformed, but as you may see in the following video, this has been corrected to show the transformed casting sprite when casting while transformed:
https://user-images.githubusercontent.com/17498701/205513203-9fa947f9-5bc9-4e62-88a7-01e96bfc3c96.mp4

fix: transformed casting sprite behavior

---

Intersect.Client/Interface/Game/Character/CharacterWindow.cs
Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
Intersect.Editor/Forms/Editors/Events/CommandPrinter.cs

* fixes an unwanted behavior within the character window where the player's equipped gear wasn't properly drawn with their corresponding color values.
* chore: simplified some gender checks by converting them into '?:' expressions.
* should resolve #1677

fix: equipment color in character window

---

Intersect.Client/Maps/MapInstance.cs
Intersect.Editor/Core/Graphics.cs

* Should resolve #1652 
* Chore: refactors client's `DrawFog` method in order to improve: performance, readability and stability.
* Fix: Solves an issue where the value of `elapsedTime` could potentially be very large if there is a significant delay between calls to the `DrawFog` method. This could cause the `mCurFogIntensity` to increase or decrease at an unexpectedly fast rate, which could cause the fog to appear and disappear abruptly or delayed.
* Removed the unnecessary check for `mCurFogIntensity` being less than 1 in the first conditional block.
* Used Math.Min and Math.Max instead of the if statements to clamp the values of `mCurFogIntensity`
* In order to handle cases where the fog texture's position goes out of bounds: converted `mFogCurrentX`/`mFogCurrentY` to compound …

fix: fog timing, intensity and consistency

---

Intersect.Client.Framework/Database/GameDatabase.cs
Intersect.Client/Entities/Entity.cs
Intersect.Client/Entities/Player.cs
Intersect.Client/Interface/Shared/SettingsWindow.cs
Intersect.Client/Localization/Strings.cs

* Adds feature: visibility settings for entity overhead hp bars.
* When toggled off (default) : 
original behaviour (damaged entity) will show up hp bars on entities ;
along with the ability to see their hp bars by hovering the cursor on them.
* When toggled on, the selected type of entity will always show up their hp bars in the game view.
* Adds player-exclusive override for the boolean ShouldDrawHpBar.
* Fixes a crash due to null player being parsed over to the player boolean IsInMyParty.
* Fixed a couple of localized string and comment typos.
* Should resolve #969
[**Assets for this pull request**](https://github.com/AscensionGameDev/Intersect-Assets/pull/28)

feat: overhead hp bar settings

---

Intersect.Client.Framework/Gwen/Control/Base.cs
Intersect.Client/Interface/Game/Bank/BankWindow.cs
Intersect.Client/MonoGame/Graphics/MonoRenderer.cs
Intersect.Client/MonoGame/IntersectGame.cs

* Adds comments and reorganizes the BankWindow class (Close() should be placed by the end of initialization).
* Improves the performance and readability of Gwen's Position method.
* Replaces a Pointf struct with separate float variables and uses ref variables within the Rotate method of the DrawTexture class to improve performance and save memory.
* Simplified the LoadFont method within the MonoRenderer class.
* Uses a for loop that iterates through children in reverse order and removes unnecessary variables within the GetControlAt and DoCacheRender methods of the Graphics and Gwen classes to improve performance.

chore: performance and memory

---

Intersect.Client.Framework/Gwen/Skin/TexturedBase.cs

* Fixes an issue where list box elements that are selected and hovered, are drawn with the selected texture instead of the hovered texture.
* Realigned listbox rows.
* Fixes glitchy and misaligned even rows.
* Should resolve #1648
* [Reworked assets with better looking listbox rows](https://github.com/AscensionGameDev/Intersect-Assets/pull/35)
https://user-images.githubusercontent.com/17498701/211175865-f10e6a99-f4bf-4e28-a716-4310eee43fdb.mp4

fix: glitched even rows and hovered rows within listboxes

---

Intersect (Core)/Configuration/ClientConfiguration.cs
Intersect.Client.Framework/Gwen/Control/Layout/Table.cs

Adds a client config to set whether the highlighted even rows of list elements should be marked differently or not.

chore: configurable listbox even rows

---

Intersect.Client/Interface/Game/Crafting/CraftingWindow.cs

Should resolve #1728 
Before (bug)
After (this PR)

fix: crafting window ingredients list

---

Intersect (Core)/Config/SpriteOptions.cs
Intersect.Client/Core/Input.cs
Intersect.Client/Entities/Entity.cs
Intersect.Client/Entities/Player.cs
Intersect.Server/Entities/Entity.cs
Intersect.Server/Entities/Npc.cs
Intersect.Server/Networking/PacketHandler.cs

* fix: normal sprite no longer overrides the attack sprites, it has it's own method now.
* fix: idle state wont mess around with casting nor blocking anymore.
* chore: less duplicated code at Entity.Draw and Entity.DrawEquipment, for which we now use the single int class "NormalSpriteAnimationFrame".
* The class "NormalSpriteAnimationFrame" handles the normal sheet attack, block and cast frames, which are now configurable by their own sprite option properties ! (NormalAttackFrame, NormalBlockFrame, NormalCastFrame).
* enhancement: prevents showing frames out of index, aka "invisible frames issue" for normal attack, block and cast frames in case of wrong config input (frame > amount of frames within the normal sheet). #1655
* shield improvements: no more frame randomness, blocking uses …

enhancements and fixes: attack, block and cast animations

---

Intersect.Client/Entities/Entity.cs

- Adjusts PaperdollOrder to ensure it is correctly synchronized with the last cardinal direction.
- Should resolve #1752 
> Previously, the frame row value was mistakenly being used instead of the direction value. To fix this, the PaperdollOrder has been adjusted to sync with the last cardinal direction, and the default direction during initialization is now set to down in order to match the directions from the beginning. These changes ensure that the PaperdollOrder is properly synchronized with movement directions.

fix: sync entity PaperdollOrder with last direction

---

Intersect.Client/Entities/Entity.cs

We don't really need a cached variable with Math.Max here, mLastDirection equals to either Direction.Down upon initialization or the last cardinal direction while moving in game, so it's never a null nor a negative value.

chore: paperdollDir

---

Intersect.Client/Entities/Player.cs

- fixes an issue where auto-turn to target made the player turn over to the right whenever they target themselves.
- should resolve #1754 
https://user-images.githubusercontent.com/17498701/223774184-0aa71dde-174e-4478-adaf-486c11096eb9.mp4

fix: don't auto-turn when self targeting

---

Intersect.Client/Entities/Entity.cs
Intersect.Client/Entities/Player.cs

- improves the logic to pick the last direction with the PickLastDirection method.
- adds PickLastDirection into TurnAround function in order to make sure that the last direction is updated when turning around in place.
- this should also resolve an issue with wrong last direction value being used to set the paperdoll rendering under certain scenarios like:
- (ie) walking from down-left to up-left (opposites).
- hold key to turn around and walk to opposite direction.
- should resolve #1758

fix: last direction for paperdoll order

---

Intersect.Client/Entities/Player.cs

- Adds PickLastDirection into AutoTurnToTarget function in order to ensure that the last direction is updated when players are auto-turning towards targets.
- Should resolve #1770 
https://user-images.githubusercontent.com/17498701/226206541-8458906b-2dbd-46ae-8947-9e5d9b758815.mp4

fix: pick last direction when auto-turning to target

---

.github/workflows/build.0.7.2-beta.yml
.github/workflows/pull_request.yml

- split PRs into separate workflow file so that PRs do not accidentally trigger releases
- limit push workflow to look for changes that are outside of the .github directory

fix: use separate workflow for PRs, limit build workflow file triggers

---

Intersect.Client/Interface/Game/Inventory/InventoryWindow.cs
Intersect.Client/Localization/Strings.cs

Should resolve #1803 which reports an issue within InventoryWindow.cs and it's context menu: "learn x spell" was hardcoded as string for context menu options of spell items without making the distinction between cast-able spells and learnable spells. This commit changes the method so it makes the distinction in place in order to have the expected behavior.

fix: swap between "cast" and "learn" spell option

---

Intersect.Client/Entities/Player.cs

- Adds a missing update for paperdoll direction order by calling PickLastDirection when players attempt to move but they are unable to and/or collide into blocked paths.
- Should resolve #1799
https://user-images.githubusercontent.com/17498701/235956869-8c395e6c-50a7-4434-8b18-6d6640ca6b2a.mp4

fix: adds missing update for paperdoll direction order

---

Intersect.Client/Core/Audio.cs
Intersect.Client/Core/Fade.cs
Intersect.Client/Core/Graphics.cs
Intersect.Client/Core/Main.cs
Intersect.Client/Core/Sounds/Sound.cs
Intersect.Client/Entities/Animation.cs
Intersect.Client/Entities/ChatBubble.cs
Intersect.Client/Entities/Critter.cs
Intersect.Client/Entities/Entity.cs
Intersect.Client/General/Time.cs
Intersect.Client/Interface/Game/AnnouncementWindow.cs
Intersect.Client/Interface/Game/Bag/BagItem.cs
Intersect.Client/Interface/Game/Bank/BankItem.cs
Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
Intersect.Client/Interface/Game/EventWindow.cs
Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs
Intersect.Client/Interface/Game/Inventory/InventoryItem.cs
Intersect.Client/Interface/Game/Spells/SpellItem.cs
Intersect.Client/Interface/Game/Trades/TradeItem.cs
Intersect.Client/Interface/Game/Typewriting/Typewriter.cs
Intersect.Client/Interface/Shared/SettingsWindow.cs
Intersect.Client/Maps/ActionMessage.cs
Intersect.Client/Maps/MapInstance.cs
Intersect.Client/Maps/WeatherParticle.cs
Intersect.Client/MonoGame/Graphics/MonoRenderer.cs
Intersect.Client/MonoGame/Graphics/MonoTexture.cs

- If the server is started while the client is already open while in the main menu, the animated background (if there's any) abruptly stops as the client detects the server's status changing from offline to online due to time synchronization issues, this can rely on MillisecondsUtc, which avoid this unintended behavior.
- Similar issue happens with the day/time/hue color cycles in game, we don't need to sync the clients to Milliseconds (sColorUpdate), MillisecondsUtc is the way.
- Hopefully fixes a reported issue where weather suddenly "stops" falling in some maps [(?) (need more testing - unable to reproduce yet).](https://github.com/AscensionGameDev/Intersect-Engine/issues/1725)
Without having to worry about server timing synchronization (+ potentially avoids issues): 
- Animations …

fix: client-side timing synchronization

---

Intersect.Editor/Content/Texture.cs
Intersect.Editor/Core/Graphics.cs
Intersect.Editor/Core/Main.cs
Intersect.Editor/Entities/Animation.cs
Intersect.Editor/Forms/frmLogin.cs

* (Tested): As overall, the editor can rely on MillisecondsUtc (local timing) without having to worry about server timing synchronization, this is because the editor it's all about animations, mapping, Winforms UI timers, etc.

chore: editor with local timers

---

Intersect.Client.Framework/Database/GameDatabase.cs
Intersect.Client/Interface/Game/Chat/Chatbox.cs
Intersect.Client/Interface/Shared/SettingsWindow.cs
Intersect.Client/Localization/Strings.cs

- This QoL update adds a handy way to show/hide the chat log by pressing a button. :see_no_evil:
- You may also optionally allow it (via game settings) to auto-show the chat log when pressing enter to chat or auto-hide it when pressing esc to un-focus the chat box.
- This QoL update also adds the ability to clear the entire chat log by pressing a button.
- Chore: fixed some code typos in Chatbox.cs
- Chore (GetDefaultInputText): removed unnecessary "else" keywords, these conditions already *return* by their own.
- Fix (GetDefaultInputText): properly uses the previously unused localized string "Chatbox.enterchat2" - this is used for whenever the user has two configured keys for chatting.
- Should address _at some degree_ the reported issues of #1684 …

enhancement: chat log tools

---

Intersect.Client/Entities/Entity.cs

- I've previously changed this variable set from Timing.Global.Milliseconds to Timing.Global.MillisecondsUtc (https://github.com/AscensionGameDev/Intersect-Engine/pull/1792), right now this is doing some funky stuff to the idle animations, i was about to restore this change but after seeing the way that SpriteFrameTimer is used like and how it's it's already synchronized at L:2041, i've concluded that we simply need to "reset" it down to 0 (which is always going to be < timingMilliseconds) and that we don't really need to call the timer for it when resetting the sprite frame. After doing so, the animation flow for idle was restored to normal.
- should resolve #1808

fix: fully reset SpriteFrameTimer within ResetSpriteFrame

---

Intersect.Server/Entities/Player.cs

Possibly a fix for #1818, though it happens in a different location

fix: fall back to MapId when oldMap is null

---

Intersect.Client/Entities/Entity.cs
Intersect.Client/Entities/Player.cs

- Previous attempt to fix #1649 by swapping `Sprite ?? TransformedSprite` for `TransformedSprite ?? Sprite` at SpellCast specifically was a total mess as it broke Weylon's custom animation override for casting. So, after some testing and code reading, i've concluded that replacing these with `string.IsNullOrEmpty(TransformedSprite) ? Sprite : TransformedSprite` is instead, the good way to go, this fixes the originally reported issues at #1649 while maintaining the original behavior for non-transformed entities.
- Should resolve #1806

fix: LoadAnimationTexture, Sprite and TransformedSprite

---

Intersect.Server/Database/DbInterface.cs
Intersect.Server/Networking/PacketHandler.cs

Minor cleanup and logic update to delete map events when maps are removed from the db
Untested. Someone should verify before we merge.

fix #1848 - map events not being deleted when the parent maps are removed

---

Intersect.Client/Core/Controls/ControlEnum.cs
Intersect.Client/Core/Controls/Controls.cs
Intersect.Client/Core/Input.cs
Intersect.Client/Localization/Strings.cs
Intersect.Client/MonoGame/Input/MonoInput.cs

Resolves #1868 
Assets: AscensionGameDev/Intersect-Assets#43
Re-enables Alt keybinds, not sure why it was ever disabled. It works on Linux at the very least :shrug: 
Default fullscreen keybind is Alt+Enter
- many browsers use F11, but we already have this for ToggleGui
- many games use Alt+Enter, so I went with this

feat: toggle fullscreen key

---

Intersect.Server/Intersect.Server.csproj
Intersect.Server/Notifications/Notification.cs

fix: smtp emails not sending using tls 1.2 in mono runtime environments

---

Intersect.Server/Migrations/Game/20201001163344_ItemAndSpellCooldownImprovements.cs
Intersect.Server/Migrations/Game/20211026130945_NpcImmunityMigration.cs

migrating string columns should not have default values at all !
should resolve #1010
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/d42a7d6c-6793-4b30-9e16-a7abeacfc203

fix: Game DB migration to MySQL

---

Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs

Should resolve #1898 
Preview:

fix: entityExperienceToNextLevel as Long within EntityBox 

---

Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs

As reported in discord:
Preview of this PR:

fix: cast entityExperience to float for percentage calculation

---

Intersect (Core)/Config/ProcessingOptions.cs
Intersect.Server/Entities/Player.cs

Resolves #1904 
Adds a timer to remove stale cooldowns while a player is logged in.
Instead of duplicating the removal code between logout and runtime removal, I turned removal of spell and item cooldowns into a re-usable method.
Won't solve major issues at the moment, but will at least stop sending endless stale records around constantly for the time being.

enh: Add timer to remove stale cooldowns during playtime

---

Intersect.Client/Entities/Player.cs

Resolves #1908 
Original GetSpellRemainingCooldown method accessed the Item Cooldown collection, rather than the Spell one. 
Changed up the method to be less susceptible to race conditions through variable caching.

Fix KeyNotFoundException and potential race conditions in GetSpellRemainingCooldown

---

Intersect.Server/Entities/Player.cs
Intersect.Server/Localization/Strings.cs

resolves #1727 
Full refactoring of the server BuyItem method.
- Now the server says to client if there is no space in the inventory and won't let you buy (resolving the bug)
- Added bug checks if buy or sell item is null
- Correctly removes the amount of currency-item from the player
- If the currency-item was not stockable (don't ask me why a currency-item would be non-stockable), the FindInventoryItemSlot methods only look for the first slot with the desired amount, I improved the search to remove the desired amount from all slots, regardless of whether it is stockable or not, in addition to using a better method to know the amount of items that the player has.
Note: Selling items is buggy the same way buying items was, when playing with inventory limits, my next pr will be to refactor …

fix: correctly removes currency amount inShop

---

Intersect.Server/Entities/Entity.cs

Resolves #1913 
Cache Player.Party as a copied array so that we can avoid the collection being modified as we iterate over it whenever an Entity dies with IndividualizedLootAutoIncludePartyMembers enabled in the server config.

fix: Cache player party in Entity.Die to avoid Collection Modified Exceptions

---

Intersect.Client/Entities/Entity.cs

Resolves #1920 
Have not been able to reproduce the issue Nazio reports, however this is the only place I can possibly see it crashing with an IndexOutOfRangeException. This way it should check if the value is valid before trying to pull the data from the two dimensional array.

fix: Potential IndexOutOfRangeException on Entity.DetermineRenderOrder

---

Intersect.Editor/Forms/frmLogin.cs
Intersect.Editor/General/Globals.cs
Intersect.Editor/Networking/Network.cs

Resolves #1942 
Yes, I'm aware there's likely a better and cleaner way.
Yes, I know this is stupid.
But since the entire editor is getting replaced anyway, I don't want to spend too long fixing a small UI countdown timer you won't even see most of the time.

fix: Correct the editor reconnect attempt timer in the most hideous of ways

---

Intersect.Server/Entities/Entity.cs
Intersect.Server/Entities/Npc.cs
Intersect.Server/Maps/MapController.cs

- Should resolve #1875
Preview:
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/fa88b328-3307-4ede-8d7a-9f053155706b

fix: properly handle NPCs directions near map borders

---

Intersect.Client/Entities/Entity.cs

Adjusted player's DirectionToTarget method to properly handle directions near map borders and across different maps.
Should resolve #1946
Preview:
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/1e7aad50-b718-4f62-9e3f-2c55d9b54358

fix: players auto-turning towards targets at map borders

---

Intersect.Client/Entities/Entity.cs

This will correct the character's animations being hidden along with the rest of the entity when entering hidden mode, very useful for GMs who want to spy on players.

Fix: hides character animations when entering hidden mode

---

Intersect (Core)/Network/Packets/Client/BuyItemPacket.cs
Intersect (Core)/Network/Packets/Client/DepositItemPacket.cs
Intersect (Core)/Network/Packets/Client/DropItemPacket.cs
Intersect (Core)/Network/Packets/Client/OfferTradeItemPacket.cs
Intersect (Core)/Network/Packets/Client/RetrieveBagItemPacket.cs
Intersect (Core)/Network/Packets/Client/RevokeTradeItemPacket.cs
Intersect (Core)/Network/Packets/Client/SellItemPacket.cs
Intersect (Core)/Network/Packets/Client/StoreBagItemPacket.cs
Intersect (Core)/Network/Packets/Client/WithdrawItemPacket.cs
Intersect (Core)/Network/Packets/SlotQuantityPacket.cs

Fixes #1953 by correcting the `[Key(#)]` attributes on the different slot packets
For some reason the base slot packet had `[Key(3)]` on a `bool` property with only an expression-body getter (so quite literally cannot be set even with reflection hacks), and the deposit bank slot was `[Key(0)]`.
It appears that there isn't actually a `[Key(0)]` on anything? Which is weird, but whatever. The problem is that the weird key situation was causing deserialization to totally break, and I am guessing since our .NET 7 upgrade MessagePack actually expects the code to be correct instead of correcting for developer mistakes.

fix: correct keys on slot packets

---

Intersect (Core)/Config/CombatOptions.cs
Intersect.Client/Entities/Entity.cs
Intersect.Client/Entities/Player.cs
Intersect.Server/Entities/Entity.cs

This PR seeks to cover the following:
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/ebed9fe8-1525-4228-9286-c1d1ae7742d6
The PR adds a configurable combat option to the server settings which enables/disables the ability to turn around while casting.

enhancement: toggle turn around while casting

---

Intersect.Server/Database/PlayerData/User.cs
Intersect.Server/Entities/Player.Database.cs

This will allow some API calls which would time out, like player rankings to succeed.

Use .AsSplitQuery() on anything with a lot of Includes for a huge performance boost

---

Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs
Intersect.Client/Localization/Strings.cs

Resolves #1987 
Fixes the lack of a display for items we're crafting and adds a visible stat range if applicable.
Now stop bugging me about this.
https://github.com/AscensionGameDev/Intersect-Engine/assets/13875600/fb2f46e5-d706-4feb-b282-8e46bec05bb0

enhancement: Display stats and stat ranges on crafting tables

---

Intersect (Core)/Config/MapOptions.cs

- "Height" has been renamed to "MapHeight" in 0.8-beta
- "Width" has been renamed to "MapWidth" in 0.8-beta

chore: removes obsolete map options

---

Intersect (Core)/Config/MapOptions.cs
Intersect.Server.Core/Entities/Entity.cs

I think many project owners use this type of map for some pvp system or battle in general, I'm sending this suggestion that will protect the player's item drops when dying on this type of map.

enhancement: don't drop items in arena map.

---

Intersect (Core)/Config/MapOptions.cs
Intersect.Server.Core/Entities/Player.cs

As the title already explains, this will allow you to choose between losing experience on maps such as arena or not.

enhancement: don't loss exp in arena map

---

Intersect.Client/Program.cs

this makes debugging startup failures on remote
devices (like steamdecks) easier to accomplish

feat: add `--debugger` flag to wait for debugger

---

Intersect (Core)/Config/MapOptions.cs
Intersect (Core)/Config/Options.cs
Intersect.Client/Maps/MapInstance.cs

enhances spawned/dropped items in maps by:
- Adding configurable size for their sprites.
- Centering their sprites in relation to the tiles they occupy.
_This doesn't requires additional texture loading, this simply allows the users to configure the size the icon textures.
The implementation also makes sure to always center the item's texture in relation with the tile they occupy while considering the configured item render size, this way we are not limited by the boundaries of the tile size of the grid anymore._
Preview:

enhancement: configurable map items size

---

Intersect.Server.Core/Networking/PacketHandler.cs

fix: restrict loot distance to the smallest of map width/map height/max loot distance

---

Intersect (Core)/GameObjects/ItemBase.cs
Intersect.Server.Core/Database/DbInterface.cs
Intersect.Server.Core/Database/IntersectDbContext.cs
Intersect.Server.Core/Entities/Player.Database.cs
Intersect.Server.Core/Entities/Player.cs
Intersect.Server.Core/Networking/PacketHandler.cs
Intersect.Server.Core/Networking/PacketSender.cs
Intersect.sln.DotSettings

Resolves #2053 
Without this fix for both quests and variables I was able to crash by quickly getting the quest/variable (that did not previously exist in the DB) and then exiting to character selection _as fast as possible_.
My theory (verified I suppose by the fact that I was able to reproduce 100% of the time without the fix, and no longer able to reproduce this with the fix) is that when we loaded the relationships for the characters it populated the `Id` of the entity before it could save.
This put the new record into an invalid `Modified` state, which generates an `UPDATE` statement instead of `Added` which would have generated an `INSERT` statement. Of course `UPDATE` fails because the record does not yet exist.
The fix is to not load relationships if the player is in the middle of …

fix(2053): don't reload relationships for last character

---

Intersect.Client/Core/Main.cs
Intersect.Client/Interface/Menu/SelectCharacterWindow.cs
Intersect.Network/LiteNetLib/LiteNetLibInterface.cs
Intersect.Server.Core/Core/ServerContext.cs
Intersect.Server.Core/Database/IntersectDbContext.cs
Intersect.Server.Core/Database/PlayerData/Players/Variable.cs
Intersect.Server.Core/Database/PlayerData/User.cs
Intersect.Server.Core/Database/PlayerData/UserSaveResult.cs
Intersect.Server.Core/Entities/Player.cs
Intersect.Server.Core/Networking/PacketHandler.cs
Intersect.Server.Core/Networking/PacketSender.cs
Intersect.Server/Intersect.Server.csproj

can still cause it by logging in with no pv, setting the pv and quickly exiting to char select, logging out, deleting the pv instance from the player db, logging back in, setting the pv, and quickly exiting to char select (and maybe even just normal logout triggers it in this specific scenario?)

fix: prevent crash when going to character select from ingame

---

Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs

fix: Display appropriate max vital when at 0 vital

---

Intersect.Server.Core/Core/LogicService.LogicThread.cs
Intersect.Server.Core/Core/MapInstancing/Controllers/InstanceController.cs
Intersect.Server.Core/Core/MapInstancing/InstanceProcessor.cs
Intersect.Server.Core/Entities/Events/CommandProcessing.cs
Intersect.Server.Core/Entities/Player.cs
Intersect.Server.Core/Maps/MapController.cs
Intersect.Server.Core/Maps/MapInstance.cs

The idea of an "Instance Controller", and subsequent InstanceProcessor, is to have some entity out there (in-memory) that can manage instance state, outside the scope of a player. This will be required for...
- Instance Variables
- Fixing the bug where mob respawn timers aren't respected in an instance that has had a map cleaned up
- Perma-dead instance NPCs
- Etc

feat: (Day) Add an instance controller for prep for future work

---

Intersect.Server.Core/Entities/Npc.cs

Fixes an issue where NPCs casting friendly AoE spells, such as to create a support NPC, do not consider other NPCs as friendly unless they are the exact same NPC as the caster.
NPCs should default to handling eachother as allies unless otherwise noted in the NPC's definition that they are hostile to certain NPCs

fix: (Day) Fix so enemies can cast friendly spells on eachother

---

Intersect.Server.Core/Entities/Player.cs

The player's MapId references a new map, but the 'map' variable in the event loop is referring to the original/old map.
Adding after loop "map = MapController.Get(MapId);" fixes the #2132 issue.

bug fix #2132

---

Intersect (Core)/GameObjects/LightBase.cs

Fixes #1716
I've added TileX and TileY to both methods GetHashCode() & Equals() in LightBase.cs
This change ensure that the hash code and equality comparison take into account the TileX and TileY properties, necessary for drag / copy / undo ...

bug fix #1716

---

Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs

Fixes #2135 
I've added a null check for the range.
This change ensures that the code handles scenarios where the range object is null and prevents unexpected client crashes.

bug fix #2135

---

Intersect.Server.Core/Entities/BankInterface.cs

Issue is basically about equipped items not being unequipped before we take them out of the inventory into the bank, which triggers the funky behavior reported at #2155 
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/ffdd43a3-7ee5-4dfa-8447-e92d902b59c0
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/d7fb766c-1ab3-4a08-92db-ca8b51078235

fix: unequip equipment when depositing into the bank

---

Intersect.Server.Core/Entities/Entity.cs
Intersect.Server.Core/Entities/Player.cs

Fixes #1683 
Which reported a bug where a spell with ammunition requirements would consume the last projectile without actually casting it out. It is also intended to provide additional chore changes and move player related code out to it's corresponding overrides.
Files changed:
1. Entity.cs - Moved projectile removal to player's CastSpell override method. Also moved the player's specific handlers for spell's cooldown to player's CastSpell override method.
2. Player.cs - Removed redundant and repeated code within the UseSpell method (ie. CastSpell(..) is already called within Entity's Update method when required) and added projectile removal and cooldown handlers within the CastSpell override method.
Bug:
https://user-images.githubusercontent.com/17498701/206912343-1b49c1e3-e80f-4e66-96b6 …

fix: last projectile spell casting

---

Intersect.Server.Core/Entities/Player.cs

Fixes #2177
Restored quick casting functionality for spell items, resolving my mess from PR #2174. Also ensured last projectile removal for quick casted spells is working as expected.
Preview:
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/8453d9c4-6ffc-4f1f-a949-695c77cd2ee3

fix: item's quick cast

---

Intersect.Editor/Forms/Editors/frmItem.Designer.cs

Fixes https://github.com/AscensionGameDev/Intersect-Engine/issues/2182
[Intersect Client 2024-03-24 00-14-08.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/14734354/Intersect.Client.2024-03-24.00-14-08.zip)
Works in client I tested it, zip has video.
If you set it to something like -200% the player will be left with one health. The game does that by design.

Item Vitals can now have negative values

---

Intersect.Editor/Forms/frmMain.cs

Should fix #2196
After upgrading to .NET7, starting the editor shows up the MapGrid (world view) window tab as selected instead of the MapEditor. Seeing the code, this is what actually makes sense, no idea why it wasn't behaving like this before upgrading, but the expected behavior is to have the MapEditor to show up at the end of the form initialization. This commit sets it to be shown by the end, giving us back the expected behavior we originally had.

fix: show MapEditor upon starting the editor

---

Intersect.Editor/Core/Graphics.cs
Intersect.Editor/Forms/DockingElements/frmMapLayers.Designer.cs
Intersect.Editor/Forms/DockingElements/frmMapLayers.cs
Intersect.Editor/Forms/Helpers/GridHelper.cs
Intersect.Editor/Localization/Strings.cs

- Adds the ability to highlight selected NPC with declared spawn within the map grid
(Resolves #1055)
- Adds configurable pulsating color for selected NPC spawns
- QoL enhancements and fixes for declared/random spawns:
- Differently colored text as visual aid
- Pressing the random checkbox for spawn location updates the grid preview
- QoL enhancements on forms organization within the NPCs map layers tab
- Adds a spawn counter under the NPC list
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/f12c5ff8-e6c9-4e11-b6f2-8347f88630a7

feature: ability to highlight selected NPC with declared spawn

---

Intersect.Server.Core/Core/Bootstrapper.cs
Intersect.Server.Core/Localization/Strings.cs

This enhancement PR extends server statistics information on startup
- Provides Motivation for Developers: By displaying server statistics during development, developers can gain a sense of progress and achievement, which can boost motivation and productivity.  
- Facilitates Performance Analysis: The additional server statistics can serve as a valuable tool for performance analysis. By monitoring these statistics, developers can identify potential bottlenecks or performance issues, enabling proactive optimization of the server.

enhancement: extend server statistics on startup

---

Intersect.Server.Core/Entities/Combat/DoT.cs

Fixes #2231 
This ensures that any remainder from the division is accounted for, avoiding the loss of ticks.

bug fix #2231

---

Intersect.Client/Interface/Game/Trades/TradingWindow.cs
Intersect.Server.Core/Localization/Strings.cs
Intersect.Server.Core/Networking/PacketHandler.cs

- The trade button is now disabled upon pressing it.
- Players will now receive an informative message when the counterparty accepts theirs offer, indicating readiness for the trade to proceed.
Preview:

enhancement: trade offer accepted

---

Intersect.Server.Core/Entities/Projectile.cs

Did some research on this today, this PR should fix #2195 
Here are some of the tests i did when trying to figure this out:
By default maps have (0+31x0+25) tiles `("MapWidth": 32, "MapHeight": 26)` (x,y) 
- shooting from 0,0 to the left map: projectiles goes to next map fine
- shooting  from 0,25 to the left map: projectiles does not go to next map (bug)
- shooting diagonally from 31,0 to the right map: projectiles does not go to next map (bug)
- shooting diagonally from 0,25 to the left map: projectiles doesn't not go to next map (bug)
The issue seems to be related to the way we're checking the boundaries of the map. We're using `Math.Round(newx)` and `Math.Round(newy)` to determine if the projectile has hit the edge of the map. This could cause issues if the projectile's `x` or `y` …

fix: map boundary checks for projectiles

---

Intersect (Core)/GameObjects/ClassBase.cs
Intersect (Core)/GameObjects/ItemBase.cs
Intersect (Core)/GameObjects/NpcBase.cs
Intersect (Core)/GameObjects/SpellBase.cs
Intersect (Core)/Network/Packets/Server/EntityPacket.cs
Intersect (Core)/Network/Packets/Server/EntityVitalsPacket.cs
Intersect (Core)/Network/Packets/Server/MapEntityVitalsPacket.cs
Intersect (Core)/Network/Packets/Server/PartyMemberPacket.cs
Intersect (Core)/Network/Packets/Server/StatusPacket.cs
Intersect (Core)/Utilities/DatabaseUtils.cs
Intersect.Client.Framework/Entities/IEntity.cs
Intersect.Client.Framework/Entities/IPartyMember.cs
Intersect.Client.Framework/Entities/IStatus.cs
Intersect.Client/Entities/Entity.cs
Intersect.Client/Entities/PartyMember.cs
Intersect.Client/Entities/Status.cs
Intersect.Client/Interface/Game/Character/CharacterWindow.cs
Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
Intersect.Server.Core/Entities/Combat/Status.cs
Intersect.Server.Core/Entities/Entity.cs
Intersect.Server.Core/Entities/Npc.cs
Intersect.Server.Core/Entities/Player.cs
Intersect.Server.Core/Entities/Resource.cs
Intersect.Server.Core/General/Formulas.cs

We previously updated the EXP values to long type so we could store values from -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807, but we didn't quite updated everything else related to this, plus, we ended up with lack of support for large values on vitals and consumable data... this chore PR makes sure to cover the missing stuff
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/ca1df184-d91e-47b4-ba37-2bd241c8819e

chore: long value type for Vitals, Exp and ConsumableData

---

Intersect.Server.Core/Entities/Player.cs

Fixes #2226 which reported an issue where LastAttackingWeapon wasn’t updated when shooting projectiles and spells, resulting in it not being properly used for CachedEquipmentOnHitTriggers
reference: https://github.com/AscensionGameDev/Intersect-Engine/issues/2226#issuecomment-2094495791
Results:
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/f2495235-875c-4f0b-b33e-c7b5f9647b55

fix: set LastAttackingWeapon for EquipmentOnHitTriggers

---

Intersect.Client/Core/Input.cs

This PR Fixes #2253
- Expected behavior: taunt's effect forces it's target to be the caster, removing the target shouldn't be possible.
- Current-not-expected behavior: pressing the esc / menu key clears the current target while taunted.
- After this PR: taunt's effect forces it's target to be the caster, removing the target is not possible at all

fix: don't clear current target when taunted

---

Intersect (Core)/Network/Packets/Client/LogoutPacket.cs
Intersect.Client/Core/Main.cs
Intersect.Client/Interface/Game/EscapeMenu.cs
Intersect.Client/Interface/Menu/CreateCharacterWindow.cs
Intersect.Client/Interface/Menu/ForgotPasswordWindow.cs
Intersect.Client/Interface/Menu/RegisterWindow.cs
Intersect.Client/Interface/Menu/ResetPasswordWindow.cs
Intersect.Client/Interface/Menu/SelectCharacterWindow.cs
Intersect.Client/Networking/PacketSender.cs
Intersect.Server.Core/Networking/PacketHandler.cs

resolves #2251 
Small explanation about:
When we pressed the logout button, it only considered whether it was changing characters or not, if it was changing characters then it kept the account logged in, if it wasn't changing, it disconnected the client.
The change I am proposing is to consider that by pressing the logout button, we are going to the main menu, where the client must still be logged in, but without a logged in user
Another problem solved is that when the connection actually drops, we always received 2 disconnection alerts, one from the interface and the other from the packet handler "onDisconnect", I removed all the interface warnings to leave just one real one where it actually makes more sense to have.
video showing working: …

fix: disconnection error message when returning to the main menu

---

Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs

resolves #2150
there was only one more condition missing, the equipment would only follow the standard intersect behavior if Stat.Range.Lenght was 0, but we must also be ensured that it exists and the current stat is 0 for low and high to also continue with the standard behavior.

fix: equipment dont showing stat info on crafting

---

Intersect.Server.Core/Entities/Events/CommandProcessing.cs
Intersect.Server.Core/Entities/Player.cs
Intersect.Server.Core/Networking/PacketHandler.cs

resolves #2170 
I tried to add more checks for many things that happen in real time that could be equipment conditions, some tiny things are not yet covered, but this should already solve the problem for most of our developers
More checks have been added in:
Variable change
Inventory change
Class change
Spells change
Stat change
Power Level change
Some quests changes
Gender change
Guild Rank changes
Maybe some others, but I don't remember

fix: add more equip checks for more conditions

---

Intersect.Client/Entities/Projectiles/Projectile.cs
Intersect.Server.Core/Entities/Projectile.cs

resolves #2276 
there is a grid size check only on the client's y-axis, I added it on the x-axis too and on the server side

fix: adds missing projectile grid size checks

---

Intersect.Client.Framework/Gwen/Control/Base.cs
Intersect.Client/Entities/Entity.cs
Intersect.Client/Entities/Player.cs
Intersect.Client/Interface/Game/DescriptionWindows/Components/ComponentBase.cs
Intersect.Client/Interface/Game/DescriptionWindows/DescriptionWindowBase.cs
Intersect.Client/Interface/Game/DescriptionWindows/SpellDescriptionWindow.cs
Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
Intersect.Client/Interface/Game/EntityPanel/PlayerStatusWindow.cs
Intersect.Client/Interface/Game/EntityPanel/SpellStatus.cs
Intersect.Client/Interface/Game/GameInterface.cs
Intersect.Client/Localization/Strings.cs
Intersect.Client/Networking/PacketHandler.cs

- Sets the player status window free from the burdens of the PlayerBox, engine users can now edit the player's status window with it's own json file so they are not limited to edit the the status window within the playerbox anymore.
- revamps the design for player, target and status windows.
- uses drop-down menu for player options instead of buttons, saves space, more simple, same results.
- status window has been modified in order to work as a scroll controller, spell icons are placed and adapted to their window width, rows and columns, and the entire window i hidden and will show up only when there's an active status count of > 0
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/f003e85b-fdd3-4a54-80e7-7bbfa0b652a4
Assets: …

enhancement: player, target and status window revamp

---

Intersect (Core)/GameObjects/Drop.cs
Intersect.Editor/Forms/Editors/frmNpc.Designer.cs
Intersect.Editor/Forms/Editors/frmNpc.cs
Intersect.Editor/Forms/Editors/frmNpc.resx
Intersect.Editor/Forms/Editors/frmResource.Designer.cs
Intersect.Editor/Forms/Editors/frmResource.cs
Intersect.Editor/Forms/Editors/frmResource.resx
Intersect.Editor/Localization/Strings.cs
Intersect.Server.Core/Entities/Npc.cs
Intersect.Server.Core/Entities/Resource.cs
Intersect.Server.Core/Migrations/Sqlite/Game/20240607220428_RandomDrops.Designer.cs
Intersect.Server.Core/Migrations/Sqlite/Game/20240607220428_RandomDrops.cs

resolves #2209
The default Amount for all games now becomes MaxQuantity in the logic of this pr, but nothing has been renamed, and there is a migration that updates the npcs and resources tables to add MinQuantity. So after this pr, all games will drop a minimum of 1 - Amount when they update.
I'm also bringing the possibility of editing items that already exist in the drop list, both in the npcs and resources editor (I don't know why we didn't have this before)
https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/53e4851f-c94d-420f-8630-bae629023b36
https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/03d36584-7aa2-4987-bc22-7b835cccf7df

feature: amount range for item drops

---

Intersect (Core)/Config/CombatOptions.cs
Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs

Adds a server combat option that if enabled (default), the target window will be shown to players whenever they target an entity
(Server Config - Combat):
Enabled (default):
Disabled:

enhancement: optional target window

---

Intersect.Client/Entities/Projectiles/Projectile.cs
Intersect.Client/Entities/Projectiles/ProjectileSpawns.cs
Intersect.Server.Core/Entities/Projectile.cs
Intersect.Server.Core/Entities/ProjectileSpawn.cs

- projectile related code has been refactored, documented and commented.
- renamed variables to follow current Intersect's naming conventions.
- fixed variable typos.
- removed unused variables, libraries and imports.
- a lot of methods have been merged into one (GetProjectileOffset, GetRange, FindProjectileRotation) for better organization.
- created AdjustPositionOnMapBoundaries methods for better organization within CheckForCollision (server and client)
- Suppress finalization to optimize garbage collection on projectile disposal (client), this is important for performance and to prevent the finalizer from running.
- fixes server crash due to IndexOutOfRangeException when attacking across maps and when NPCs change maps (#2287).
- fixes projectiles not crossing map boundaries when …

projectile refactoring: fixes, docs, enhancements

---

Intersect.Network/Lidgren/LidgrenBuffer.cs
Intersect.Network/Lidgren/LidgrenConnection.cs
Intersect.Network/Lidgren/LidgrenInterface.cs
Intersect.Network/LiteNetLib/AesAlgorithm.cs
Intersect.Network/LiteNetLib/LiteNetLibConnection.cs

(side note: implicit usings were introduced with .NET 6)

chore: removes unnecessary and implicit usings from intersect network

---

Intersect.Network/ClientNetwork.cs
Intersect.Network/IServer.cs
Intersect.Network/Lidgren/LidgrenBuffer.cs
Intersect.Network/Lidgren/LidgrenConnection.cs
Intersect.Network/Lidgren/LidgrenInterface.cs
Intersect.Network/NetworkMetaStatus.cs

**Context:** File-scoped namespaces _were introduced in C# 10.0, which was released as part of .NET 6_. This feature allows developers to declare namespaces at the top of a file without enclosing them in a curly brace block, effectively making the namespace applicable to the entire file. Converting namespaces to file-scoped namespaces in C# promotes cleaner, more organized code that is easier to read, maintain, and scale as the project grows. It aligns with modern coding practices and helps prevent potential namespace conflicts, contributing to overall code quality and developer productivity.

chore: converts network namespaces to file-scoped namespaces

---

Intersect.Editor/Content/ContentManager.cs
Intersect.Editor/Forms/DockingElements/frmMapGrid.cs
Intersect.Editor/Forms/DockingElements/frmMapLayers.cs
Intersect.Editor/Forms/DockingElements/frmMapList.cs
Intersect.Editor/Forms/DockingElements/frmMapProperties.cs
Intersect.Editor/Forms/Editors/EditorForm.cs
Intersect.Editor/Forms/Editors/Events/frmEvent.cs
Intersect.Editor/Forms/Editors/Quest/frmQuest.cs
Intersect.Editor/Forms/Editors/frmAnimation.cs
Intersect.Editor/Forms/Editors/frmClass.cs
Intersect.Editor/Forms/Editors/frmCraftingTables.cs
Intersect.Editor/Forms/Editors/frmCrafts.cs
Intersect.Editor/Forms/Editors/frmDynamicRequirements.cs
Intersect.Editor/Forms/Editors/frmItem.cs
Intersect.Editor/Forms/Editors/frmNpc.cs
Intersect.Editor/Forms/Editors/frmProjectile.cs
Intersect.Editor/Forms/Editors/frmResource.cs
Intersect.Editor/Forms/Editors/frmShop.cs
Intersect.Editor/Forms/Editors/frmSpell.cs
Intersect.Editor/Forms/Editors/frmVariable.cs
Intersect.Editor/Forms/frmAbout.cs
Intersect.Editor/Forms/frmMain.cs
Intersect.Editor/Forms/frmOptions.cs
Intersect.Editor/Forms/frmProgress.cs
Intersect.Editor/Forms/frmUpdate.cs
Intersect.Editor/Forms/frmVariableSelector.cs
Intersect.Editor/Forms/frmWarpSelection.cs
Intersect.Editor/Maps/MapGrid.cs
Intersect.Editor/Maps/MapInstance.cs
Intersect.Editor/Networking/PacketHandler.cs

fixes an issue with some missing `using Intersect.Editor.Core` that were updated to their corresponding namespace and folders.
tested and built locally, GHA should properly build the engine now.

fix: editor build after cleanup

---

Intersect (Core)/Intersect.Core.csproj
Intersect.Client/Interface/Game/DescriptionWindows/DescriptionWindowBase.cs
Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs
Intersect.Client/Interface/Game/DescriptionWindows/SpellDescriptionWindow.cs
Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs

- Previous work related to this -> #1650
- Updates the description windows positioning logic to a modern and better approach, similar to what it's seen in most of the MMOs out there where description windows are positioned based on the hovered element.
- Description windows re-positions itself when created near screen borders (inverts positioning side), preventing flicker
-  Fixes #1784
- Works for everything that uses description windows: inventory slots, spell slots, hotbars, trading slots, craft items, bank slots, status, etc.
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/5660f969-7559-42b0-98a6-449b3a20220d

enhancement: bind description window to hovered control

---

Intersect.Client/Core/Input.cs
Intersect.Client/Interface/Menu/MainMenu.cs
Intersect.Client/Interface/Menu/SelectCharacterWindow.cs

Enhancement that allows the game user to press the enter key while in the character select window, in order to select a character to play with. By enabling the player to simply press the enter key to confirm their choice of character, we streamline the user interface and reduce the need for additional mouse clicks or button presses, creating a smoother and more efficient experience for the player.
Preview:
https://github.com/user-attachments/assets/15aa8882-51bc-4d38-ba64-b5feeda0c104

enhancement: press enter key to select character to play

---

Intersect.Client/Interface/Game/DescriptionWindows/Components/ComponentBase.cs
Intersect.Client/Interface/Game/DescriptionWindows/DescriptionWindowBase.cs
Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs
Intersect.Client/Interface/Game/DescriptionWindows/SpellDescriptionWindow.cs

Fixes #2336
I forgot to consider item-spell descriptions while coding #2322
This never really worked as intended anyways, before #2322 it was hard-coded to item description's bottom only and without considering screen edges. This PR fixes that logic and makes it so it dynamically adapts to the hovered control as seen in #2322

fix: spell item description

---

Intersect.Editor/Forms/DockingElements/frmMapLayers.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_Warp.cs
Intersect.Editor/Localization/Strings.cs

Should fix #2259 
Instance type strings is not used at all plus, it's triggering an NSE when starting the game editor.
They were hardcoded to use their enum strings instead of their localized strings.
Preview Note: edited the overworld type string in order to show up that the values aren't hard-coded anymore.

fix: editor NSE for instance type strings

---

Intersect.Client/Interface/Game/Hotbar/HotBar.cs
Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs

This PR adds a new feature [(requested here)](https://github.com/AscensionGameDev/Intersect-Engine/discussions/2300) which allows the hotbar to display quantity of items.
_Currently part of_ [_(v0.8.0-beta.120+) Roadmap_](https://github.com/AscensionGameDev/Intersect-Engine/discussions/2303)
This also features the the ability for the hotbar to count every item, and not only display the value with the right abbreviation as a label, but it will also display the exact value when hovering the cursor over the item/spell in order to view it's description window.
_Reminder: [Merge Assets before Engine PR](https://github.com/AscensionGameDev/Intersect-Assets/pull/52)_
https://github.com/user-attachments/assets/fc685c4f-a1cf-44de-a1d0-1e136531bf24

feature: display quantity of items within hotbar slots

---

Intersect.Client/Entities/Player.cs
Intersect.Client/Interface/Game/Inventory/InventoryItem.cs
Intersect.Client/Interface/Shared/InputBox.cs

Updates `TryDropItem` so we can drop more than a single stack of stackable items, the slider will now also count every inventory item based on the selected stack.
https://github.com/user-attachments/assets/1302c783-be79-43a0-b194-2fc60e39cc72
Also fixes slider's current stack value when the prompt is opened (Thanks @WeylonSantana for finding this out !):
https://github.com/user-attachments/assets/ff53ef94-9583-47ac-ac9a-ec1009bf7dce
https://github.com/user-attachments/assets/77163364-c2af-45d1-bd30-eb0961d7f82d

enhancement: ability to drop multiple stacks of stackable items

---

Intersect.Client/Interface/Debugging/DebugWindow.cs

This is (probably) a fix for an unreported bug, which has no exact reproduction step. Occasionally the debug window would crash the client. I had this problem (client crashing) a few times while doing the previous pr (admin window)
After adding this modification, I no longer had problems with the debug window

fix: debug window crashing client

---

Intersect.Network/ClientNetwork.cs

See more: https://learn.microsoft.com/en-us/dotnet/core/compatibility/networking/7.0/ping-custom-payload-linux
Resolves #2358

fix(2358): pass empty array into Ping.Send() to avoid cap_net_raw breaking change

---

Intersect.Client.Framework/Gwen/Control/WindowControl.cs
Intersect.Client.Framework/Gwen/Skin/Intersect2021.cs

- Add DrawShadow property (default true) to control drawing the backdrop shadow
- DrawBackground of the window now controls if the "frame" (the background, minus the titlebar) is visible
- DrawBackground of the Titlebar node now controls if the "titlebar" image is drawn
Resolves https://www.ascensiongamedev.com/topic/7075-how-do-i-get-this-off-my-screen-v2/

feat: window background transparency

---

Intersect.Client/Core/Graphics.cs

Fixes RenderingEntities inline initialization crashing the client when using custom map width/height
[(We merged this breaking change here)](https://github.com/AscensionGameDev/Intersect-Engine/commit/a5df1c7fae80de097b09112e2e08ad4f0d478b4f#diff-e8a874c3978934c92de6b7e4813fddbfe5dcae510b18694f21827b25e341c1c4L141)
crash log (when changing MapWidth/MapHeight to 64x64):
```
--------------------------------------------------------------------------------
2024-08-07 14:18:25.906 [Error] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack:    at Intersect.Client.Core.Graphics.InitInGame() in C:\Users\Admin\Desktop\VSCode\Intersect-Engine\Intersect.Client\Core\Graphics.cs:line 142
at Intersect.Client.Networking.PacketHandler.HandlePacket(IPacketSender packetSender, …
```

fix: undo RenderingEntities inline initialization

---

Intersect.Client/Core/Graphics.cs

- Adds Null Check: RenderingEntities == null checks if RenderingEntities is not initialized.
- Adds Null Check: Globals.MapGrid == null checks if the 2D array is not initialized.
- Removes default Check: Globals.MapGrid is an array, checking against default is unnecessary.

fix: dereference of possibly null references in core graphics

---

Intersect.Client.Framework/Database/GameDatabase.cs
Intersect.Client.Framework/Gwen/Control/Base.cs
Intersect.Client/Core/Input.cs
Intersect.Client/Interface/Game/GameInterface.cs
Intersect.Client/Interface/Game/Menu.cs
Intersect.Client/Interface/Game/SimplifiedEscapeMenu.cs
Intersect.Client/Interface/Shared/SettingsWindow.cs
Intersect.Client/Localization/Strings.cs

This pull request introduces a simplified escape menu feature with an in-game interface setting to toggle it on/off. It also fixes a long-standing bug that caused an InvalidOperationException client crash when selecting 'yes' on the Combat Warning prompt during logout/exit. 
[Assets (make sure to merge before this PR)](https://github.com/AscensionGameDev/Intersect-Assets/pull/55)
https://github.com/user-attachments/assets/89178793-c94f-49df-bb3c-5c209563ef97
https://github.com/user-attachments/assets/099ce515-5886-4c86-8bba-eb802512fa54
https://github.com/user-attachments/assets/8a3e3694-b77f-4183-9c51-be877429b8ba

feature: simplified escape menu

---

Intersect (Core)/Collections/Slotting/ISlot.cs
Intersect (Core)/Collections/Slotting/SlotList.cs
Intersect (Core)/Config/Options.cs
Intersect.Client.Core/Entities/Entity.cs
Intersect.Client.Core/Interface/Game/Spells/SpellItem.cs
Intersect.Client.Core/Interface/Game/Spells/SpellsWindow.cs
Intersect.Server.Core/Database/DbInterface.cs
Intersect.Server.Core/Database/Item.cs
Intersect.Server.Core/Database/PlayerData/Players/BagSlot.cs
Intersect.Server.Core/Database/PlayerData/Players/BankSlot.cs
Intersect.Server.Core/Database/PlayerData/Players/Guild.cs
Intersect.Server.Core/Database/PlayerData/Players/GuildBankSlot.cs
Intersect.Server.Core/Database/PlayerData/Players/HotbarSlot.cs
Intersect.Server.Core/Database/PlayerData/Players/ISlot.cs
Intersect.Server.Core/Database/PlayerData/Players/InventorySlot.cs
Intersect.Server.Core/Database/PlayerData/Players/SlotHelper.cs
Intersect.Server.Core/Database/PlayerData/Players/SpellSlot.cs
Intersect.Server.Core/Database/PlayerData/User.cs
Intersect.Server.Core/Entities/BankInterface.cs
Intersect.Server.Core/Entities/Entity.cs
Intersect.Server.Core/Entities/IBankInterface.cs
Intersect.Server.Core/Entities/Player.Database.cs
Intersect.Server.Core/Entities/Player.cs
Intersect.Server.Core/Networking/PacketSender.cs

Resolves #2122 
This should resolve collection-size related jackpot crashes in the various "slot" lists, including [the one mentioned in Discord](https://discord.com/channels/363106200243535872/965617981159788614/1320063351400828949) (I don't think it has a bug open?)

fix: avoid jackpots on changed slot collection sizes

---

Intersect.Server.Core/Database/PlayerData/LoginFailureReason.cs
Intersect.Server.Core/Database/PlayerData/LoginFailureType.cs
Intersect.Server.Core/Database/PlayerData/Players/BankSlot.cs
Intersect.Server.Core/Database/PlayerData/Players/GuildBankSlot.cs
Intersect.Server.Core/Database/PlayerData/Players/GuildVariable.cs
Intersect.Server.Core/Database/PlayerData/Players/HotbarSlot.cs
Intersect.Server.Core/Database/PlayerData/Players/InventorySlot.cs
Intersect.Server.Core/Database/PlayerData/Players/PlayerVariable.cs
Intersect.Server.Core/Database/PlayerData/Players/Quest.cs
Intersect.Server.Core/Database/PlayerData/Players/SpellSlot.cs
Intersect.Server.Core/Database/PlayerData/Players/Switch.cs
Intersect.Server.Core/Database/PlayerData/Players/UserVariable.cs
Intersect.Server.Core/Database/PlayerData/User.cs
Intersect.Server.Core/Localization/Strings.cs
Intersect.Server.Core/Networking/PacketHandler.cs
Intersect.Server/Networking/NetworkedPacketHandler.cs

- Fixes the case where a new character is created and logged in on the client but has not saved yet and then the editor is logged into afterwards (but before the user auto-saves)

fix: save already logged in user before allowing a second login

---

Intersect (Core)/GameObjects/ItemBase.cs
Intersect.Client.Core/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs

Resolves #2356 
- Remove ItemBase.StatRanges (which was not in the correct order and was part of the reason it was broken before)
- change duplicate accessors to local variable

fix(2356): only display x-to-y ranges as a range, treat x-to-x as a flat stat

---

Intersect.Client.Core/Maps/ActionMessage.cs
Intersect.Client.Core/Maps/MapInstance.cs
Intersect.Client.Framework/Maps/IActionMessage.cs

- Also clean up ActionMessage class

fix: action message X coordinate was mistakenly using map's Y coordinate

---

Intersect.Client.Core/Entities/Resource.cs
Intersect.Client.Framework/File Management/GameContentManager.cs

fix(2376): load textures for tileset resources that are waiting after the tilesets are loaded

---

Intersect.Editor/Forms/DockingElements/frmMapEditor.cs
Intersect.Editor/General/Globals.cs

- Removed `CursorUpdateTimer_Tick` method.
- Added global `CurrentTool` property with `ToolChanged` event to manage tool state.
- Reduced unnecessary calls to `SetCursorSpriteInGrid()`.

chore: Refactor tool cursor updates in MapEditor

---

Intersect.Client.Core/Entities/Player.cs
Intersect.Client.Core/Interface/Game/EntityPanel/EntityBox.cs
Intersect.Client.Core/Interface/Game/GameInterface.cs
Intersect.Client.Core/Interface/Game/TargetContextMenu.cs
Intersect.Client.Core/Localization/Strings.cs

- extracts player context menu out of EntityBox.cs
- (new) feature: allows to right-click players in order to view player's context menu!
- (new) player context menu item: private message!
- part of https://github.com/AscensionGameDev/Intersect-Engine/discussions/2303
https://github.com/user-attachments/assets/73b67ccc-d68e-43d5-a104-3485f9656dc4

enhancement: player context menu

---

Intersect.Client.Core/Interface/Game/TargetContextMenu.cs

_targetNameMenuItem to display the target player's name in the context menu. Instead of using label, ensured  the menu item is non-interactive.
Co-authored-by @Arufonsu 
https://github.com/user-attachments/assets/0d5d4e2f-de36-405c-83c6-92135c4e2abf

enhancement: Add target context menu item

---

Intersect.Client.Core/Core/Input.cs

fix(2469): hide escape menu if it's open when trying to toggle simplified menu

---

Intersect.Client.Core/Interface/Game/GameInterface.cs

fix(2468): treat TargetContextMenu as one of the windows that should be closed

---

Intersect.Server.Core/Entities/Entity.cs
Intersect.Server.Core/Entities/Npc.cs

resolves #2460 
1. Hit entity when entity is invisble in 3 cases
a. when using projectiles spells
b. when using aoe spells
c. when using single target spell on a visible player, but there is player in stealth inside hit radius
2. Dont keep looking at the entity if the entity is invisible
3. If there is another valid target on range when the current target becomes invisible, change target.

fix: some npc behaviors

---

Framework/Intersect.Framework.Core/GameObjects/Drop.cs
Intersect.Editor/Forms/Editors/frmNpc.Designer.cs
Intersect.Editor/Forms/Editors/frmNpc.cs
Intersect.Editor/Forms/Editors/frmNpc.resx
Intersect.Editor/Forms/Editors/frmResource.Designer.cs
Intersect.Editor/Forms/Editors/frmResource.cs
Intersect.Editor/Forms/Editors/frmResource.resx
Intersect.Editor/General/NotifiableDrop.cs
Intersect.Editor/Localization/Strings.cs
Intersect.Server.Core/Entities/Npc.cs
Intersect.Server.Core/Entities/Resource.cs

Resolves #2488 
The default Amount for all games now becomes MaxQuantity in the logic of this pr, but nothing has been renamed. So after this pr, all games will drop a minimum of 1 - Amount when they update.
I'm also bringing the possibility of editing items that already exist in the drop list, both in the npcs and resources editor (I don't know why we didn't have this before)
https://github.com/user-attachments/assets/cc991795-4cff-419f-8cf2-3eb8fd3c7a14

feat: random drops

---

Framework/Intersect.Framework.Core/GameObjects/Events/Commands/EventCommands.cs
Framework/Intersect.Framework.Core/GameObjects/Events/CommonEventTrigger.cs
Intersect (Core)/CustomColors.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_GiveExperience.Designer.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_GiveExperience.cs
Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_GiveExperience.resx
Intersect.Editor/Localization/Strings.cs
Intersect.Server.Core/Entities/Events/CommandProcessing.cs
Intersect.Server.Core/Entities/Player.cs
Intersect.Server.Core/Localization/Strings.cs

resolves #2491
- refactor give exp editor
- adding support for decreasing the player's level using the give exp command
- added a new event common trigger
https://github.com/user-attachments/assets/a0e0b033-a8a6-4aa8-87a5-07a4a787ab9e

Add level down support

---

Intersect.Server.Core/Entities/Npc.cs

fix(2490): Make NPCs attack and target other NPCs if they're NPC vs NPC combat is enabled

---

Intersect (Core)/Network/Packets/Server/MapPacket.cs
Intersect.Client.Core/Core/Sounds/MapSound.cs
Intersect.Client.Core/Entities/Entity.cs
Intersect.Client.Core/Entities/Events/Event.cs
Intersect.Client.Core/Entities/Projectiles/Projectile.cs
Intersect.Client.Core/General/Globals.cs
Intersect.Client.Core/Maps/MapInstance.cs
Intersect.Client.Core/Networking/PacketHandler.cs
Intersect.Client.Framework/Maps/IMapInstance.cs
Intersect.Server.Core/Maps/MapController.cs
Intersect.Server.Core/Networking/PacketHandler.cs
Intersect.Server.Core/Networking/PacketSender.cs

fix(2190): take into account GridX/Y and camera holds for map cache

---

Intersect.Server.Core/Entities/Entity.cs
Intersect.Server.Core/Entities/Npc.cs
Intersect.Server.Core/Entities/Player.cs
Intersect.Server.Core/Entities/ProjectileSpawn.cs
Intersect.Server.Core/Entities/Resource.cs
Intersect.Server.Core/Maps/MapInstance.cs

Resolves #743
I wasn't able to reproduce the bug myself, but from Weylon's reproduction scenario comment I only see one way to reproduce this, and this change _should_ fix it:
Weylon's comment:
> to reproduce the npc must cast a spell the moment you die

fix(743): Reset player after warping to new map to prevent getting hit by a new effect while mid-respawn

---

Framework/Intersect.Framework.Core/Config/MapOptions.cs
Framework/Intersect.Framework.Core/GameObjects/Maps/GameBorderStyle.cs
Intersect.Client.Core/Core/Graphics.cs
Intersect.Server.Core/Maps/MapController.cs

- Change `GameBorderStyle` to an enum for clarity of what the different values do
- Serialize `GameBorderStyle` as a string (this option in the config is forward-compatible and automatically migrated from int to string)
- lock map to center camera if the display resolution exceeds map size for `GameBorderStyle.Seamed`

chore/fix/feat: change GameBorderStyle into an enum, maked Seamed have effect at high resolution

---

Framework/Intersect.Framework.Core/Config/Options.cs
Intersect (Core)/Network/Packets/Server/EntityDashPacket.cs
Intersect.Client.Core/Entities/Dash.cs
Intersect.Client.Core/Networking/PacketHandler.cs
Intersect.Server.Core/Entities/Combat/Dash.cs
Intersect.Server.Core/Networking/PacketSender.cs

fix(982): expire dashes based on end time in case packets are delayed

---

Intersect.Client.Core/Interface/Game/Admin/AdminWindow.cs

fix: Null safety in AdminWindow, clean up all of the warnings

---

Framework/Intersect.Framework.Core/Color.cs
Framework/Intersect.Framework.Core/Core/IApplicationContext.cs
Framework/Intersect.Framework/Reflection/AssemblyExtensions.cs
Framework/Intersect.Framework/StringExtensions.cs
Intersect.Client.Core/Core/Bootstrapper.cs
Intersect.Client.Core/Core/ClientCommandLineOptions.cs
Intersect.Client.Core/Core/ClientContext.cs
Intersect.Client.Core/Interface/Game/EscapeMenu.cs
Intersect.Client.Core/Interface/Menu/MenuGuiBase.cs
Intersect.Client.Core/Interface/Shared/VersionLabel.cs
Intersect.Client.Core/Interface/Shared/VersionPanel.cs
Intersect.Client.Core/MonoGame/Network/MonoSocket.cs
Intersect.Client.Framework/Gwen/Control/Base.cs
Intersect.Client.Framework/Gwen/Control/ILabel.cs
Intersect.Client.Framework/Gwen/Control/ITextContainer.cs
Intersect.Client.Framework/Gwen/Control/Label.cs
Intersect.Client.Framework/Gwen/Control/Panel.cs
Intersect.Client.Framework/Gwen/ControlInternal/Text.cs
Intersect.Client.Framework/Gwen/Renderer/IntersectRenderer.cs
Intersect.Client.Framework/Gwen/Skin/Base.cs
Intersect.Network/ClientNetwork.cs

- add `IsDeveloper` to the application context, this is true when the client host is non-public or failed to be resolved and false in all other cases
- Version indicator is shown in bottom left corner of main menu
- Version indicator is shown in bottom left corner of in-game escape menu (not including the simplified menu)
- make version label copy version string to clipboard on click

feat: engine version indicator

---

Intersect.Client.Framework/Gwen/Control/ComboBox.cs

(most easily reproducible by clicking another combobox like Resolution -> FPS in settings)

fix black text on combobox when losing keyboard focus

---

Intersect.Client.Framework/Gwen/Control/ImagePanel.cs

Update texture name to avoid EnsureTextureLoaded() reloading the nulled-out texture #2561

---

Intersect.Client.Core/Interface/Shared/SettingsWindow.cs
Intersect.Client.Framework/Gwen/Control/Base.cs
Intersect.Client.Framework/Gwen/Control/LabeledSlider.cs
Intersect.Client.Framework/Gwen/Control/ValueChangeHandler.cs

add a hook to re-update the window state #2563

---

Intersect.Client.Core/Interface/Debugging/DebugWindow.cs
Intersect.Client.Core/Localization/Strings.cs
Intersect.Client.Core/MonoGame/Graphics/MonoRenderer.cs
Intersect.Client.Core/MonoGame/NativeInterop/OpenGL/GL.ATI_meminfo.cs
Intersect.Client.Core/MonoGame/NativeInterop/OpenGL/GL.Extensions.cs
Intersect.Client.Core/MonoGame/NativeInterop/OpenGL/GL.Memory.cs
Intersect.Client.Core/MonoGame/NativeInterop/OpenGL/GL.NVX_gpu_memory_info.cs
Intersect.Client.Core/MonoGame/NativeInterop/OpenGL/GL.cs
Intersect.Client.Core/MonoGame/NativeInterop/OpenGL/GLenum.cs
Intersect.Client.Core/MonoGame/NativeInterop/OpenGL/Gl.Helpers.cs
Intersect.Client.Core/MonoGame/NativeInterop/OpenGL/Gl.glGet.cs
Intersect.Client.Core/MonoGame/NativeInterop/Sdl2.GL.cs
Intersect.Tests.Client/Intersect.Tests.Client.csproj
Intersect.Tests.Client/Localization/StringsTests.cs
Intersect.Tests.Client/Stub.cs
Intersect.sln.DotSettings

The underlying API calls added in this are needed to properly implement #450 with #2453

Add VRAM stats to debug window

---

Framework/Intersect.Framework.Core/Color.cs
Intersect.Client.Core/Interface/Game/EventWindow.cs
Intersect.Client.Core/Interface/Game/Typewriting/Typewriter.cs
Intersect.Client.Core/Utilities/TextColorParser.cs
Intersect.Client.Framework/Gwen/Control/RichLabel.cs

This PR introduces `TextColorParser`, enabling **colorized text support** in the event window. It allows uers to specify text colors using:
- **Known colors** (e.g., `\c{red}Red text\c{}`)
- **Hex color codes** (e.g., `\c{#87CEEB}Hexcooode text\c{}`)
```plaintext
None of the above. \c{red}Red text\c{} next text \c{#87CEEB}Hexcooode text\c{} \c{red}Red text\c{}
```

feat: Add TextColorParser for colorized text support in event window

---

Intersect.Client.Core/Interface/Game/EventWindow.cs

add ForceImmediateRebuild() back to properly compute prompt label height for long text

---

Intersect.Client.Core/Core/Input.cs
Intersect.Client.Core/Interface/Shared/SettingsWindow.cs
Intersect.Client.Core/Localization/Strings.cs
Intersect.Client.Core/MonoGame/Input/MonoInput.cs
Intersect.Client.Framework/Database/GameDatabase.cs

This PR introduces mouse scroll functionality for zooming in and out of the game world.

feat: adapt ca85609 from MAO for the base engine

---

Intersect.Client.Core/Interface/Menu/SelectCharacterWindow.cs

resolves #2604 
UpdateDisplay() is called before EnsureEnsureInitialized()
Update display hides the arrows, when the condition is true, EnsureEnsureInitialized loads the json value which is false, so the arrows appear when they shouldn't

fix: select character arrow visibility

---

Intersect.Client.Core/Interface/Game/TargetContextMenu.cs

fix crash when open target context menu

---

Intersect.Client.Core/Interface/Game/Hotbar/HotBar.cs

hotbar size to contents before loading json to prevent ProcessAlignments() from screwing up the positioning #2619

---

Intersect.Client.Core/Interface/Game/GameInterface.cs
Intersect.Client.Core/Interface/Game/Shop/ShopItem.cs
Intersect.Client.Core/Interface/Game/Shop/ShopWindow.cs
Intersect.Client.Core/Localization/Strings.cs
Intersect.Client.Framework/Gwen/Control/Base.cs
Intersect.Client.Framework/Gwen/Control/ImagePanel.cs
Intersect.Client.Framework/Gwen/Control/Menu.cs
Intersect.Client.Framework/Gwen/ControlInternal/Dragger.cs
Intersect.Client.Framework/Gwen/ControlInternal/ScrollBarBar.cs

resolves #2558 
assets in https://github.com/AscensionGameDev/Intersect-Assets/pull/62
Shop Window inherits from Window
ShopItem inheriting from image
code reduction and cleaning in general
Functions delegated correctly now:
- The Window only serves as a container, with no context logic when right-clicking on the shop item
- Shop item dealing with the context menu, since it is the one that is clicked and not the window as before
I recommend looking at the files directly in the ide, github is showing everything strange
working as it should so far
https://github.com/user-attachments/assets/0002f4ca-7fc0-4021-9d52-b4af433cbcf8

cleanup shop window/item

---

Intersect.Client.Core/Interface/Game/GameInterface.cs
Intersect.Client.Core/Interface/Game/Inventory/InventoryItem.cs
Intersect.Client.Core/Interface/Game/Inventory/InventoryWindow.cs
Intersect.Client.Core/Interface/Game/MenuContainer.cs
Intersect.Client.Core/Interface/Game/Shop/ShopItem.cs

assets - https://github.com/AscensionGameDev/Intersect-Assets/pull/63

cleanup inventory window/item

---

Intersect.Client.Core/Core/Input.cs
Intersect.Client.Core/Interface/Menu/SelectCharacterWindow.cs
Intersect.Client.Framework/Gwen/Control/Base.cs
Intersect.Client.Framework/Gwen/Control/Button.cs
Intersect.Client.Framework/Gwen/Control/TextBox.cs
Intersect.Client.Framework/Gwen/Input/InputHandler.cs
Intersect.Client.Framework/Gwen/Input/IntersectInput.cs

process virtual clicks instead of using a control override

---

Intersect.Client.Core/Interface/Game/Bag/BagItem.cs
Intersect.Client.Core/Interface/Game/Bank/BankItem.cs
Intersect.Client.Core/Interface/Game/Inventory/InventoryItem.cs
Intersect.Client.Core/Interface/Game/Inventory/InventoryWindow.cs
Intersect.Client.Core/Interface/Game/Shop/ShopItem.cs
Intersect.Client.Core/Interface/Game/Shop/ShopWindow.cs
Intersect.Client.Core/Interface/Game/SlotItem.cs
Intersect.Client.Core/Utilities/PopulateSlotContainer.cs

This pr intends to unify the "Items" files under the same class, and in addition, it adds a PopulateSlotContainer to reduce the repeated code that exists in several "Windows" files.
assets - https://github.com/AscensionGameDev/Intersect-Assets/pull/64

unify items

---

Intersect.Server.Core/General/Formulas.cs

resolves #2647 
I tested without modifying anything in the default formulas file, everything is ok
then I tested it with this formula here
`"PhysicalDamage": "(BaseDamage + A_Level + (ScalingStat * ScaleFactor) * CritMultiplier) * (100 / ((100 + V_Defense) * V_Level))",`
https://github.com/user-attachments/assets/5cbf5470-7a4c-459f-a2dc-e9224728d414

reference attacker/victim level in combat formula

---

Intersect.Client.Core/MonoGame/Input/MonoInput.cs
Intersect.Client.Framework/Input/GameInput.cs
Intersect.Client.Framework/Input/InputDeviceType.cs

Resolves https://github.com/AscensionGameDev/Intersect-Engine/issues/2605
- Implemented tracking of the last input device (mouse or controller).
- Ensured that the cursor only moves if the last input was from a controller.

fix: Fixed cursor warping when sending chat messages

---

Intersect.Client.Core/Interface/Game/Bag/BagItem.cs
Intersect.Client.Core/Interface/Game/MenuContainer.cs
Intersect.Client.Core/Interface/Game/Spells/SpellItem.cs
Intersect.Client.Core/Interface/Game/Spells/SpellsWindow.cs

assets https://github.com/AscensionGameDev/Intersect-Assets/pull/67
https://github.com/user-attachments/assets/ac9dbd70-6c66-4005-bb53-fc76212a2a18

refactor spells window/item

---

Framework/Intersect.Framework.Core/GameObjects/Resources/ResourceDescriptor.cs
Framework/Intersect.Framework.Core/GameObjects/Resources/ResourceGraphicType.cs
Framework/Intersect.Framework.Core/GameObjects/Resources/ResourceStateDescriptor.cs
Framework/Intersect.Framework.Core/GameObjects/Resources/ResourceTextureSource.cs
Intersect.Client.Core/Entities/Resource.cs
Intersect.Client.Core/Maps/MapInstance.cs
Intersect.Client.Core/Networking/PacketHandler.cs
Intersect.Client.Framework/Entities/IResource.cs
Intersect.Editor/Core/Graphics.cs
Intersect.Editor/Core/Main.cs
Intersect.Editor/Forms/Editors/frmResource.Designer.cs
Intersect.Editor/Forms/Editors/frmResource.cs
Intersect.Editor/Forms/Editors/frmResource.resx
Intersect.Editor/Localization/Strings.cs
Intersect.Server.Core/Database/DbInterface.cs
Intersect.Server.Core/Entities/Entity.cs
Intersect.Server.Core/Entities/Resource.cs
Intersect.Server.Core/Migrations/Sqlite/Game/20250326125418_ResourceStates.Designer.cs
Intersect.Server.Core/Migrations/Sqlite/Game/20250326125418_ResourceStates.cs
Intersect.Server/Migrations/MySql/Game/20250326125350_ResourceStates.Designer.cs
Intersect.Server/Migrations/MySql/Game/20250326125350_ResourceStates.cs
Intersect.Server/Migrations/MySql/Game/MySqlGameContextModelSnapshot.cs

resolves #2686 | #1767
This feature aims to add custom states to resources based on their life.
works like in videos, and also supports animated resources
The only detail to pay attention to is that it will be considered a "dead state" when the maxhp of the state is 0%
if there is no state that fits the min-max hp percentages, nothing will be rendered
The current resources that already exist in the old model are migrated correctly (as far as testing) and already serve as a model for everyone who already has resources to understand how the system works.
resource rendering can be based on the resource's maximum lifetime or the resource object's maximum lifetime, which can provide a more dynamic mapping, but that is not the intent of this feature. …

feat: added reasources states based on resource health

---

Intersect.Server.Core/Entities/Npc.cs

NPCs now wander longer paths using randomized walk  ranges based on their sight distance, with smoother direction changes and better obstacle handling. MoveRandomly has been refactored as a method for better organization.
Preview:
https://github.com/user-attachments/assets/e54504bb-cb85-4c4e-aac0-432ae468ad07

enhancement: NPC random movement with walk ranges

---

Intersect.Client.Core/Interface/Game/Character/CharacterWindow.cs
Intersect.Client.Core/Interface/Game/Character/EquipmentItem.cs
Intersect.Client.Core/Localization/Strings.cs

- Simplifies extra buff labels into a button ("Details") with a tooltip containing all the info.
- Partially solves #2554 - we still need to rework party, friends and guild windows.
- Important: [check and merge Assets PR first](https://github.com/AscensionGameDev/Intersect-Assets/pull/70)
Preview:

enhancement: updates character window and quest log
