Intersect.Server/Core/ServerContext.cs
=> Add additional logging to diagnose the real cause of #80

Intersect (Core)/Network/AbstractNetwork.cs, Intersect (Core)/Network/NetworkStatus.cs, Intersect.Editor/Forms/frmLogin.cs, Intersect.Editor/Forms/frmMain.cs, Intersect.Network/LidgrenInterface.cs
Fixes disconnection handling bugs reported in #84 due to #78
=> Tweaks to handle disconnects and connection timeouts properly

Intersect.Server/Entities/Player.cs, Intersect.Server/Networking/PacketHandler.cs
=> This fixes #71 and does a little code cleanup on the attack packet handler

Intersect (Core)/Crypto/RsaUtils.cs, Intersect (Core)/GameObjects/Events/EventMoveRoute.cs, Intersect (Core)/GameObjects/Maps/MapAttribute.cs, Intersect (Core)/Intersect (Core).csproj, Intersect (Core)/Logging/Formatting/DefaultFormatter.cs, Intersect (Core)/Network/CerasPacket.cs, Intersect.Client.Framework/File Management/GameContentManager.cs, Intersect.Client.Framework/GenericClasses/OpenFileDialog.cs, Intersect.Client.Framework/GenericClasses/SaveFileDialog.cs, Intersect.Client.Framework/Gwen/Control/Base.cs, Intersect.Client.Framework/Gwen/Renderer/Base.cs, Intersect.Client.Framework/Gwen/Skin/Base.cs, Intersect.Client/Interface/Game/Draggable.cs, Intersect.Client/Items/Item.cs, Intersect.Client/MonoGame/Graphics/MonoTileBuffer.cs, Intersect.Client/MonoGame/Network/MonoSocket.cs, Intersect.Network/ClientNetwork.cs, Intersect.Network/Intersect.Network.csproj, Intersect.Network/Lidgren/LidgrenBuffer.cs, Intersect.Network/Lidgren/LidgrenConnection.cs, Intersect.Network/Lidgren/LidgrenInterface.cs, Intersect.Server/Database/GameData/Migrations/Beta6Migration.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Networking/Helpers/PortChecker.cs, Intersect.Server/Networking/Lidgren/ServerNetwork.cs, Intersect.Server/Web/RestApi/Attributes/ConfigurableAuthorizeAttribute.cs
Cleans up:
- an empty class
- empty constructors
- empty destructors
- empty catch clauses
- empty statements (`;`)
=> chore - Cleanup an empty issues

Intersect (Core)/Intersect (Core).csproj, Intersect (Core)/Utilities/Randomization.cs, Intersect.Server/Database/Item.cs, Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/Events/CommandProcessing.cs, Intersect.Server/Entities/Events/EventPageInstance.cs, Intersect.Server/Entities/Npc.cs, Intersect.Server/Entities/Resource.cs, Intersect.Server/General/Formulas.cs, Intersect.Server/General/Globals.cs, Intersect.Server/General/Time.cs, Intersect.Server/Maps/MapInstance.cs, Intersect.Server/Notifications/ResetPassword.cs
Part of #96, does not resolve it completely.
=> 96: Remove Globals.Rand

Intersect.Server/Maps/MapInstance.cs, Intersect.Server/Networking/PacketSender.cs
=> Fixing deadlocks and simplifying code by using concurrent collections

Intersect.Server/Entities/Player.cs, Intersect.Server/Localization/Strings.cs
Fix for https://github.com/AscensionGameDev/Intersect-Engine/issues/117
Don't allow bound items in tradewindow
=> fix for #117

Intersect.Client/Intersect.Client.csproj, Intersect.Client/Localization/Strings.cs, Intersect.Client/MonoGame/File Management/MonoContentManager.cs, Intersect.Client/MonoGame/IntersectGame.cs, Intersect.Client/Program.cs
=> Removing client windows forms

Intersect.Server/Database/DbInterface.cs, Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/Pathfinding/Pathfinder.cs, Intersect.Server/Maps/MapGrid.cs, Intersect.Server/Maps/TileHelper.cs, Intersect.Server/Networking/PacketHandler.cs, Intersect.Server/Networking/PacketSender.cs
This also refactors a lot of not so good code and terrible code wrapping.
Resolves #130
=> Fixes pathfinding, map packets from crashing while maps are being saved.

Intersect.Server/Database/DbInterface.cs, Intersect.Server/Database/PlayerData/User.cs
=> Fixing username lookups not being case insensitive.

Intersect.Server/Entities/Player.cs
=> Actually makes party xp range and common event options work

Intersect.Server/Networking/PacketHandler.cs
Adds locks to the ServerLoop.Lock when executing the following:
-- Adding Maps
-- Removing Maps
-- Linking Maps
-- Unlinking Maps
I added these changes directly into the Celtos source a week or so ago while trying to fix their instability,
Prevents multiple scenarios where the mapgrids are being changed during the server loop resulting in various errors. I also believe this fixes a deadlock scenario but I don't recall exactly what that was.
=> Lock server loop when editor is making changes to maps/map grids.

Intersect.Server/Networking/PacketHandler.cs
This fixes crashes when trying to edit games while there are many players online with active npcs needing access to the map grid(s).
=> Lock server loop when editor is making changes to maps/map grids. (#163)

Intersect.Client/Entities/Entity.cs
=> Removes animations from entities animation list once disposed

Intersect.Client/Networking/PacketHandler.cs, Intersect.Server/Entities/Entity.cs, Intersect.Server/Networking/PacketSender.cs
=> Fixing ghost players 160

Intersect.Editor/Forms/Editors/Quest/frmQuest.cs
=> 216: Fix NRE in Quest Editor

Intersect.Editor/Forms/DockingElements/frmMapEditor.cs, Intersect.Editor/Forms/DockingElements/frmMapLayers.cs
=> 215: Fix stack overflow in SmartFillAttribute

Intersect.Server/Entities/Player.cs
Resolves #237 
Fixes an issue where overflowing items on a full inventory would still attempt to cram an item (or multiple) into the inventory.
=> Fixes an issue with item overflow

Intersect.Server/Database/DbInterface.cs, Intersect.Server/Database/Item.cs, Intersect.Server/Database/PlayerData/Players/Bag.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Networking/PacketHandler.cs
=> fix 191: Bag access is done via cached value

Intersect.Editor/Forms/Editors/Events/CommandPrinter.cs
Add additional logging information for #257
=> Add additional logging information for #257

Intersect.Client/General/Globals.cs, Intersect.Client/Interface/Game/GameInterface.cs, Intersect.Client/Interface/Game/Inventory/InventoryWindow.cs, Intersect.Client/Interface/Game/Menu.cs, Intersect.Server/Entities/Player.cs
=> Make Inventory window unclosable when Bag/Shop/Trade/Craft/Bank open

Intersect.Server/Entities/Entity.cs
=> fix 284: Do not use Add() for cooldowns

Intersect.Server/Database/DbInterface.cs
=> fix 274: remove cause of NRE

Intersect (Core)/Updater/Updater.cs, Intersect.Editor/Localization/Strings.cs
=> fix 267: download data as utf8 to prevent corruption

Intersect.Editor/Forms/frmMain.cs
=> Fix Update Generation case mismatch

Intersect.Client/Intersect.Client.csproj, Intersect.Client/MonoGame/File Management/MonoContentManager.cs, Intersect.Client/Program.cs
=> Fixes client launch support on Linux

Intersect.Editor/Forms/frmMain.cs
=> Fixes the broken bug tracker url within the editor.

AUTHORS.md
This should have been done with their first PR, oversight on our part.
=> Adding Wishy to AUTHORS.md

Intersect (Core)/Config/Options.cs, Intersect.Network/Lidgren/LidgrenInterface.cs, Intersect.Server/Localization/Strings.cs, Intersect.Server/Networking/PacketHandler.cs
=> Add a connection and logged in user cap.

AUTHORS.md, Intersect.Client.Framework/Gwen/Control/Base.cs, Intersect.Client.Framework/Gwen/Control/Canvas.cs, Intersect.Client.Framework/Gwen/Control/ScrollControl.cs, Intersect.Client.Framework/Gwen/Input/InputHandler.cs, Intersect.Client.Framework/Gwen/Input/IntersectInput.cs, Intersect.Client/MonoGame/Input/MonoInput.cs
Code is entirely taken from TDog's code over at: https://www.ascensiongamedev.com/topic/5267-kash-shop-mouse-scroll/
So all credit to him, it was never turned into a PR and we've gotten permission to use it in the base engine. 👍 https://www.ascensiongamedev.com/topic/5526-kash-shop-flash-sale-20/?tab=comments#comment-48414
=> Add mouse scroll support to scrollbars.

Intersect.Client.Framework/Gwen/Platform/Neutral.cs, Intersect.Client.Framework/Input/GameClipboard.cs, Intersect.Client.Framework/Intersect.Client.Framework.csproj, Intersect.Client/Interface/Game/Chat/Chatbox.cs, Intersect.Client/Intersect.Client.csproj, Intersect.Client/MonoGame/Input/MonoClipboard.cs, Intersect.Client/MonoGame/IntersectGame.cs
=> Abstracting monogame clipboard

Intersect.Client/Interface/Game/PartyWindow.cs
=> Update party window based on maximum party members from config

Intersect.Server/Entities/Player.cs
Resolves #247 
Thanks to @rhathaway86 for the fix provided within the issue.
=> Fixes player bump event activations by checking the proper map

Intersect.Client/Entities/Entity.cs, Intersect.Client/Networking/PacketHandler.cs
=> Resolving 301 by not trying to calculate npc attack times!

Intersect.Client/Core/Input.cs
=> Modifies input logic so left mouse can be used for hotbar/other actions

Intersect (Core)/GameObjects/Events/Commands/EventCommands.cs
=> Fix copying and pasting of input variable commands.

Intersect (Core)/GameObjects/Events/Condition.cs, Intersect.Editor/Forms/Editors/Events/CommandPrinter.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.Designer.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Events/CommandProcessing.cs
resolves #360 
I realised I based this off of pre-release a bit late. Can change if need be?
=> Make Conditional Branch else optional

Intersect.Server/Entities/Npc.cs
=> Fix taunt and DoTs not functioning with resetting Npcs

Intersect (Core)/GameObjects/Maps/MapAttribute.cs, Intersect.Client/Entities/Player.cs, Intersect.Editor/Forms/DockingElements/frmMapLayers.Designer.cs, Intersect.Editor/Forms/DockingElements/frmMapLayers.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/Projectile.cs, Intersect.Server/Maps/MapInstance.cs
=> Add option for map animations to be considered blocks

Intersect.Client.Framework/Graphics/GameRenderer.cs, Intersect.Client/MonoGame/Audio/MonoMusicSource.cs, Intersect.Client/MonoGame/Audio/MonoSoundSource.cs, Intersect.Client/MonoGame/File Management/MonoContentManager.cs, Intersect.Client/MonoGame/Graphics/MonoRenderer.cs, Intersect.Client/MonoGame/Graphics/MonoTexture.cs
Temporary until Beta 7 is ready for showtime. Resolves #370
=> Pass real filenames to content classes for proper loading on Linux/Mac

Intersect.Client/MonoGame/IntersectGame.cs
=> Fixes window sizing in Linux while updating.

Intersect.Editor/Core/Graphics.cs
Oopsie, thanks @jcsnider for noticing that!
=> Fix NRE with removed/unreleased assets on map editor event previews

Intersect (Core)/Config/PacketOptions.cs, Intersect.Client/Core/Input.cs, Intersect.Client/Core/Main.cs, Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/General/Globals.cs, Intersect.Client/Networking/PacketHandler.cs, Intersect.Server/Networking/Client.cs, Intersect.Server/Networking/PacketHandler.cs
=> Fixing desync sensitivity

Intersect.Server/Entities/Entity.cs, Intersect.Server/Maps/MapInstance.cs
=> Fix entities able to walk on resources after respawning and resources respawning with Npcs and Players on them.

Intersect.Server/Entities/Entity.cs
=> Don't send cooldown to npcs! (Fixes 395)

Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Events/Event.cs
=> Force WorldPos height/width to the Tile Size when no graphic is available

Intersect.Server/Admin/Actions/ActionProcessing.cs, Intersect.Server/Database/ContextInterface.cs, Intersect.Server/Database/ContextProvider.Locking.cs, Intersect.Server/Database/ContextProvider.cs, Intersect.Server/Database/DbInterface.cs, Intersect.Server/Database/GameData/GameContext.cs, Intersect.Server/Database/GameData/IGameContext.cs, Intersect.Server/Database/IDbContext.cs, Intersect.Server/Database/IntersectDbContext.cs, Intersect.Server/Database/Logging/Entities/UserActivityHistory.cs, Intersect.Server/Database/Logging/ILoggingContext.cs, Intersect.Server/Database/Logging/LoggingContext.cs, Intersect.Server/Database/PlayerData/IPlayerContext.cs, Intersect.Server/Database/PlayerData/PlayerContext.cs, Intersect.Server/Intersect.Server.csproj, Intersect.Server/Migrations/Logging/20201119230003_AddUserActivityHistory.Designer.cs, Intersect.Server/Migrations/Logging/20201119230003_AddUserActivityHistory.cs, Intersect.Server/Networking/PacketHandler.cs, Intersect.Server/Networking/PacketSender.cs
Note that this isn't _totally_ complete, as not all of the user actions are represented in the DB, and some things like Quit to Desktop do not get reported.
Will open a separate issue (or issues) to expand upon it, but this was meant more to be a framework base and example for other logging features to get added.
=> feat(logging-db): add logging db with user action history

Intersect.Building/Intersect.Building.csproj, Intersect.Client.Framework/Intersect.Client.Framework.csproj, Intersect.Client/Intersect.Client.csproj, Intersect.Client/Program.cs, Intersect.Network/Intersect.Network.csproj, Intersect.Server/Intersect.Server.csproj, Intersect.Tests.Editor/Intersect.Tests.Editor.csproj, targets/Intersect.Building.KeyGeneration.msbuild, targets/Intersect.targets
=> fix(building): fix build on linux using msbuild/monodevelop

Intersect.Client/Interface/Menu/SelectCharacterWindow.cs
=> Force waiting for a server response upon selecting a character.

Intersect.Server/Database/ContextProvider.cs, Intersect.Server/Intersect.Server.csproj
=> fix: server build on linux, context interface lookup

Intersect.Client/Interface/Menu/CreateCharacterWindow.cs, Intersect.Client/Interface/Menu/ForgotPasswordWindow.cs, Intersect.Client/Interface/Menu/LoginWindow.cs, Intersect.Client/Interface/Menu/RegisterWindow.cs, Intersect.Client/Interface/Menu/SelectCharacterWindow.cs
Expand changes made in #436 to similar menus
=> Expand changes made in #436 to similar menus

AUTHORS.md, Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Events/Event.cs, Intersect.Client/Interface/Menu/CreateCharacterWindow.cs, Intersect.Client/Interface/Menu/ForgotPasswordWindow.cs, Intersect.Client/Interface/Menu/LoginWindow.cs, Intersect.Client/Interface/Menu/RegisterWindow.cs, Intersect.Client/Interface/Menu/SelectCharacterWindow.cs, Intersect.Network/Intersect.Network.csproj, Intersect.Server/Entities/Entity.cs
* Don't send cooldown to npcs!
* Bad logic is bad.
* Update Authors.md link to my profile
* Force WorldPos height/width to the Tile Size when no graphic is available
* Force waiting for a server response upon selecting a character.
* Disable the button and re-enable it when no longer waiting for a server response.
* Changes batch 1
* Changes batch 2
* Also disable logout button while waiting for a server response.
* Fix some comment mishaps.
* Do not generate keys on every build
Co-authored-by: Cheshire <azurebeats@hotmail.nl>
Co-authored-by: Robert Lodico <lodico.rj@gmail.com>
=> Merging 6.2 fixes into B7 (#461)

Intersect (Core)/Config/CombatOptions.cs, Intersect (Core)/GameObjects/Maps/MapBase.cs, Intersect (Core)/Intersect (Core).csproj, Intersect (Core)/Network/Packets/Server/CancelCastPacket.cs, Intersect.Client/Core/Graphics.cs, Intersect.Client/Maps/MapAnimation.cs, Intersect.Client/Maps/MapInstance.cs, Intersect.Client/Networking/PacketHandler.cs, Intersect.Server/Entities/Combat/Buff.cs, Intersect.Server/Entities/Combat/DoT.cs, Intersect.Server/Entities/Combat/Stat.cs, Intersect.Server/Entities/Combat/Status.cs, Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/Events/EventPageInstance.cs, Intersect.Server/Entities/Npc.cs, Intersect.Server/Entities/Pathfinding/Pathfinder.cs, Intersect.Server/Entities/Pathfinding/SpatialAStar.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Entities/Projectile.cs, Intersect.Server/Entities/ProjectileSpawn.cs, Intersect.Server/Entities/Resource.cs, Intersect.Server/Intersect.Server.csproj, Intersect.Server/Maps/MapInstance.cs, Intersect.Server/Maps/MapTrapInstance.cs, Intersect.Server/Networking/Helpers/NetDebug.cs, Intersect.Server/Networking/PacketHandler.cs, Intersect.Server/Networking/PacketSender.cs
Using more concurrent dictionaries with cached arrays for quicker/threadsafe access.
Stat Calc Fixes
Npc Logic Updates
Disabling Combat Messages
Hotbar Auto Cast if Held Down
=> Combat, NPC Logic (Loot Maps!) and Threading Updates

Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ChangeItems.cs
=> Fixes variable selection in the event change items menu

Intersect.Server/Networking/PacketHandler.cs, Intersect.Server/Networking/PacketSender.cs
Also cleans up caching of game data packet.
Fixes half of #491
=> Fixes editors not being sent entire set of game content

Intersect.Editor/Forms/Editors/frmSpell.cs
=> Fix cooldown group in editor not updating for selected spells

Intersect (Core)/GameObjects/Events/Commands/EventCommands.cs, Intersect.Editor/Forms/Editors/Events/CommandPrinter.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_EquipItem.Designer.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_EquipItem.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.Designer.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Events/CommandProcessing.cs, Intersect.Server/Entities/Player.cs
=> Allow unequipping items via events

Intersect.Server/Entities/Events/CommandProcessing.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Networking/PacketSender.cs
Resolves #501 -- mostly. Might loop back around and do this check at various intervals but this is a good start.
=> Auto unequip items that are not equipment, or items we no longer meet conditions for

Intersect (Core)/Intersect (Core).csproj, Intersect (Core)/Network/Packets/Server/MapEntityStatusPacket.cs, Intersect (Core)/Network/Packets/Server/MapEntityVitalsPacket.cs, Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs, Intersect.Client/Networking/PacketHandler.cs, Intersect.Server/Entities/Combat/Status.cs, Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/Npc.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Entities/Resource.cs, Intersect.Server/Maps/MapInstance.cs, Intersect.Server/Networking/PacketSender.cs
Fixes #497 
This code/logic was written by @Cheshire92 for Leafling. (Credit where credit is due.)
=> Send vital/status updates each map update instead of on demand

Intersect.Server/Entities/Resource.cs
=> Play resource death animations again

Intersect.Editor/Forms/DockingElements/frmMapEditor.cs, Intersect.Editor/Forms/DockingElements/frmMapLayers.cs
=> Cleanup droppler code and fix map layer selections

Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_GiveExperience.cs
=> Fix give experience command editor saving incorrect variable id

Intersect.Client/Interface/Game/MapItem/MapItemIcon.cs
=> Loot window item rendering with proper item colors

Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
=> Fix entity level label not having it's value set.

Intersect.Client/Entities/Animation.cs, Intersect.Editor/Forms/Editors/frmAnimation.cs
=> Fix animation rendering so that if improper frame counts are provided it cannot render out of bounds

Intersect (Core)/GameObjects/TimeBase.cs
=> Fixes time editor losing new values

Intersect.Editor/Forms/Editors/frmClass.cs
=> Fix 515 by not resetting warp/map combobox values initializing editor

Intersect.Server/Entities/Player.cs, Intersect.Server/Maps/MapInstance.cs
=> Fix item/stat issues

AUTHORS.md, README.md
Updated the source code compilation information (which was outdated, VS 2017 isn't capable to build the current solution anymore).
The URL linked to the "Getting Started" documentation has been updated as well.
=> Updated README.md

Intersect.Server/Entities/Entity.cs, Intersect.Server/Maps/MapInstance.cs
=> Stops dead entities from switching maps, and stops knocking back dead entities

Intersect.Server/Entities/Player.cs
=> Show target out of range errors (if configured) on warp to spells

Intersect.Server/Entities/Entity.cs
And some status updates not sending at all (time updates/refreshes)
Should partially or fully resolve #520
=> Fix vital/status updates sending every loop for every entity

Intersect.Client/Interface/Shared/OptionsWindow.cs
Also reduces control setting time to 3 seconds before being set to None.. 5 seconds felt way too long.
Resolves #485
=> Fix control mappings so the same key cannot be mapped for multiple controls

Intersect.Client.Framework/Database/GameDatabase.cs
=> Fixes 551 by enabling the sticky target preference by default

Intersect.Server/Entities/Entity.cs
=> Fix invulnerability by only blocking damage (instead of damage and healing)

Intersect.Client/Entities/Entity.cs
=> Fix animated sprites by calculating which frames to render after setting the animation types

Intersect.Client/Interface/Game/EscapeMenu.cs, Intersect.Server/Database/PlayerData/User.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Localization/Strings.cs, Intersect.Server/Networking/Client.cs, Intersect.Server/Networking/PacketHandler.cs
=> Fix server crashes due to deleting characters that remain online and in combat

Intersect.Server/Entities/Pathfinding/SpatialAStar.cs
=> Pathfinding - Return the path to the closest point found when unable to reach target.

Intersect.Server/Entities/Player.cs
=> Send quest progress upon quest completion via event.

Intersect.Client/Interface/Game/GameInterface.cs
=> Stop events from getting stuck while changing resolutions with bank/shop/trade/crafting open

Intersect.Client/Interface/Game/GameInterface.cs, Intersect.Server/Entities/Player.cs
=> Bug fixes that should be in Prerelease and not stuck in Dev

Intersect.Server/Database/DbInterface.cs, Intersect.Server/Database/PlayerData/User.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Intersect.Server.csproj, Intersect.Server/Migrations/20210414121435_TrackUserPlayerStats.Designer.cs, Intersect.Server/Migrations/20210414121435_TrackUserPlayerStats.cs, Intersect.Server/Networking/Client.cs
Track user playtime, last ip, and registration dates. Also track character playtime and creation dates.
=> Extra user/player db fields for stats/tracking

Intersect (Core)/Config/ChatOptions.cs, Intersect (Core)/Config/ProcessingOptions.cs, Intersect.Server/Database/Logging/Entities/ChatHistory.cs, Intersect.Server/Database/Logging/Entities/UserActivityHistory.cs, Intersect.Server/Database/Logging/ILoggingContext.cs, Intersect.Server/Database/Logging/LoggingContext.cs, Intersect.Server/Intersect.Server.csproj, Intersect.Server/Migrations/Logging/20210414222302_AddedChatLogging.Designer.cs, Intersect.Server/Migrations/Logging/20210414222302_AddedChatLogging.cs, Intersect.Server/Networking/PacketHandler.cs, Intersect.Server/Web/RestApi/Payloads/IpAddress.cs, Intersect.Server/Web/RestApi/Routes/V1/LogsController.cs
Resolves #110 
Credit for most of this logic goes to @march0 #481
=> Add Chat Logging & Logging Api Endpoints

Intersect.Server/Database/Item.cs
it is related but not sure if fix all the problems  for this #600
=> Fix bug for using bag, trying to store or retrive items form a bag don't work

Intersect.Server/Entities/Projectile.cs
=> Fix projectile responsiveness/delay on server processing

Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
=> Reset TargetBox when switching targets so that it updates correctly

Intersect (Core)/Enums/CommonEventTrigger.cs, Intersect (Core)/GameObjects/Events/EventPage.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.Designer.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.resx, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/Events/CommandProcessing.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Networking/PacketHandler.cs, Intersect.Server/Networking/PacketSender.cs, Intersect.Server/Web/RestApi/Routes/V1/PlayerController.cs, Intersect.Server/Web/RestApi/Routes/V1/VariablesController.cs
- On Equip/Unequip
- On Player Variable Change (specific variable selected in common event editor)
- On Server Variable Change (specific variable selected in common event editor)
Hopefully these will be used instead of Autorun for better server performance.
=> Adds new common event triggers

Intersect.Editor/Forms/Editors/Events/frmEvent.cs
=> Fix event trigger variable selection offset when reloading event editor

Intersect.Client/Entities/Projectiles/Projectile.cs
=> Do not spawn more projectiles if the spawn itself is being disposed already

Intersect.Server/Entities/Npc.cs
=> Fix npcs not resetting when pulled outside their reset radius

Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
=> Fixes exp bar not updating and showing full xp when you have 0

Intersect.Server/Entities/Player.cs
=> Fix common events not starting when the first page of conditions are not met

Intersect.Editor/Content/Texture.cs
=> Fix texture packing memory leak by not loading full MonoGame textures while calculating rects

Intersect.Server/Entities/Player.cs
=> Fixes common events with equip/unequip trigger were running when there are no changes

Intersect.Editor/Forms/Controls/GameObjectList.cs, Intersect.Editor/Forms/Editors/EditorForm.cs, Intersect.Editor/Forms/Editors/Quest/frmQuest.Designer.cs, Intersect.Editor/Forms/Editors/Quest/frmQuest.cs, Intersect.Editor/Forms/Editors/frmAnimation.Designer.cs, Intersect.Editor/Forms/Editors/frmAnimation.cs, Intersect.Editor/Forms/Editors/frmClass.Designer.cs, Intersect.Editor/Forms/Editors/frmClass.cs, Intersect.Editor/Forms/Editors/frmCommonEvent.Designer.cs, Intersect.Editor/Forms/Editors/frmCommonEvent.cs, Intersect.Editor/Forms/Editors/frmCraftingTables.Designer.cs, Intersect.Editor/Forms/Editors/frmCraftingTables.cs, Intersect.Editor/Forms/Editors/frmCrafts.Designer.cs, Intersect.Editor/Forms/Editors/frmCrafts.cs, Intersect.Editor/Forms/Editors/frmItem.Designer.cs, Intersect.Editor/Forms/Editors/frmItem.cs, Intersect.Editor/Forms/Editors/frmNpc.Designer.cs, Intersect.Editor/Forms/Editors/frmNpc.cs, Intersect.Editor/Forms/Editors/frmProjectile.Designer.cs, Intersect.Editor/Forms/Editors/frmProjectile.cs, Intersect.Editor/Forms/Editors/frmResource.Designer.cs, Intersect.Editor/Forms/Editors/frmResource.cs, Intersect.Editor/Forms/Editors/frmShop.Designer.cs, Intersect.Editor/Forms/Editors/frmShop.cs, Intersect.Editor/Forms/Editors/frmSpell.Designer.cs, Intersect.Editor/Forms/Editors/frmSpell.cs, Intersect.Editor/Forms/Editors/frmVariable.Designer.cs, Intersect.Editor/Forms/Editors/frmVariable.cs
=> Speed up editor listing and searching, also cleanup code in engine editors

Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs, Intersect.Client/Interface/Game/GameInterface.cs
=> Fix player shield bar rendering when it shouldn't and expanding incorrectly.

Intersect (Core)/GameObjects/Events/Commands/EventCommands.cs, Intersect (Core)/Intersect (Core).csproj, Intersect (Core)/Network/Packets/Client/PictureClosedPacket.cs, Intersect (Core)/Network/Packets/Server/ShowPicturePacket.cs, Intersect.Client/General/Globals.cs, Intersect.Client/Interface/Game/GameInterface.cs, Intersect.Client/Interface/Game/PictureWindow.cs, Intersect.Client/Networking/PacketHandler.cs, Intersect.Client/Networking/PacketSender.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ShowPicture.Designer.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ShowPicture.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Events/CommandInstance.cs, Intersect.Server/Entities/Events/CommandProcessing.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Networking/PacketHandler.cs, Intersect.Server/Networking/PacketSender.cs
=> Added options to wait until event pictures are closed, and auto hide after X time options as well

Intersect.Server/Database/PlayerData/Players/Guild.cs
=> Fixes ghost entities from appearing when kicking/promoting/demoting offline players in guilds

Intersect.Server/Migrations/20201017065035_AddColorToEntities.cs, Intersect.Server/Migrations/Game/20201016122614_AddItemAndNpcColors.cs
=> Fix sqlite migration by allowing color field to be null

Intersect.Client/Entities/Entity.cs
=> Hide chatbubbles when stealthed, fix character not going transparent when stealthed

Intersect.Server/Entities/BankInterface.cs
I never noticed there's two methods that let you deposit items to the bank.
Oopsie.
=> Add item bankable checks to the second TryDeposit method

Intersect (Core)/Config/ChatOptions.cs, Intersect (Core)/Config/LoggingOptions.cs, Intersect (Core)/Config/Options.cs, Intersect (Core)/Intersect (Core).csproj, Intersect.Server/Database/Logging/Entities/ChatHistory.cs, Intersect.Server/Database/Logging/Entities/TradeHistory.cs, Intersect.Server/Database/Logging/Entities/UserActivityHistory.cs, Intersect.Server/Database/Logging/ILoggingContext.cs, Intersect.Server/Database/Logging/LoggingContext.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Intersect.Server.csproj, Intersect.Server/Migrations/Logging/20210515114555_LogPlayerTrades.Designer.cs, Intersect.Server/Migrations/Logging/20210515114555_LogPlayerTrades.cs, Intersect.Server/Networking/PacketHandler.cs, Intersect.Server/Web/RestApi/Routes/V1/LogsController.cs
=> Trade logging and endpoints

Intersect.Client/Interface/Game/Menu.cs
=> Enabled ESC to Close Guild Window

Intersect (Core)/Config/Guilds/GuildOptions.cs, Intersect (Core)/Config/LoggingOptions.cs, Intersect (Core)/Utilities/FieldChecking.cs, Intersect.Server/Database/Logging/Entities/ChatHistory.cs, Intersect.Server/Database/Logging/Entities/GuildHistory.cs, Intersect.Server/Database/Logging/ILoggingContext.cs, Intersect.Server/Database/Logging/LoggingContext.cs, Intersect.Server/Database/PlayerData/Players/Guild.cs, Intersect.Server/Entities/Events/CommandProcessing.cs, Intersect.Server/Entities/Player.Database.cs, Intersect.Server/Intersect.Server.csproj, Intersect.Server/Localization/Strings.cs, Intersect.Server/Migrations/Logging/20210519095613_AddGuildActivityLogging.Designer.cs, Intersect.Server/Migrations/Logging/20210519095613_AddGuildActivityLogging.cs, Intersect.Server/Networking/PacketHandler.cs, Intersect.Server/Web/RestApi/Payloads/GuildRank.cs, Intersect.Server/Web/RestApi/Routes/V1/GuildController.cs, Intersect.Server/Web/RestApi/Routes/V1/LogsController.cs
=> Guild logging and endpoints

Intersect.Client/Core/Controls/ControlEnum.cs, Intersect.Client/Core/Controls/Controls.cs, Intersect.Client/Core/Input.cs, Intersect.Client/Interface/Game/Menu.cs, Intersect.Client/Localization/Strings.cs
Should resolve #724 
Not 100% sure on the JSON generation part but tested to work with a hand edited OptionsWindow.json
=> Hotkey for Guild Window

Intersect (Core)/Config/PlayerOptions.cs, Intersect.Server/Entities/Player.cs
=> Option to Loss Exp When Die

Intersect.Server/Networking/PacketHandler.cs
This will resolve issue #753 
Error message from a failed invite isn't showing however.
=> Guild invite fixes

Intersect (Core)/GameObjects/Events/Commands/EventCommands.cs, Intersect (Core)/GameObjects/Events/Enums.cs, Intersect.Editor/Forms/Editors/Events/CommandPrinter.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.Designer.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Events/CommandProcessing.cs
=> Reset stat point allocations event command

Intersect.Client/Maps/MapInstance.cs
=> Fixes #764 but spawning map animations based on y rendering

Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs, Intersect.Client/Localization/Strings.cs
=> Fix 753 part2

Intersect.Server/Entities/Player.cs
=> Fixed npc common events on death (for party members) not running

Intersect.Server/Entities/Player.cs
=> Fixes #759 where variable inputs failed to trigger variable changed common events

Intersect (Core)/GameObjects/ItemBase.cs, Intersect (Core)/GameObjects/ResourceBase.cs, Intersect (Core)/GameObjects/SpellBase.cs, Intersect.Editor/Forms/Editors/frmItem.Designer.cs, Intersect.Editor/Forms/Editors/frmItem.cs, Intersect.Editor/Forms/Editors/frmResource.Designer.cs, Intersect.Editor/Forms/Editors/frmResource.cs, Intersect.Editor/Forms/Editors/frmSpell.Designer.cs, Intersect.Editor/Forms/Editors/frmSpell.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Intersect.Server.csproj, Intersect.Server/Migrations/Game/20210622051409_AddingRequirementNotMetMessages.Designer.cs, Intersect.Server/Migrations/Game/20210622051409_AddingRequirementNotMetMessages.cs
Resolves #790 
New editor fields:
Shown in game:
=> Adds custom error messages when requirements are not met to use items cast spells, or harvest resources.

Intersect.Server/Entities/Events/CommandProcessing.cs
=> Fixes server crash when input variable command has no variable

Intersect.Server/Entities/Player.cs
For equipment that has changed/been removed
Resolves #801
=> Fix index out of range crash when checking equipment stats

Intersect.Client/Interface/Game/Bag/BagItem.cs, Intersect.Client/Interface/Game/Bank/BankItem.cs, Intersect.Client/Interface/Game/Draggable.cs, Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs, Intersect.Client/Interface/Game/Inventory/InventoryItem.cs, Intersect.Client/Interface/Game/Spells/SpellItem.cs, Intersect.Client/Interface/Game/Trades/TradeItem.cs
=> Fix 823 by retaining item hues when dragging

Intersect.Client/Interface/Game/GameInterface.cs
=> Fix 824 - Do not allow escape to close crafting window while crafting.

Intersect.Server/Entities/Player.cs
=> Fix 819 by not allowing the engine to give player items with quantities <= 0

Intersect.Client.Framework/Gwen/Control/Layout/Table.cs, Intersect.Client.Framework/Gwen/Control/ListBox.cs, Intersect.Client/Interface/Game/Chat/Chatbox.cs
Resolves #618 
This is a cleaner solution that I propose to resolve #618 than #809 
Fix has been confirmed by @Arufonsu with non default sized chatboxes
=> Resolve chatbox scrolling issues. (618 Alternative Fix)

Intersect.Server/Networking/PacketHandler.cs
=> Resolves 794 by allowing items to be picked up from the map even if you cannot hold the entire amount

Intersect.Client/Entities/Entity.cs
=> Fixes 817 by having client respect blocked animation attribute tiles

Intersect.Server/Entities/Events/CommandProcessing.cs, Intersect.Server/Entities/Events/Conditions.cs
=> Fixes condition negation for most conditionals.

Intersect.Editor/Forms/Editors/frmClass.Designer.cs, Intersect.Editor/Forms/Editors/frmItem.Designer.cs, Intersect.Editor/Forms/Editors/frmNpc.Designer.cs, Intersect.Editor/Forms/Editors/frmSpell.Designer.cs
=> Fix 803 by allowing crit dmg multipliers to be set to 2 decimal points in various editors

Intersect.Client/Entities/Entity.cs
=> Fix 782: Transform effects not returning back to their original sprite.

Intersect.Client/Entities/Player.cs
=> Fix 781: Targeting of steathy and event hidden players.

Intersect.Server/Networking/PacketHandler.cs
=> Fix 779: Stop players from PMing themselves.

Intersect.Client/Interface/Game/Crafting/CraftingWindow.cs, Intersect.Client/Localization/Strings.cs
Resolves #822 
Also adds a 'stop' button to stop crafts in progress.
=> Added a craft all button, resolves #822

Intersect (Core)/GameObjects/ShopBase.cs, Intersect.Editor/Forms/Editors/frmShop.Designer.cs, Intersect.Editor/Forms/Editors/frmShop.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Intersect.Server.csproj, Intersect.Server/Migrations/Game/20210703145618_AddingShopSoundEffects.Designer.cs, Intersect.Server/Migrations/Game/20210703145618_AddingShopSoundEffects.cs
=> Added buying and selling sound effects to shops

Intersect.Editor/Forms/Editors/frmCraftingTables.Designer.cs, Intersect.Editor/Forms/Editors/frmCraftingTables.cs, Intersect.Editor/Forms/Editors/frmShop.Designer.cs, Intersect.Editor/Forms/Editors/frmShop.cs, Intersect.Editor/Localization/Strings.cs
Resolves #820 
(Same for crafting table editor)
=> Shop & Crafting Table list sorting

Intersect (Core)/GameObjects/Crafting/CraftBase.cs, Intersect.Editor/Forms/Editors/frmCrafts.Designer.cs, Intersect.Editor/Forms/Editors/frmCrafts.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Intersect.Server.csproj, Intersect.Server/Migrations/Game/20210630114724_CraftingCommonEvents.Designer.cs, Intersect.Server/Migrations/Game/20210630114724_CraftingCommonEvents.cs
=> Add Common Event Triggers to Crafting Items

Intersect (Core)/Plugins/Loaders/PluginLoader.Configuration.cs
=> fix: fix plugin config initializer

Examples/Intersect.Examples.Plugin.Client.Tests/Intersect.Examples.Plugin.Client.Tests.csproj, Examples/Intersect.Examples.Plugin.Client.Tests/packages.config, Examples/Intersect.Examples.Plugin.Client/Intersect.Examples.Plugin.Client.csproj, Examples/Intersect.Examples.Plugin.Client/packages.config, Examples/Intersect.Examples.Plugin.ClientVB/Intersect.Examples.Plugin.ClientVB.vbproj, Examples/Intersect.Examples.Plugin.ClientVB/packages.config, Examples/Intersect.Examples.Plugin.Server/Intersect.Examples.Plugin.Server.csproj, Examples/Intersect.Examples.Plugin.Server/packages.config, Examples/Intersect.Examples.Plugin/Intersect.Examples.Plugin.csproj, Examples/Intersect.Examples.Plugin/packages.config, scripts/package-framework.ps1, targets/AscensionGameDev.Intersect.CommonVariables.targets
missing ; in exclusions
updated packages in Examples
improved package build script
=> fix: fix broken exclusions

Intersect (Core)/Plugins/Contexts/PluginBootstrapContext.cs, Intersect (Core)/Plugins/PluginInstance.cs, Intersect.Client.Framework/Gwen/Control/Button.cs, Intersect.Client/Intersect.Client.csproj, Intersect.Client/Plugins/Contexts/ClientPluginContext.cs, Intersect.Client/Plugins/Helpers/ClientNetworkHelper.cs, Intersect.Client/Plugins/Helpers/PluginPacketSender.cs
=> Add Click sound methods to Buttons

Intersect.Client.Framework/Graphics/GameRenderer.cs, Intersect.Client.Framework/Graphics/IGameRenderer.cs
Figured I should document these methods and clean up some of the variable names.
Might as well expose them properly if we're going to use them in plugins!
=> chore: Document IGameRenderer and cleanup

Intersect.Server/Core/LogicService.LogicThread.cs, Intersect.Server/Database/PlayerData/Players/Guild.cs, Intersect.Server/Entities/Combat/Dash.cs, Intersect.Server/Entities/Combat/DoT.cs, Intersect.Server/Entities/Combat/Status.cs, Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/Events/CommandProcessing.cs, Intersect.Server/Entities/Events/Event.cs, Intersect.Server/Entities/Events/EventPageInstance.cs, Intersect.Server/Entities/Npc.cs, Intersect.Server/Entities/Player.Database.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Entities/Projectile.cs, Intersect.Server/Entities/ProjectileSpawn.cs, Intersect.Server/General/Globals.cs, Intersect.Server/General/Time.cs, Intersect.Server/Maps/MapInstance.cs, Intersect.Server/Maps/MapTrapInstance.cs, Intersect.Server/Metrics/MetricsRoot.cs, Intersect.Server/Networking/Client.cs, Intersect.Server/Networking/PacketHandler.cs, Intersect.Server/Networking/PacketSender.cs, Intersect.Server/Web/RestApi/Routes/V1/InfoController.cs
This PR Swaps Globals.Timing for Timing.Global, as discussed in discord with @lodicolo
=> Swaps Globals.Timing for Timing.Global

Intersect (Core)/Network/Packets/Client/HotbarUpdatePacket.cs, Intersect.Client.Framework/Entities/IFriendInstance.cs, Intersect.Client.Framework/Entities/IHotbarInstance.cs, Intersect.Client.Framework/Entities/IPartyMember.cs, Intersect.Client.Framework/Entities/IPlayer.cs, Intersect.Client.Framework/Intersect.Client.Framework.csproj, Intersect.Client.Framework/Plugins/Interfaces/IClientLifecycleHelper.cs, Intersect.Client/Core/Input.cs, Intersect.Client/Entities/FriendInstance.cs, Intersect.Client/Entities/HotbarInstance.cs, Intersect.Client/Entities/PartyMember.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs, Intersect.Client/Interface/Game/Inventory/InventoryItem.cs, Intersect.Client/Intersect.Client.csproj, Intersect.Client/Maps/MapInstance.cs, Intersect.Client/Networking/PacketSender.cs, Intersect.Client/Plugins/Helpers/ClientLifecycleHelper.cs
This way we can get player specific information in plugins such as party, guild and cooldown information.
=> Create IPlayer interface to get player specific info into client plugins

Intersect (Core)/Configuration/ClientConfiguration.cs, Intersect.Client.Framework/Audio/IAudioManager.cs, Intersect.Client/Core/Audio.cs, Intersect.Client/Core/Main.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/Networking/PacketHandler.cs, Intersect.Client/Plugins/Audio/AudioManager.cs
=> Rework fade timers to be millisecond based and understandable, expose timer to client configuration

Intersect.Client.Framework/Entities/IEntity.cs, Intersect.Client.Framework/Entities/IPlayer.cs, Intersect.Client.Framework/Maps/IMapInstance.cs, Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/Intersect.Client.csproj, Intersect.Client/Maps/ActionMessage.cs, Intersect.Client/Maps/MapInstance.cs, Intersect.Client/app.config, Intersect.Client/packages.config
Replaced them with IReadOnlyList which I should have used from the start, I used it for later changes but never went back to fix the originals. Whoopsie.
This should also fix compilation issues on any system other than my own.
=> Removes Immutable collections and dependencies

Intersect (Core)/Config/PlayerOptions.cs
This PR implements changes previously discussed with @lodicolo [here](https://github.com/AscensionGameDev/Intersect-Engine/pull/928#issuecomment-910510279) and [here](https://github.com/AscensionGameDev/Intersect-Engine/pull/928#discussion_r701114988).
The title is quite self explanatory on this one.
=> Turns PlayerOptions Fields into Properties & Alphabetically re-ordered them.

Intersect.Client.Framework/Intersect.Client.Framework.csproj, Intersect.Client.Framework/Maps/IMapGrid.cs, Intersect.Client.Framework/Plugins/IClientPluginContext.cs, Intersect.Client/Intersect.Client.csproj, Intersect.Client/Maps/MapGrid.cs, Intersect.Client/Plugins/Contexts/ClientPluginContext.cs
Realised I exposed the grid locations in IMapInstance, but never the actual grid itself.
=> Expose Mapgrid information to client plugins

Intersect.Client.Framework/Entities/IResource.cs, Intersect.Client.Framework/Intersect.Client.Framework.csproj, Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Resource.cs
Just a little something I ran into while trying to make the minimap plugin distinguish between resource types. :)
=> Add Resource Interface so client plugins can figure out the base resource

Intersect.Editor/Forms/Editors/frmSpell.Designer.cs
Resolves #948 
Oopsie, somehow managed to unlink these before.
=> Re-assign events to combat spell form controls

Intersect.Client.Framework/Gwen/Control/Base.cs
=> save output when loading Gui Json files unless loading from cache

Intersect.Client/Core/Sounds/MapSound.cs
=> Makes MapSounds to use server tile sizes as reference.

Intersect.Server/Entities/Player.cs, Intersect.Server/Networking/PacketHandler.cs
=> Fix: "Player is Busy" on Party Invite.

Intersect.Server/Entities/Player.cs
=> Stacks with available space in them were ignored on item pickup if a full stack was in front of them, and the inventory was full

AUTHORS.md, Intersect.Server/Entities/Player.cs
=> Inventory Stack limit respected when pulling out of bank

Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs
_Should_ fix #1088 
https://user-images.githubusercontent.com/17498701/156083892-3e997d73-5221-4d5b-b556-bec3dfe5fce2.mp4
https://user-images.githubusercontent.com/17498701/156083933-88d4f580-31aa-48fd-bb56-46b97596c403.mp4
=> Fixes a visual glitch when moving elements within the hotbars.

AUTHORS.md
=> Add myself to authors

Intersect.Editor/Forms/DockingElements/frmMapEditor.cs, Intersect.Editor/Forms/DockingElements/frmMapList.cs, Intersect.Editor/Forms/frmMain.cs, Intersect.Editor/Maps/MapGrid.cs, Intersect.Editor/Networking/PacketHandler.cs
=> Store and Load the last map Id the editor has worked on when restarting

Intersect.Client/Interface/Game/Spells/SpellsWindow.cs
_Should_ fix #1090 
https://user-images.githubusercontent.com/17498701/156087884-4bab3145-d198-4a92-8e8e-23387a7dde7b.mp4
https://user-images.githubusercontent.com/17498701/156087894-ab028e17-2551-45ab-b6d4-ac4ec106d952.mp4
=> Fixes a visual glitch when moving spells within the spells window.

Intersect.Server/Entities/Entity.cs
=> FIX: 1087 (Step backward/forward do not work)

Intersect.Server/Entities/Combat/Status.cs
Kind of weird if an NPC can keep casting while they're stunned only for the cast to go off when the stun ends. lol
=> Actually interrupt all entity types upon applying an interrupt status, not just players.

Intersect.Editor/Forms/Editors/Events/Event Commands/Event_MoveRouteDesigner.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.cs
=> Don't allow selection of Move Route target when editing current event move route

Intersect.Client.Framework/Gwen/Control/NumericUpDown.cs, Intersect.Client.Framework/Gwen/Control/Slider.cs, Intersect.Client.Framework/Gwen/Control/TextBoxNumeric.cs
=> Change Numerical Input field values back-end storage to Double type

Intersect.Server/Entities/Entity.cs
*NOTE*: Don't know if this is actually in dev. Will close PR if not reproducable.
=> FIX-1123: OOB exception on spell cast cancellation

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement_idea.md, .github/ISSUE_TEMPLATE/feature_request.md
* Update enhancement_idea.md
* Update bug_report.md
* Update feature_request.md
=> chore: update issue templates (#1127)

Intersect (Core)/Logging/Formatting/DefaultFormatter.cs, Intersect (Core)/Logging/Output/ConciseConsoleOutput.cs, Intersect.Server/Core/Commands/SetVariableCommand.cs, Intersect.Server/Core/ConsoleService.ConsoleThread.cs, Intersect.Server/Localization/CommandsNamespace.cs
=> fix: command/console output

Intersect (Core)/Extensions/StringExtensions.cs, Intersect.Server/Core/CommandParsing/CommandParserErrorsNamespace.cs, Intersect.Server/Core/Commands/GetVariableCommand.cs, Intersect.Server/Core/Commands/ListVariablesCommand.cs, Intersect.Server/Core/Commands/SetVariableCommand.cs, Intersect.Server/Core/ConsoleService.ConsoleThread.cs, Intersect.Server/Database/GameData/GameContext.cs, Intersect.Server/Localization/CommandsNamespace.cs, Intersect.Server/Localization/Strings.cs
=> feat: add getvar/listvars, get/setvar accepts name or id

Intersect.Client.Framework/File Management/GameContentManager.cs, Intersect.Client/Interface/Shared/SettingsWindow.cs
- move SettingsWindow to the shared layout
=> fix: add "shared" layout directory (#1134)

Intersect (Core)/Enums/ChatboxChannel.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Events/CommandProcessing.cs
=> Add Party and Guild to AddChatBoxText event

Intersect.Server/Entities/Player.cs
[Minor code cleanup PR - No issue report is needed]
Adds missing Semicolon at Intersect.Server/Entities/Player.cs -> L:2203
=> Adds missing Semicolon at Server/Entities/Player

Intersect.Client.Framework/Content/ContentWatcher.cs, Intersect.Client.Framework/File Management/GameContentManager.cs, Intersect.Client.Framework/Gwen/Control/Base.cs, Intersect.Client/MonoGame/File Management/MonoContentManager.cs
=> feat: gui layout hot reloading prototype (#1136)

AUTHORS.md
Like requested in the issue #1158, I added myself as a contributor.
Thanks! 🙏
=> Adding myself as a contributor (#1158)

Intersect.Client.Framework/Gwen/Control/Base.cs, Intersect.Client.Framework/Gwen/Control/Canvas.cs, Intersect.Client.Framework/Gwen/Control/ComboBox.cs, Intersect.Client.Framework/Gwen/ControlInternal/Text.cs, Intersect.Client/Interface/Game/Bank/BankWindow.cs, Intersect.Client/Interface/Game/GameInterface.cs, Intersect.Client/Interface/Game/Hotbar/HotbarItem.cs, Intersect.Editor/Forms/DockingElements/frmMapEditor.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.cs, Intersect.Editor/Forms/Editors/frmCrafts.cs, Intersect.Editor/Forms/frmMain.cs, Intersect.Server/Core/LogicService.LogicThread.cs, Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Networking/PacketHandler.cs
Testing and working this time.
=> chore: Cherry Picking Fixes from Beta 7.1 into Beta 7.0 (Main) bug -- again

Intersect.Server/Entities/Entity.cs
Resolves #1171
Cherry picked this into Main so Stable doesn't crap itself when casting spells.
=> fix: Daywalkr - Bounds check (#1171)

Intersect.Client/Interface/Shared/SettingsWindow.cs
=> fix: pass .Key into GetName (#1160)

Intersect (Core)/Color.cs, Intersect (Core)/ErrorHandling/ExceptionRepeater.cs, Intersect.Client.Framework/Content/ContentWatcher.cs, Intersect.Client.Framework/File Management/GameContentManager.cs, Intersect.Client.Framework/Gwen/Control/Base.cs, Intersect.Client.Framework/Gwen/Control/Button.cs, Intersect.Client.Framework/Gwen/Control/CheckBox.cs, Intersect.Client.Framework/Gwen/Control/Label.cs, Intersect.Client.Framework/Gwen/Control/RadioButton.cs, Intersect.Client.Framework/Gwen/ControlInternal/Text.cs, Intersect.Client.Framework/Gwen/Skin/Base.cs, Intersect.Client.Framework/Gwen/Skin/Intersect2021.cs, Intersect.Client.Framework/Gwen/Skin/TexturedBase.cs, Intersect.Client/Core/Input.cs, Intersect.Client/Interface/Debugging/DebugWindow.cs, Intersect.Client/Interface/Game/AdminWindow.cs, Intersect.Client/Interface/Interface.cs, Intersect.Client/Interface/MutableInterface.cs, Intersect.Client/Localization/Strings.cs, Intersect.Client/MonoGame/File Management/MonoContentManager.cs, Intersect.Client/MonoGame/Graphics/MonoRenderer.cs
Resolves #1137
- added checkbox, radio button to skins
- made them composed and added extra states
- debug window persists on all screens
- improvements to settings window
- improvements to layout hot reloading (toggleable switch, but it still will break the UI in game)
- while we continue to use GWEN the way we do, layout hot reloading simply will not be completely functional, every hot reload makes the UI disjoint from the data it's representing, and also messes up the loaded files, and additionally will cause windows that shouldn't be visible to be visible prematurely, causing crashes **use at your own risk**
- admin window can be styled
=> feat: ui improvements, fixes, skin changes

Intersect.Client.Framework/Gwen/Control/Base.cs, Intersect.Client.Framework/Gwen/ControlInternal/Text.cs, Intersect.Client/Core/Main.cs, Intersect.Client/Interface/Debugging/DebugWindow.cs, Intersect.Client/Interface/Interface.cs, Intersect.Client/Interface/MutableInterface.cs, Intersect.Client/MonoGame/IntersectGame.cs
=> fix: prevent CancellationToken crash

Intersect.Client.Framework/Gwen/Control/TextBox.cs
=> fix: erase triggers an event, so do a replace and quit early for selection

Intersect.Client/Entities/Player.cs, Intersect.Client/Interface/Game/InputBox.cs, Intersect.Server/Entities/Player.cs
=> fix: re-add inventory update event/packet

Intersect (Core)/GameObjects/Events/Condition.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.Designer.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Events/Conditions.cs
Resolves #1189
Adds a new condition that checks whether or not the slot is busy.
Testing: https://www.ascensiongamedev.com/resources/filehost/d041471d7587942aa4ee656fd4c0ba25.mp4
=> Add a Slot Check Condition

Intersect (Core)/Core/ApplicationContext`2.cs, Intersect.Server/Core/ServerContext.cs
=> fix: make only errors have non-zero exit code from server/client #1203

Intersect (Core)/GameObjects/Events/Condition.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.Designer.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Events/Conditions.cs
* Added Slot Check Condition
* Panda Review
* Panda Review II
=> Add a Slot Check Condition (#1201)

Intersect.Client.Framework/Gwen/Control/TextBox.cs
=> fix: rewrite text insertion/replacement logic

Intersect.Client.Framework/Entities/IEntity.cs, Intersect.Client.Framework/Graphics/BoundsComparison.cs, Intersect.Client.Framework/Graphics/GameTexture.cs, Intersect.Client/Core/Graphics.cs, Intersect.Client/Entities/Animation.cs, Intersect.Client/Entities/ChatBubble.cs, Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Events/Event.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs, Intersect.Client/Interface/Menu/SelectCharacterWindow.cs, Intersect.Client/Maps/WeatherParticle.cs
Resolves #1213, #1214, #1215 (again)
- paperdoll color
- paperdoll position
- cast bar
- hp + shield bar
- label positioning
- chat bubble positioning
- event rendering simplification
- fix event label multi-rendering
=> fix: simplify rendering, adjust positioning

Intersect.Client/Entities/Player.cs
=> fix: check map for event entities

Intersect.Client/Entities/Critter.cs, Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Events/Event.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/Entities/Projectiles/Projectile.cs, Intersect.Client/Entities/Resource.cs, Intersect.Client/General/Globals.cs, Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs, Intersect.Client/Networking/PacketHandler.cs
=> fix: exact type check for name rendering

Intersect.Server/Entities/Player.cs
=> fix: Daywalkr - Guild instance warp validation was unnecessasry where it was

Intersect.Client.Framework/Content/ContentWatcher.cs
=> fix: switch to concurrent dictionary, suspected race condition crash with list

Intersect.Client/Entities/Entity.cs
=> fix: remove extra . in texture name

Intersect.Client/Entities/Events/Event.cs
=> fix: lazily cache tileset event textures

Intersect.Server/Intersect.Server.csproj
Prerelease equivalent of #1257
=> chore: update System.Text.Encodings.Web to 4.7.2

Intersect.Client/Entities/Player.cs
=> Fix Map Change crash when target tagged

Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Events/Event.cs
=> fix: correct event name rendering

Intersect.Client/Entities/Player.cs
* Sets the proper maximum amount for the trade window's input slider box when adding/taking stackable items from it.
* Should Fix #1288
Fix preview:
https://user-images.githubusercontent.com/17498701/174124650-95cf480c-7f4e-472d-a390-f0660a6fb3f3.mp4
=> Fix: Sets the proper maximum amount for the item trading input slider box

Intersect.Client/Entities/Player.cs
* Sets the proper maximum amount for shop's item selling input slider box when selling stackable items.
* Should Fix #1290
Fix preview:
https://user-images.githubusercontent.com/17498701/174140430-ef2e999b-add9-4750-bd96-fed621d8a79f.mp4
=> Fix: Sets the proper maximum amount for shop's item selling input slider

Intersect.Client/Interface/Menu/SelectCharacterWindow.cs
* Should fix #1279
Fix preview:
https://user-images.githubusercontent.com/17498701/174326280-ff419ab1-7878-4e7d-9d42-ae2cbdd832aa.mp4
=> Fix: render selected character's equipment in main menu

Intersect.Client/Entities/Critter.cs, Intersect.Client/Entities/Entity.cs, Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/Events/EventPageInstance.cs, Intersect.Server/Entities/Npc.cs, Intersect.Server/Maps/MapInstance.cs
=> enhancement: Make directions consistent by utilizing Options.Instance.Sprites.Directions

Intersect.Editor/Forms/Editors/Events/frmEvent.Designer.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.cs
=> resolves (#1327) Green event labels!

Intersect.Client/Entities/Player.cs
=> fix: hotbar key reference

Intersect.Client/Networking/PacketHandler.cs
=> fix: client crash at login when deleting gameobject

Intersect.Server/Networking/Client.cs
=> maybe fix editors saving and rolling back characters

Intersect (Core)/GameObjects/Events/EventPage.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.Designer.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Entity.cs
=> Defaulted events to respect npc avoids with editor option to ignore them

Intersect.Client/Core/Main.cs, Intersect.Client/Interface/Game/GameInterface.cs, Intersect.Client/Interface/Interface.cs, Intersect.Client/Interface/Menu/MenuGuiBase.cs
This resolves #1344 
I found that the UI elements although hidden could still be closed, so the extra code changes in this pr fixes that as well.
=> fix #1344: force show the ui when user input is required

Intersect.Server/Entities/Events/CommandProcessing.cs
=> Fix stat allocation bug

Intersect.Server/Entities/Entity.cs
=> Snare Spell Effect Fix

Intersect.Server/Entities/Entity.cs
=> NPC getting aggro when targeted by player spell

Intersect (Core)/Updater/Updater.cs, Intersect.Client/MonoGame/IntersectGame.cs
=> fix: (Day) - Update editor to use appropriate strings for file size/remaining text

Intersect.Server/Networking/PacketHandler.cs
=> Fix 1358 "Loot All" across map boundaries

Intersect (Core)/Models/DatabaseObject.cs, Intersect.Server/Networking/PacketHandler.cs
Simplifies part of the logic in #1358
=> chore: simplify canTake

Intersect.Server/Admin/Actions/ActionProcessing.cs, Intersect.Server/Localization/Strings.cs
* This commit will disallow to target the WarpToMe and WarpMeTo action on whoever performs the action.
* Should resolve #1380
=> Disallows to target warp actions on whoever performs them

Intersect (Core)/Network/Packets/Server/EntityAttackPacket.cs, Intersect.Client.Framework/Entities/IPlayer.cs, Intersect.Client/Core/Input.cs, Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/Networking/PacketHandler.cs, Intersect.Server/Entities/Entity.cs, Intersect.Server/Networking/PacketHandler.cs, Intersect.Server/Networking/PacketSender.cs
Resolves #1300
I believe that the block was created to act as a "status", the player while holding the button is in a "defense state" until released, I changed that.
I'm using the attack logic as a base to modify the blocking, now, it is working similar to the attack, as an action and not as a "state", so while holding the block button, it keeps making several attempts to block, as it works in attack.
Basically, the player either attacks or defends, never both, and [this fixes the attack animation playing after blocking.](https://github.com/AscensionGameDev/Intersect-Engine/issues/1300)
I just changed the logic a little bit of how it works to make it look like the attack with "speed modifier".
=> Blocking Refactor I

Intersect.Server/Database/Item.cs, Intersect.Server/Database/PlayerData/Players/Bag.cs
=> fix bags with deleted items have slots taken by ghost items

Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/Npc.cs, Intersect.Server/Entities/Player.cs
=> chore: Refactor Entity#DropItems() to be virtual/abstract

Intersect.Server/Maps/MapInstance.cs
=> fix: (Day) Fix to not cleanup overworld map instances

Intersect.Client/Interface/Game/Crafting/CraftingWindow.cs, Intersect.Client/Localization/Strings.cs
resolves #1433
A little more description for the crafting window
=> Crafting Description

Intersect (Core)/Config/ItemOptions.cs, Intersect (Core)/Config/Options.cs, Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs, Intersect.Client/Localization/Strings.cs, Intersect.Client/MonoGame/IntersectGame.cs, Intersect.Client/Networking/PacketHandler.cs, Intersect.Editor/Forms/Editors/frmItem.cs, Intersect.Editor/Forms/frmLogin.cs, Intersect.Editor/Forms/frmUpdate.cs, Intersect.Editor/Localization/Localizer.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Editor/Networking/PacketHandler.cs
- rewrote string loading/saving to only add missing content
- add item rarity configuration to the server
- reload strings after receiving options to include missing content
- disabled log spam from the editor localizer
Resolves #1435
=> feat: configurable item rarities

Intersect.Client/Intersect.Client.csproj, Intersect.Client/app.manifest
=> fix: correctly reference application manifest to return true native resolution

Intersect.Server/Networking/PacketSender.cs
=> fix: get correct map instance

Intersect.Editor/Forms/frmMain.cs
=> fix: exit from method on null source/target path

Intersect.Editor/Forms/frmMain.cs, Intersect.Editor/Localization/Strings.cs
=> fix: safely parse input and show error to user

Intersect.Editor/Forms/Editors/frmItem.Designer.cs
=> Small reordering in item editor

Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/ProjectileSpawn.cs
=> fix: don't try to attack EventPageInstances

Intersect.Editor/Forms/DockingElements/frmMapEditor.cs
=> fix: replace recursive flood-fill with bfs

Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_PlayAnimation.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_SpawnNpc.cs, Intersect.Editor/Forms/Helpers/GridHelper.cs
=> fix: correct pixel-to-cell translation

Intersect (Core)/Network/Packets/Client/CraftItemPacket.cs, Intersect.Client/Interface/Game/Crafting/CraftingWindow.cs, Intersect.Client/Interface/Game/GameInterface.cs, Intersect.Client/Networking/PacketSender.cs, Intersect.Server/Entities/Events/Event.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Localization/Strings.cs, Intersect.Server/Networking/PacketHandler.cs
=> fix: make autocrafting serverside

Intersect (Core)/GameObjects/ItemBase.cs, Intersect (Core)/GameObjects/Maps/MapAttribute.cs, Intersect.Editor/Forms/DockingElements/frmMapLayers.Designer.cs, Intersect.Editor/Forms/DockingElements/frmMapLayers.cs, Intersect.Editor/Forms/DockingElements/frmMapLayers.resx, Intersect.Editor/Forms/Editors/frmItem.Designer.cs, Intersect.Editor/Forms/Editors/frmItem.cs, Intersect.Editor/Forms/Editors/frmItem.resx, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Maps/MapInstance.cs, Intersect.Server/Maps/MapItemInstance.cs, Intersect.Server/Migrations/Game/20220926042726_AddedConfigurableItemDespawnTimes.Designer.cs, Intersect.Server/Migrations/Game/20220926042726_AddedConfigurableItemDespawnTimes.cs
=> enhance: custom item attribute respawn timers and custom item despawn timers

Intersect.Client/Interface/Game/Crafting/CraftingWindow.cs, Intersect.Server/Entities/Player.cs
=> fix: correct craft all button updates and failure chance rolls

Intersect.Server/Entities/Player.cs
=> fix: if target is npc, check if we can attack them

Intersect.Client/Interface/Debugging/DebugWindow.cs
=> fix: add another ToArray() and prevent initialization when not yet rendered

Intersect (Core)/GameObjects/Drop.cs, Intersect (Core)/GameObjects/NpcBase.cs, Intersect (Core)/GameObjects/ResourceBase.cs, Intersect.Editor/Forms/Editors/frmNpc.cs, Intersect.Editor/Forms/Editors/frmResource.cs
=> chore: refactor NpcDrop and ResourceDrop

Intersect.Client/Entities/Player.cs, Intersect.Client/Interface/Game/InputBox.cs, Intersect.Client/Interface/Game/Inventory/InventoryItem.cs, Intersect.Client/Interface/Game/Spells/SpellItem.cs, Intersect.Editor/Networking/Network.cs, Intersect.Server/Entities/BankInterface.cs, Intersect.Server/Entities/Player.cs
=> fix: rework a lot of item logic

Intersect.Editor/Forms/Editors/Events/frmEvent.Designer.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.cs, Intersect.Editor/Localization/Strings.cs
resolves #1441
https://user-images.githubusercontent.com/63019821/188471470-a209469c-762a-4a7f-94de-87967efa6ccf.mp4
=> New Trigger Layout

Intersect.Client/Networking/PacketHandler.cs
=> Fix warp bug

Intersect.Server/Web/RestApi/Authentication/OAuth/Providers/BearerAuthenticationProvider.cs, Intersect.Server/Web/RestApi/Authentication/OAuth/Providers/GrantProvider.cs, Intersect.Server/Web/RestApi/IntersectApiController.cs, Intersect.Server/Web/RestApi/Routes/V1/UserController.cs
Resolves #1449 
- Also prevents banned users from using the API (which they could use to unban themselves)
=> fix: resolve errors when trying to perform administrator actions

Intersect.Server/Metrics/Controllers/NetworkMetricsController.cs, Intersect.Server/Metrics/Controllers/ThreadingMetricsController.cs
=> fix: change method invoked to avoid SOE

Intersect.Client.Framework/Gwen/Control/Base.cs, Intersect.Client.Framework/Gwen/Control/LabeledCheckBox.cs, Intersect.Client.Framework/Gwen/Control/LabeledRadioButton.cs
=> fix: link cb/rb subcomponents to parents

Intersect.Server/Entities/Player.cs, Intersect.Server/Networking/Client.cs, Intersect.Server/Networking/PacketHandler.cs
=> fix: prevent event deadlock

Intersect.Server/Core/Commands/PanicCommand.cs, Intersect.Server/Core/ConsoleService.ConsoleThread.cs, Intersect.Server/Localization/CommandsNamespace.cs
Note that this command _will_ crash your server, so only use it when collecting information when it is not responding to clients/editors and you intend to reboot it anyway.
=> feat: panic command for the server to dump information

Intersect.Client.Framework/Gwen/Control/Slider.cs
=> fix: correct NaN in slider

Intersect.Client/Entities/Player.cs
=> fix: packet flood on AutoTurnToTarget

Intersect.Server/Entities/Player.cs
Reverts AscensionGameDev/Intersect-Engine#1616
=> Revert "fix: (Day) Move event queue out of a foreach"

Intersect.Server/Web/RestApi/Routes/V1/UserController.cs
=> fix: correct incorrect response codes

Intersect.Server/Web/RestApi/Routes/V1/UserController.cs
=> fix: return object instead of string

Intersect.Server/Web/RestApi/Routes/V1/UserController.cs
=> fix: prevent nre in user controllers

Intersect.Server/Entities/Entity.cs, Intersect.Server/Maps/MapInstance.cs, Intersect.Server/Maps/MapNpcSpawn.cs
=> fix: rewrote npc/resource logic to be simpler and more NRE resistant

Intersect.Server/Database/PlayerData/SeedData/SeedUsers.cs
This pull request should resolve #1636
=> fix: adds missing reference to SeedUsers.cs

Intersect.Client/Entities/Entity.cs
Chore: replaces a hardcoded value ( 3 ) with it's correspoding configurable value (NormalSheetAttackFrame).
=> chore: replaces hardcoded value with NormalSheetAttackFrame

Intersect.Client/Core/Input.cs, Intersect.Client/Entities/Critter.cs, Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/Networking/PacketHandler.cs
* Client: Replaces duplicated tick calculations by Timing.Global.Milliseconds
=> chore: replaces duplicated tick calculations

Intersect.Client/Interface/Game/Character/EquipmentItem.cs
=> fix: character window equipped item menu

Intersect.Client.Framework/Gwen/Renderer/IntersectRenderer.cs
=> fix: correctly scale textures for clipping logic when scrolling in UI containers

Intersect.Client.Framework/Gwen/Skin/TexturedBase.cs
* Improves context menus by adding a texture that provides better visibility on highlighted elements.
* Requires the following assets: https://github.com/AscensionGameDev/Intersect-Assets/pull/35
* Requires the following assets: https://github.com/AscensionGameDev/Intersect-Assets/pull/36
https://user-images.githubusercontent.com/17498701/210157263-6e853d51-6c84-439a-ab47-91a96b70baa7.mp4
=> enhancement: hovered context menu elements

Intersect.Client.Framework/Gwen/Renderer/IntersectRenderer.cs
=> fix: gwen issues on container and canvas edges

Intersect.Client.Framework/Gwen/Control/TreeNode.cs, Intersect.Client/Interface/Game/AdminWindow.cs, Intersect.Client/Interface/Game/BanMuteBox.cs, Intersect.Client/Localization/Strings.cs
* Admin/Ban/Mute Windows: revamped visual elements to fit current Intersect's styling, also improved elements readability.
* chore and fixes for tree nodes: the 'CalculateTreeNodeHeight' method sets the correct height of the trees nodes before they are drawn. This eliminates the need for a second pass to set the correct height and prevents nodes from getting hidden when expanding and collapsing.
* strings: fixes typos for a couple of buttons
https://user-images.githubusercontent.com/17498701/221968654-4b1a282e-fdd7-4146-a359-29ff1bfb78af.mp4
=> enhancement: admin window

Intersect (Core)/GameObjects/Events/Condition.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.Designer.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Events/CommandProcessing.cs, Intersect.Server/Entities/Events/Conditions.cs, Intersect.Server/Entities/Events/VariableCheckHandlerRegistry.cs
Before it was necessary to define a variable for the value "Time system" so that we could compare with our variables that use the time system, this modification allows to compare directly.
https://user-images.githubusercontent.com/63019821/215845980-fc58147b-0e5a-474a-a2d1-b097e22af4f3.mp4
=> enhancement: directly compare with TimeSystem conditions

Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Player.cs
* Simplified code, tested and covered all scenarios.
=> chore: overhead hp bar

Intersect.Client/Maps/MapInstance.cs
=> fix: clipped fog when walking through maps

Intersect.Client/Interface/Game/Typewriting/Typewriter.cs
- fixes an issue where the typewriter would stop working after doing it's job once.
- refactors typewriter and it's write logic bit.
=> chore and fix: typewriter

Intersect (Core)/Enums/ItemEffect.cs, Intersect (Core)/Enums/SpellEffect.cs, Intersect (Core)/GameObjects/ItemBase.cs, Intersect (Core)/GameObjects/NpcBase.cs, Intersect (Core)/GameObjects/SpellBase.cs, Intersect (Core)/Network/Packets/Server/StatusPacket.cs, Intersect.Client.Framework/Entities/IStatus.cs, Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/Entities/Status.cs, Intersect.Client/Interface/Game/Character/CharacterWindow.cs, Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs, Intersect.Client/Interface/Game/DescriptionWindows/SpellDescriptionWindow.cs, Intersect.Client/Networking/PacketHandler.cs, Intersect.Editor/Forms/Editors/frmItem.cs, Intersect.Editor/Forms/Editors/frmNpc.cs, Intersect.Editor/Forms/Editors/frmSpell.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Combat/DoT.cs, Intersect.Server/Entities/Combat/Status.cs, Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/Npc.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Maps/MapInstance.cs, Intersect.Server/Networking/PacketHandler.cs
chore: enum corrective naming
> StatusTypes -> SpellEffect
> EffectType -> ItemEffect
=> chore: enum corrective naming

Intersect.Client/Entities/Animation.cs
* fixes an issue where animation rotation couldn't be disabled.
* should resolve #1749
https://user-images.githubusercontent.com/17498701/223606194-032b652c-9e66-4f00-bfad-8f62e315971d.mp4
=> fix: animation rotation can't be disabled

Intersect.Server/Entities/Player.cs
https://user-images.githubusercontent.com/17498701/236640146-719bf558-935c-4ea3-b866-0921273a34d1.mp4
=> enhancement: notify when learning spell from item

Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.cs
=> fix: wrong selecting variables on hasItem and freeSlots

Intersect.Server/Core/LogicService.LogicThread.cs, Intersect.Server/Maps/MapInstance.cs
=> Fix possible excessive cpu usage due to abandoned maps still being considered active

Intersect.Client/Interface/Game/DescriptionWindows/Components/ComponentBase.cs
=> avoid description window to delete control twice

Intersect.Client/Entities/Player.cs
I also forgot to check if it is blocking when it tries to block, so it floods the server with unnecessary packets
=> avoid blocking with shield packets flood

Intersect (Core)/Enums/Direction.cs, Intersect (Core)/GameObjects/Maps/MapAttribute.cs, Intersect.Editor/Forms/DockingElements/frmMapLayers.cs, Intersect.Server/Entities/Combat/Dash.cs, Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/Events/EventPageInstance.cs, Intersect.Server/Entities/MovementBlockerType.cs, Intersect.Server/Entities/Npc.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Networking/PacketHandler.cs
Fixes #1100 
Note to reviewers: the easiest way to review this is by reviewing each commit one-by-one in chronological order
The names of each commit say exactly what operation was done in each commit so some of the commits are basically not necessary to review.
=> chore: refactor Entity#CanMove()'s return types

Intersect.Client/MonoGame/Graphics/MonoRenderer.cs, Intersect.Client/MonoGame/IntersectGame.cs, Intersect.Client/MonoGame/NativeInterop/Sdl2.Rect.cs, Intersect.Client/MonoGame/NativeInterop/Sdl2.Video.cs, Intersect.Client/MonoGame/NativeInterop/Sdl2.cs
- linux is known to  be broken without this fix if primary display is not leftmost
=> fix: correct startup window position for multimonitor devices

Intersect.Server/Entities/Player.cs, Intersect.Server/Networking/PacketHandler.cs
resolves #1836 
I slightly modified the logic of the crafting checks, and tried to lock the craft item logic and cancel crafting.
ps: Despite the reported video of the bug, I haven't been able to reproduce the bug even once, before or after this modification, so I need help verifying the changes I've made to see if the bug has been fixed or not. I made these initial changes in an attempt to start the discussion for resolution of this bug.
=> fix: prevent crashing when stopping active crafting

Intersect (Core)/Network/Packets/Server/EventEntityPacket.cs, Intersect.Client/Entities/Events/Event.cs, Intersect.Client/Entities/Player.cs, Intersect.Server/Entities/Events/EventPageInstance.cs
=> Allow firing projectiles while facing events whos trigger is not 'Action Button'

Intersect.Server/Networking/PacketHandler.cs
=> fix(1877): simplify logic and check for nulls

Intersect.Client/Core/Graphics.cs
=> fix: (Day) 1885 - Issue where custom cursors didn't work with zoom

Intersect.Client/Core/Graphics.cs, Intersect.Client/Entities/Resource.cs
=> fix: (Day) 1887 - Fixes issues with zoom out at >32px tile size

Intersect (Core)/GameObjects/ProjectileBase.cs
should resolve #1827
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/ec5fb32e-0ac0-4c48-8c02-e972721782f0
=> fix: projectile diagonal directions

Intersect.Server/Migrations/Game/20201001163344_ItemAndSpellCooldownImprovements.cs, Intersect.Server/Migrations/Game/20211026130945_NpcImmunityMigration.cs
=> fix: nullable string columns for SQLite

Intersect (Core)/GameObjects/Events/Commands/EventCommands.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ChangeSpells.Designer.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ChangeSpells.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server/Entities/Events/CommandProcessing.cs, Intersect.Server/Entities/Player.cs
Should resolve #1715
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/03b3bc79-85fc-4d28-b596-d3f2d5e806e1
=> fix/enhancement: remove bounded spells through events

Intersect (Core)/Network/Packets/Server/GlobalCooldownPacket.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/Networking/PacketHandler.cs, Intersect.Server/Entities/Player.cs, Intersect.Server/Networking/PacketSender.cs
Resolves #1906 
I am a big dum.
=> redo global cooldown to be its own value

Intersect.Server/Entities/Player.cs
Resolves #1916 
Pretty rare crashes, one of them has been reported by Naziozeno Austermann, the second I saw while I was reading through the method to see what could cause the problem.
=> Fix NRE and Collection Modified Exceptions in Player.GetMaxVital

Intersect.Editor/Forms/Editors/frmItem.Designer.cs
=> fix infinite mouse loading on item editor

Intersect.Server/Entities/Player.cs
Resolves #1918 
Attempt to fix all non-null checked accessing of Player.CraftingState so it can hopefully not crash the server anymore.
=> fix: Potential NREs on Player.CraftingState

Intersect (Core)/GameObjects/Annotations/EditorDictionaryAttribute.cs, Intersect.Editor/Localization/Strings.cs
=> fix: int dict to localedictionary

Intersect.Server/LICENSE.md
Here's my part for the license update.
Thanks for your consideration 🙏
=> Update LICENSE.md GPLv3 to MIT

Intersect.Server/Entities/Npc.cs
(Fix & Chore - Also potentially prevents NPE)
=> fix: typo and swaps condition checks within NotifySwarm

Intersect.Server/Web/Net7/ApiService.cs, Intersect.Server/Web/RestApi/Routes/OAuthController.cs
Removed Identity which was not being utilized.
Added role claims into our security descriptor which seems to work fine.
=> Fix user based api endpoints

Intersect.Server/Database/PlayerData/Players/Bag.cs
=> fix: use Add() instead of Update() when creating bags

Intersect.Client/Interface/Game/Trades/TradeItem.cs, Intersect.Client/Interface/Game/Trades/TradingWindow.cs
- should resolve #1970
- we don't need this: dragging items within the trade window isn't doing a thing on neither of the offering sides
=> fix: removes the ability to drag items within the trade window

Intersect.Server/Migrations/MySql/Player/20231017140257_UpdatingQuestHotbarSwitchIdsToAutoGenerate.Designer.cs, Intersect.Server/Migrations/MySql/Player/20231017140257_UpdatingQuestHotbarSwitchIdsToAutoGenerate.cs, Intersect.Server/Migrations/Sqlite/Player/20231017140318_UpdatingQuestHotbarSwitchIdsToAutoGenerate.Designer.cs, Intersect.Server/Migrations/Sqlite/Player/20231017140318_UpdatingQuestHotbarSwitchIdsToAutoGenerate.cs, Intersect.Server/Migrations/Sqlite/Player/SqlitePlayerContextModelSnapshot.cs
This is just the migrations for the changes I've already merged on accident.
=> fix: Allow ef to handle add vs update of hotbar, quests, and switches Pt. 2

Intersect.Server/Entities/Entity.cs, Intersect.Server/Entities/Npc.cs
=> fix: make NPCs unable to exhaust all their HP casting a spell

Intersect.Server.Core/Entities/Projectile.cs
should resolve #2001 
preview:
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/6e44b227-723a-48d1-b54b-aff97ca02faa
=> fix: allow diagonal grapple hooks

Intersect.Client/Maps/MapInstance.cs
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/4d159b86-a7e0-4ce7-8a40-ac86bcfd169a
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/82451ae9-cc07-4dc5-b5b2-d2efb24dde4c
=> fix: fog displacement

Intersect.Client/Maps/MapInstance.cs
- restored the check branching for better readability
- (tested) fixes fog displacement when crossing maps **vertically and horizontally** without issues -
Thanks to Akemi for reporting this: https://streamable.com/32e5vt
Should hopefully resolve #1884 
Preview after this PR's changes:
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/adef1921-6ca0-4924-be77-ec5b82312138
=> fix: safe checks on fog displacement

Intersect.Client/Interface/Interface.cs, Intersect.Client/Localization/Strings.cs, Intersect.Client/MonoGame/Network/MonoSocket.cs
=> fix(1640): don't crash on dns failure

Intersect.Server.Core/Entities/Entity.cs, Intersect.Server.Core/Entities/Events/EventPageInstance.cs
=> fix: actually take DirectionFix into account

Intersect (Core)/Logging/Output/FileOutput.cs, Intersect (Core)/Network/Packets/Client/NeedMapPacket.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/Maps/MapInstance.cs, Intersect.Client/Networking/PacketSender.cs, Intersect.Server.Core/Networking/PacketHandler.cs
=> chore(1377): batch map request packets from client

Intersect.Client/Core/Main.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/Networking/PacketHandler.cs, Intersect.Client/Networking/PacketSender.cs, Intersect.Server.Core/Database/DbInterface.cs, Intersect.Server.Core/Entities/Entity.cs, Intersect.Server.Core/Entities/Pathfinding/Pathfinder.cs, Intersect.Server.Core/Maps/MapGrid.cs, Intersect.Server.Core/Maps/TileHelper.cs, Intersect.Server.Core/Networking/PacketHandler.cs, Intersect.Server.Core/Networking/PacketSender.cs, Intersect.Server/Networking/NetworkedPacketHandler.cs
=> fix: flip incorrect condition and actually bulk-request updates, get rid of a lot of horrid lookups

Intersect.Client/Entities/Player.cs, Intersect.Client/Interface/Game/Bag/BagItem.cs, Intersect.Client/Interface/Game/Bank/BankItem.cs, Intersect.Client/Items/Item.cs, Intersect.Server.Core/Entities/BankInterface.cs, Intersect.Server.Core/Localization/Strings.cs
=> fix(2038): allow merging bank slots and deposit in the right slot

Intersect.Client/Entities/Player.cs, Intersect.Client/Items/Item.cs, Intersect.Server.Core/Database/Item.cs, Intersect.Server.Core/Entities/BankInterface.cs
=> fix: clone slots if they are single item/equipment

Intersect (Core)/Enums/Direction.cs, Intersect.Client/Entities/Critter.cs, Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/Entities/Projectiles/Projectile.cs
=> feat(1763): diag slides if only one dir blocked

Intersect.Network/LiteNetLib/LiteNetLibInterface.cs
=> fix(2041): don't trigger OnDisconnect for manual disconnection 🔄

.github/workflows/build.yml, Intersect.Client/Intersect.Client.csproj, Intersect.Editor/Intersect.Editor.csproj, Intersect.Server/Intersect.Server.csproj
Contrary to the first commit comment, unix permissions _do not_ seem to make it through
=> chore: binary compression and separate platform builds

Intersect.Server.Core/Database/Item.cs, Intersect.Server.Core/Entities/Player.cs, Intersect.Server.Core/Networking/PacketHandler.cs
=> feat: insert stackables into partially filled bag slots before inventory

Intersect (Core)/CustomColors.cs, Intersect.Client.Framework/Maps/IMapInstance.cs, Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Player.cs
Default hostile color:
Default party color:
Default guild color:
=> feat: (Day) Adds custom player name colors for in-party/in-guild/hostile

Intersect (Core)/Config/CombatOptions.cs, Intersect.Server.Core/Entities/Player.cs
=> feat: (Day) Add option to allow safe zones to consider any player friendly

Intersect.Server.Core/Entities/Player.cs, Intersect.Server.Core/Networking/PacketHandler.cs
Allows ex-party members to rejoin a shared instance
=> Rejoin shared instance

Intersect.Server.Core/Database/Logging/Entities/ChatHistory.cs, Intersect.Server.Core/Database/Logging/Entities/GuildHistory.cs, Intersect.Server.Core/Database/Logging/Entities/TradeHistory.cs, Intersect.Server.Core/Database/Logging/Entities/UserActivityHistory.cs, Intersect.Server/Web/RestApi/Routes/V1/InfoController.cs
=> fix: b8 broken api endpoints and logging

Intersect.Server/Web/RestApi/Routes/V1/InfoController.cs
I failed to fix this previously.. should be good now.
=> fix: metrics api endpoint attempt 2

Intersect.Client/Interface/Shared/SettingsWindow.cs
=> fix: remove shortcircuit for none

Intersect.Server.Core/Entities/Combat/Status.cs, Intersect.Server.Core/Entities/Entity.cs
=> fix: (Day) Fixes issue where shields did not scale with equipment stats'

Intersect.Server.Core/Entities/BankInterface.cs
More information/context in the dev discord.
=> fix: item dupe with mismatched inventory bank stacking values

.gitmodules, Intersect.Editor/Intersect.Editor.csproj, Intersect.sln
=> Fix docking forms registry error on windows

Intersect.Editor/Intersect.Editor.csproj
Fixes: https://github.com/AscensionGameDev/Intersect-Engine/issues/2165
=> Fixed DPI Scaling issue on Intersect Editor

Intersect (Core)/GameObjects/Events/Commands/EventCommands.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_EquipItem.Designer.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_EquipItem.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server.Core/Entities/Events/CommandProcessing.cs, Intersect.Server.Core/Entities/Player.cs
resolves #1789 
originally made by @WeylonSantana 
https://github.com/AscensionGameDev/Intersect-Engine/pull/1831
updated and solved conflicts
=> enhancement: trigger cooldown timer by event equip command

Intersect.Server.Core/Maps/MapGrid.cs
=> fix: update map grid cache when editing maps

Intersect.Client/Interface/Game/GameInterface.cs
Resolves #2188 
Fixes a bug where you had to press the hotkey twice in order to open the admin panel twice before it would open for the first time
=> fix: opening admin panel

Intersect.Editor/Forms/Editors/frmAnimation.Designer.cs, Intersect.Editor/Forms/Editors/frmAnimation.cs, Intersect.Editor/Localization/Strings.cs
This feature PR seeks to add the ability to play sounds within the animation editor and the ability to loop sounds on frame 1 during layer animation preview
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/67ae477a-0b53-4b05-9c32-eba4be7a5c98
=> feature: ability to play sounds within the animation editor

Intersect.Editor/Forms/Editors/frmItem.Designer.cs
=> fix: allow negative values for item stat bonuses

Intersect.Editor/Forms/Editors/Events/frmEvent.Designer.cs
Fixes #2229
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/2257f49d-1093-4438-91e4-77760db1f3f6
=> fix: typo in event command type for setGuildBankSlotsTreeNode

Intersect.Network/ClientNetwork.cs
Should resolve #2238 
Preview:
( Screenshot by @cydyn )
=> fix: update ping information

Intersect.Server.Core/Entities/Player.cs
safe checks as attempt to fix #2245
(I've been unable to reproduce the bug, my server doesn't crashes at all when crafting)
=> fix: server crash when crafting

Intersect (Core)/GameObjects/Events/Commands/EventCommands.cs, Intersect.Editor/Forms/Editors/Events/CommandPrinter.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_EquipItem.Designer.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_EquipItem.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_EquipItem.resx, Intersect.Editor/Localization/Strings.cs, Intersect.Server.Core/Entities/Events/CommandProcessing.cs
resolves #1190
https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/581348c8-1e62-446d-8ed4-d59bc2db975d
=> feature: unequip item by slot

Intersect (Core)/Network/Packets/Client/LogoutPacket.cs, Intersect.Client/Core/Main.cs, Intersect.Client/General/Globals.cs, Intersect.Client/Interface/Game/EscapeMenu.cs, Intersect.Client/Interface/Menu/SelectCharacterWindow.cs, Intersect.Client/Networking/Network.cs, Intersect.Client/Networking/PacketSender.cs, Intersect.Server.Core/Networking/PacketHandler.cs
resolves all issues related to returning to the main menu, keeping the client disconnected when out of the game (in main menu screen), and only showing messages when the client actually loses connection to the server
https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/dbf7c894-bcc5-4548-b75e-77b35c3c652e
=> fix: disconnection error when returning to main menu

Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_Variable.cs
=> fix: editor crashes on specifics variable mods

Intersect.Client/Entities/Player.cs
resolves #2154 
There is a check for this on the server player update side, but it should also be on the client side..
=> fix: player infinite blocking state on client side

Intersect (Core)/GameObjects/Events/EventBase.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.Designer.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server.Core/Entities/Player.cs, Intersect.Server.Core/Migrations/Sqlite/Game/20240608185758_ParallelEvents.Designer.cs, Intersect.Server.Core/Migrations/Sqlite/Game/20240608185758_ParallelEvents.cs
resolves #1498 
https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/dbfa016d-d76d-4bd9-8b0e-39840ba35ef9
new checkbox added to give events the possibility of running in parallel, useful when we kill several monsters in one hit and then want everyone's events to run, by default false
=> feature: run parallel events

Intersect (Core)/GameObjects/ProjectileBase.cs, Intersect (Core)/Network/Packets/Client/TargetPacket.cs, Intersect.Client/Entities/Animation.cs, Intersect.Client/Entities/Player.cs, Intersect.Client/Entities/Projectiles/Projectile.cs, Intersect.Client/Networking/PacketSender.cs, Intersect.Editor/Forms/Editors/frmProjectile.Designer.cs, Intersect.Editor/Forms/Editors/frmProjectile.cs, Intersect.Editor/Forms/Editors/frmProjectile.resx, Intersect.Editor/Localization/Strings.cs, Intersect.Server.Core/Entities/Projectile.cs, Intersect.Server.Core/Migrations/Sqlite/Game/20240607105636_HomingProjectile.Designer.cs, Intersect.Server.Core/Migrations/Sqlite/Game/20240607105636_HomingProjectile.cs, Intersect.Server.Core/Networking/PacketHandler.cs
https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/8a654541-e78b-411a-9e1b-e749aa6f7f82
=> feature: homing projectiles

Intersect.Client/Entities/Entity.cs, Intersect.Client/Entities/Projectiles/Projectile.cs
=> fix: homing projectile on map border visual bug

Intersect.Client/Entities/Projectiles/Projectile.cs, Intersect.Server.Core/Entities/Projectile.cs
resolves #2273 
https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/3fc7e1be-f773-4842-a99b-76e717903660
=> fix: homing projectiles not transversing maps

Intersect.Client/Entities/Projectiles/Projectile.cs, Intersect.Server.Core/Entities/Entity.cs, Intersect.Server.Core/Entities/Projectile.cs
I did some major cleaning and now I believe I have fixed all the bugs regarding the projectile homing system.
fixed - #2279
fixed - #2280
fixed - projectiles knockback
fixed - projectile bug on seamless world
https://www.ascensiongamedev.com/resources/filehost/9a68339599c4b8be5a5996df097f7062.mp4
=> fix: bugs about projectile system

Intersect.Client/Interface/Game/EntityPanel/PlayerStatusWindow.cs
Fixes #2297
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/932a5076-ee51-4169-94c3-749b7627b42e
=> fix: player status timer

Intersect.Client/Entities/Projectiles/Projectile.cs
fixes #2319
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/05482ba0-16d9-4c0e-a4ff-60e844a9f118
https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/b61fe28a-67ff-47dd-a97c-1e117fb4977a
=> fix: client side projectile issue

Intersect.Client/Entities/Entity.cs
=> fix: entity animation texture

Intersect.Client/Core/Input.cs, Intersect.Client/Interface/Game/Menu.cs
small bug fix so we can properly open the simplified escape menu with ESC KEY (default for opening the game menu).
Preview:
https://github.com/user-attachments/assets/461a04f7-b6e5-4169-8813-88918a520a77
=> fix: esc key - simplified escape menu

Intersect.Server.Core/Entities/Entity.cs, Intersect.Server.Core/Entities/Npc.cs, Intersect.Server.Core/Entities/Pathfinding/IIndexedObject.cs, Intersect.Server.Core/Entities/Pathfinding/PathNode.cs, Intersect.Server.Core/Entities/Pathfinding/PathNodeBlockType.cs, Intersect.Server.Core/Entities/Pathfinding/PathNodeComparer.cs, Intersect.Server.Core/Entities/Pathfinding/Pathfinder.cs, Intersect.Server.Core/Entities/Pathfinding/PathfinderResult.cs, Intersect.Server.Core/Entities/Pathfinding/PathfinderResultType.cs, Intersect.Server.Core/Entities/Pathfinding/SpatialAStar.cs, Intersect.Server.Core/Entities/Player.cs
=> fix: pathfind through players, and attack blocking players when not fleeing

Intersect (Core)/Collections/Slotting/SlotList.cs, Intersect.Server.Core/Entities/BankInterface.cs
=> fix(2431): Ensure that target inventory has slots populated

Intersect (Core)/Config/ItemOptions.cs, Intersect.Client.Core/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs, Intersect.Client.Core/Localization/Strings.cs, Intersect.Editor/Forms/Editors/frmItem.cs, Intersect.Editor/Localization/Strings.cs
=> fix(2398): don't unsafely grab strings from ItemOptions.RarityTiers

Intersect.Client.Core/MonoGame/Network/MonoSocket.cs, Intersect.Client.Core/Networking/Network.cs
=> fix: #2255

Framework/Intersect.Framework.Core/Models/DatabaseObject.cs, Intersect.Client.Core/Entities/Entity.cs, Intersect.Client.Core/Entities/Resource.cs, Intersect.Client.Core/Networking/PacketHandler.cs, Intersect.Client.Framework/Entities/IResource.cs, Intersect.Server/Networking/NetworkedPacketHandler.cs
Resolves #1447 
client fixes:
- update resource instance descriptor (detect deletion)
- reload resource sprite on descriptor deletion
=> fix(1447): kill resource instances on save

Framework/Intersect.Framework.Core/GameObjects/Animations/AnimationSource.cs, Framework/Intersect.Framework.Core/GameObjects/Animations/AnimationSourceType.cs, Intersect (Core)/Network/Packets/Server/PlayAnimationPacket.cs, Intersect.Client.Core/Entities/Animation.cs, Intersect.Client.Core/Entities/Entity.cs, Intersect.Client.Core/Maps/MapAnimation.cs, Intersect.Client.Core/Maps/MapInstance.cs, Intersect.Client.Core/Networking/PacketHandler.cs, Intersect.Client.Framework/Maps/IMapInstance.cs, Intersect.Server.Core/Entities/Npc.cs, Intersect.Server.Core/Entities/Player.cs, Intersect.Server.Core/Networking/PacketSender.cs
=> fix(2120): send animation source information and use it to cancel spell cast animations

Intersect.Client.Core/Entities/Player.cs
=> fix(2521): change ClearTarget() to set _target to null

Intersect.Client.Core/Core/Main.cs, Intersect.Client.Core/General/Time.cs
=> Move Time.Update() back, use GetTime() to get real-world time when not ingame #2566

Intersect.Client.Core/Entities/Animation.cs, Intersect.Client.Core/Entities/Critter.cs, Intersect.Client.Core/Entities/Entity.cs, Intersect.Client.Core/Entities/Events/Event.cs, Intersect.Client.Core/Entities/Resource.cs, Intersect.Client.Core/Maps/MapInstance.cs, Intersect.Client.Core/Networking/PacketHandler.cs
=> Ensure that the animation list and lookup are kept appropriately in sync #2538

Intersect.Client.Framework/Gwen/Control/Base.cs
=> uniformly apply tabability criteria #2574

Intersect.Client.Core/Core/Controls/Controls.cs, Intersect.Client.Core/Entities/Player.cs, Intersect.Client.Core/Interface/Game/Bag/BagItem.cs, Intersect.Client.Core/Interface/Game/Bank/BankItem.cs, Intersect.Client.Core/Interface/Game/Character/EquipmentItem.cs, Intersect.Client.Core/Interface/Game/Crafting/RecipeItem.cs, Intersect.Client.Core/Interface/Game/Draggable.cs, Intersect.Client.Core/Interface/Game/EventWindow.cs, Intersect.Client.Core/Interface/Game/Hotbar/HotbarItem.cs, Intersect.Client.Core/Interface/Game/Inventory/InventoryItem.cs, Intersect.Client.Core/Interface/Game/MapItem/MapItemIcon.cs, Intersect.Client.Core/Interface/Game/Shop/ShopItem.cs, Intersect.Client.Core/Interface/Game/Spells/SpellItem.cs, Intersect.Client.Core/Interface/Game/TargetContextMenu.cs, Intersect.Client.Core/MonoGame/Input/MonoInput.cs, Intersect.Client.Framework/Input/ControlBinding.cs, Intersect.Client.Framework/Input/ControlMapping.cs, Intersect.Client.Framework/Input/GameInput.cs, Intersect.Client.Framework/Input/IGameInput.cs
=> UI actions need to be triggered by a change in input state #2581

Intersect.Client.Core/Entities/Player.cs
=> fix: Take into account Yes/No prompt for single items #2594

Framework/Intersect.Framework.Core/GameObjects/Maps/MapBase.cs, Intersect.Editor/Forms/DockingElements/frmMapEditor.cs, Intersect.Editor/Maps/MapInstance.cs, Intersect.Server.Core/Database/DbInterface.cs, Intersect.Server.Core/Maps/MapController.cs
=> fix: adapt c860bf7 from MAO for the base engine #2598

Intersect.Editor/Networking/PacketHandler.cs, Intersect.Network/LiteNetLib/AesAlgorithm.cs, Intersect.Network/LiteNetLib/AesGcmAlgorithm.cs, Intersect.Network/LiteNetLib/ISymmetricAlgorithm.cs, Intersect.Network/LiteNetLib/LiteNetLibConnection.cs, Intersect.Network/LiteNetLib/SymmetricAlgorithm.cs
=> fix encryption threading and map editor leak

Intersect.Client.Framework/Gwen/Control/ImagePanel.cs
=> fix: prevent fully resolved texture name from being emitted into the JSON #2626

Intersect.Client.Core/Interface/Game/DescriptionWindows/Components/DescriptionComponent.cs, Intersect.Client.Core/MonoGame/Graphics/MonoFont.cs, Intersect.Client.Core/MonoGame/Graphics/MonoRenderer.cs, Intersect.Client.Framework/Gwen/Control/ImagePanel.cs, Intersect.Client.Framework/Gwen/Control/RichLabel.cs, Intersect.Client.Framework/Gwen/Skin/Texturing/Bordered.cs
=> Force resize description to contents on creation, and resize container to contents

Intersect.Client.Core/Interface/Game/Bag/BagItem.cs, Intersect.Client.Core/Interface/Game/Bag/BagWindow.cs, Intersect.Client.Core/Interface/Game/GameInterface.cs, Intersect.Client.Core/Interface/Game/Inventory/InventoryItem.cs
assets: https://github.com/AscensionGameDev/Intersect-Assets/pull/66
https://github.com/user-attachments/assets/154c9e28-ee92-4e60-8d68-7eb2dace29be
=> refactor bag window/item

Framework/Intersect.Framework.Core/GameObjects/Conditions/ConditionMetadata/CombatCondition.cs, Framework/Intersect.Framework.Core/GameObjects/Conditions/ConditionType.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_ConditionalBranch.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server.Core/Entities/Events/Conditions.cs
resolves #2652
https://github.com/user-attachments/assets/01630594-918f-4177-bc12-12548ffacd62
=> feat: is on combat condition

Framework/Intersect.Framework.Core/GameObjects/Events/CommonEventTrigger.cs, Intersect.Editor/Forms/Editors/Events/frmEvent.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server.Core/Entities/Player.cs
https://github.com/user-attachments/assets/2f890e7e-3f0c-431d-a744-d3a5403d7683
=> feat: logout common event trigger

Intersect.Client.Core/Interface/Game/Bag/BagItem.cs, Intersect.Client.Core/Interface/Game/Bank/BankItem.cs, Intersect.Client.Core/Interface/Game/Bank/BankWindow.cs, Intersect.Client.Core/Interface/Game/GameInterface.cs, Intersect.Client.Core/Interface/Game/Inventory/InventoryItem.cs
https://github.com/user-attachments/assets/ddf40666-1026-4024-a74f-9feb94b451c0
=> refactor bank window/item

Framework/Intersect.Framework.Core/Config/PassabilityOptions.cs, Intersect.Client.Core/Entities/Entity.cs, Intersect.Server.Core/Entities/Player.cs
=> change passability to a more dynamic model #2660

Intersect.Server/Web/ApiService.AppSettings.cs
=> Fallback to the environment-specific config token instead of the generic token

Framework/Intersect.Framework.Core/GameObjects/Conditions/ConditionMetadata/IntegerVariableComparison.cs, Framework/Intersect.Framework.Core/GameObjects/Events/VariableComparator.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/Conditions/ConditionControl_PlayerStat.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/Conditions/ConditionControl_Variable.Designer.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/Conditions/ConditionControl_Variable.cs, Intersect.Editor/Localization/Strings.cs, Intersect.Server.Core/Entities/Events/Conditions.cs
adding the possibility to choose between a static value or another in the conditional branch of the is numeric variable
before:
now:
https://github.com/user-attachments/assets/20ee7e26-9454-4634-bbed-8379f650cb81
=> feat: added in between to static numeric variable comparison

Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_Warp.Designer.cs, Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_Warp.cs
=> enhancement: Replace sliders with numeric up/down for map coordinate input 

Intersect.Server.Core/Entities/Entity.cs
=> store the effect ID instead of the entity's ID

Intersect.Client.Core/Entities/Entity.cs
fixes infinite loop of animations overlapping on devices that have constant animations
=> fix equipment infinite animations
